export const PORTABLE_STATE_SCHEMA = 'peartube.portable-state'
export const PORTABLE_STATE_VERSION = 1

export const MAX_PORTABLE_MANIFEST_BYTES = 1024 * 1024
export const MAX_PORTABLE_ITEMS = 2048
export const MAX_PORTABLE_PUBLISHERS = 64
export const MAX_PORTABLE_ROOT_HISTORY = 256
export const MAX_PORTABLE_GRAPH_PREFERENCES = 512
export const MAX_PORTABLE_INDEX_PREFERENCES = 256
export const MAX_PORTABLE_FOLLOWED_FEEDS = 256
export const MAX_PORTABLE_ARCHIVE_EVIDENCE = 256
export const MAX_PORTABLE_EVIDENCE_BYTES = 64 * 1024
export const MAX_PORTABLE_STRING_BYTES = 256

export const PORTABLE_STATE_ERROR_CODES = Object.freeze({
  INVALID_REQUEST: 'PORTABLE_STATE_INVALID_REQUEST',
  TOO_LARGE: 'PORTABLE_STATE_TOO_LARGE',
  ITEM_LIMIT: 'PORTABLE_STATE_ITEM_LIMIT',
  UNSUPPORTED_VERSION: 'PORTABLE_STATE_UNSUPPORTED_VERSION',
  NONCANONICAL: 'PORTABLE_STATE_NONCANONICAL',
  CHECKSUM_MISMATCH: 'PORTABLE_STATE_CHECKSUM_MISMATCH',
  SIGNATURE_INVALID: 'PORTABLE_STATE_SIGNATURE_INVALID',
  CHECKPOINT_INVALID: 'PORTABLE_STATE_CHECKPOINT_INVALID',
  DUPLICATE_ID: 'PORTABLE_STATE_DUPLICATE_ID',
  UNKNOWN_FIELD: 'PORTABLE_STATE_UNKNOWN_FIELD',
  INVALID_FIELD: 'PORTABLE_STATE_INVALID_FIELD',
  EXPORT_FAILED: 'PORTABLE_STATE_EXPORT_FAILED',
  TRANSACTION_FAILED: 'PORTABLE_STATE_TRANSACTION_FAILED'
})
