#include "NitroVLCOnLoad.hpp"

#include <fbjni/fbjni.h>
#include <jni.h>

#include <NitroModules/DefaultConstructableObject.hpp>
#include <NitroModules/HybridObjectRegistry.hpp>

#include "JFunc_void_OnPlayingEventProps.hpp"
#include "JFunc_void_OnProgressEventProps.hpp"
#include "JFunc_void_SimpleCallbackEventProps.hpp"
#include "JFunc_void_VideoInfo.hpp"
#include "JHybridNitroVLCModuleSpec.hpp"
#include "JHybridNitroVLCViewSpec.hpp"

namespace margelo::nitro::nitrovlc {

int initialize(JavaVM* vm) {
  using namespace facebook;
  using namespace margelo::nitro;
  using namespace margelo::nitro::nitrovlc;

  return jni::initialize(vm, [] {
    // Register native JNI methods generated by Nitrogen.
    JHybridNitroVLCViewSpec::registerNatives();
    JFunc_void_OnPlayingEventProps_cxx::registerNatives();
    JFunc_void_OnProgressEventProps_cxx::registerNatives();
    JFunc_void_SimpleCallbackEventProps_cxx::registerNatives();
    JFunc_void_VideoInfo_cxx::registerNatives();
    JHybridNitroVLCModuleSpec::registerNatives();

    // Register Nitro Hybrid Objects.
    //
    // Important: We intentionally do NOT register "NitroVLCView" here.
    // The rendered view is a plain RN ViewManager (NitroVLCViewManager.kt),
    // and HybridNitroVLCView instances are created by that ViewManager and
    // then looked up via NitroVLCModule.getView(viewId). This avoids the
    // Nitrogen-generated Fabric HybridView integration (CachedProp/StateUpdater)
    // which has caused native crashes on Android.
    HybridObjectRegistry::registerHybridObjectConstructor(
      "NitroVLCModule",
      []() -> std::shared_ptr<HybridObject> {
        static DefaultConstructableObject<JHybridNitroVLCModuleSpec::javaobject> object(
          "com/margelo/nitro/com/nitrovlc/HybridNitroVLCModule"
        );
        auto instance = object.create();
        return instance->cthis()->shared();
      }
    );
  });
}

} // namespace margelo::nitro::nitrovlc

