// This file is autogenerated by the hrpc compiler
/* eslint-disable camelcase */
/* eslint-disable space-before-function-paren */

const { c, RPC, RPCStream, RPCRequestStream } = require('hrpc/runtime')
const { getEncoding } = require('./messages.js')

const methods = new Map([
  ['@peartube/create-identity', 0],
  [0, '@peartube/create-identity'],
  ['@peartube/get-identity', 1],
  [1, '@peartube/get-identity'],
  ['@peartube/get-identities', 2],
  [2, '@peartube/get-identities'],
  ['@peartube/set-active-identity', 3],
  [3, '@peartube/set-active-identity'],
  ['@peartube/recover-identity', 4],
  [4, '@peartube/recover-identity'],
  ['@peartube/bootstrap-device', 5],
  [5, '@peartube/bootstrap-device'],
  ['@peartube/attest-device', 6],
  [6, '@peartube/attest-device'],
  ['@peartube/verify-attestation', 7],
  [7, '@peartube/verify-attestation'],
  ['@peartube/get-channel', 8],
  [8, '@peartube/get-channel'],
  ['@peartube/update-channel', 9],
  [9, '@peartube/update-channel'],
  ['@peartube/list-videos', 10],
  [10, '@peartube/list-videos'],
  ['@peartube/get-video-url', 11],
  [11, '@peartube/get-video-url'],
  ['@peartube/prepare-playback', 12],
  [12, '@peartube/prepare-playback'],
  ['@peartube/get-video-data', 13],
  [13, '@peartube/get-video-data'],
  ['@peartube/upload-video', 14],
  [14, '@peartube/upload-video'],
  ['@peartube/download-video', 15],
  [15, '@peartube/download-video'],
  ['@peartube/delete-video', 16],
  [16, '@peartube/delete-video'],
  ['@peartube/subscribe-channel', 17],
  [17, '@peartube/subscribe-channel'],
  ['@peartube/unsubscribe-channel', 18],
  [18, '@peartube/unsubscribe-channel'],
  ['@peartube/get-subscriptions', 19],
  [19, '@peartube/get-subscriptions'],
  ['@peartube/join-channel', 20],
  [20, '@peartube/join-channel'],
  ['@peartube/get-public-feed', 21],
  [21, '@peartube/get-public-feed'],
  ['@peartube/refresh-feed', 22],
  [22, '@peartube/refresh-feed'],
  ['@peartube/submit-to-feed', 23],
  [23, '@peartube/submit-to-feed'],
  ['@peartube/unpublish-from-feed', 24],
  [24, '@peartube/unpublish-from-feed'],
  ['@peartube/is-channel-published', 25],
  [25, '@peartube/is-channel-published'],
  ['@peartube/hide-channel', 26],
  [26, '@peartube/hide-channel'],
  ['@peartube/get-channel-meta', 27],
  [27, '@peartube/get-channel-meta'],
  ['@peartube/get-swarm-status', 28],
  [28, '@peartube/get-swarm-status'],
  ['@peartube/create-device-invite', 29],
  [29, '@peartube/create-device-invite'],
  ['@peartube/pair-device', 30],
  [30, '@peartube/pair-device'],
  ['@peartube/list-devices', 31],
  [31, '@peartube/list-devices'],
  ['@peartube/retry-sync-channel', 32],
  [32, '@peartube/retry-sync-channel'],
  ['@peartube/prefetch-video', 33],
  [33, '@peartube/prefetch-video'],
  ['@peartube/get-video-stats', 34],
  [34, '@peartube/get-video-stats'],
  ['@peartube/get-seeding-status', 35],
  [35, '@peartube/get-seeding-status'],
  ['@peartube/set-seeding-config', 36],
  [36, '@peartube/set-seeding-config'],
  ['@peartube/get-transcode-settings', 37],
  [37, '@peartube/get-transcode-settings'],
  ['@peartube/set-transcode-settings', 38],
  [38, '@peartube/set-transcode-settings'],
  ['@peartube/pin-channel', 39],
  [39, '@peartube/pin-channel'],
  ['@peartube/unpin-channel', 40],
  [40, '@peartube/unpin-channel'],
  ['@peartube/get-pinned-channels', 41],
  [41, '@peartube/get-pinned-channels'],
  ['@peartube/get-storage-stats', 42],
  [42, '@peartube/get-storage-stats'],
  ['@peartube/set-storage-limit', 43],
  [43, '@peartube/set-storage-limit'],
  ['@peartube/clear-cache', 44],
  [44, '@peartube/clear-cache'],
  ['@peartube/get-video-thumbnail', 45],
  [45, '@peartube/get-video-thumbnail'],
  ['@peartube/get-video-metadata', 46],
  [46, '@peartube/get-video-metadata'],
  ['@peartube/set-video-thumbnail', 47],
  [47, '@peartube/set-video-thumbnail'],
  ['@peartube/set-video-thumbnail-from-file', 48],
  [48, '@peartube/set-video-thumbnail-from-file'],
  ['@peartube/get-status', 49],
  [49, '@peartube/get-status'],
  ['@peartube/pick-video-file', 50],
  [50, '@peartube/pick-video-file'],
  ['@peartube/pick-image-file', 51],
  [51, '@peartube/pick-image-file'],
  ['@peartube/get-blob-server-port', 52],
  [52, '@peartube/get-blob-server-port'],
  ['@peartube/global-search-videos', 53],
  [53, '@peartube/global-search-videos'],
  ['@peartube/add-comment', 54],
  [54, '@peartube/add-comment'],
  ['@peartube/list-comments', 55],
  [55, '@peartube/list-comments'],
  ['@peartube/hide-comment', 56],
  [56, '@peartube/hide-comment'],
  ['@peartube/remove-comment', 57],
  [57, '@peartube/remove-comment'],
  ['@peartube/add-reaction', 58],
  [58, '@peartube/add-reaction'],
  ['@peartube/remove-reaction', 59],
  [59, '@peartube/remove-reaction'],
  ['@peartube/get-reactions', 60],
  [60, '@peartube/get-reactions'],
  ['@peartube/event-ready', 61],
  [61, '@peartube/event-ready'],
  ['@peartube/event-error', 62],
  [62, '@peartube/event-error'],
  ['@peartube/event-upload-progress', 63],
  [63, '@peartube/event-upload-progress'],
  ['@peartube/event-download-progress', 64],
  [64, '@peartube/event-download-progress'],
  ['@peartube/event-feed-update', 65],
  [65, '@peartube/event-feed-update'],
  ['@peartube/event-log', 66],
  [66, '@peartube/event-log'],
  ['@peartube/event-video-stats', 67],
  [67, '@peartube/event-video-stats'],
  ['@peartube/cast-available', 68],
  [68, '@peartube/cast-available'],
  ['@peartube/cast-start-discovery', 69],
  [69, '@peartube/cast-start-discovery'],
  ['@peartube/cast-stop-discovery', 70],
  [70, '@peartube/cast-stop-discovery'],
  ['@peartube/cast-get-devices', 71],
  [71, '@peartube/cast-get-devices'],
  ['@peartube/cast-add-manual-device', 72],
  [72, '@peartube/cast-add-manual-device'],
  ['@peartube/cast-connect', 73],
  [73, '@peartube/cast-connect'],
  ['@peartube/cast-disconnect', 74],
  [74, '@peartube/cast-disconnect'],
  ['@peartube/cast-play', 75],
  [75, '@peartube/cast-play'],
  ['@peartube/cast-pause', 76],
  [76, '@peartube/cast-pause'],
  ['@peartube/cast-resume', 77],
  [77, '@peartube/cast-resume'],
  ['@peartube/cast-stop', 78],
  [78, '@peartube/cast-stop'],
  ['@peartube/cast-seek', 79],
  [79, '@peartube/cast-seek'],
  ['@peartube/cast-set-volume', 80],
  [80, '@peartube/cast-set-volume'],
  ['@peartube/cast-get-state', 81],
  [81, '@peartube/cast-get-state'],
  ['@peartube/cast-is-connected', 82],
  [82, '@peartube/cast-is-connected'],
  ['@peartube/event-cast-device-found', 83],
  [83, '@peartube/event-cast-device-found'],
  ['@peartube/event-cast-device-lost', 84],
  [84, '@peartube/event-cast-device-lost'],
  ['@peartube/event-cast-playback-state', 85],
  [85, '@peartube/event-cast-playback-state'],
  ['@peartube/event-cast-time-update', 86],
  [86, '@peartube/event-cast-time-update'],
  ['@peartube/search-videos', 87],
  [87, '@peartube/search-videos'],
  ['@peartube/log-watch-event', 88],
  [88, '@peartube/log-watch-event'],
  ['@peartube/index-video-vectors', 89],
  [89, '@peartube/index-video-vectors'],
  ['@peartube/get-recommendations', 90],
  [90, '@peartube/get-recommendations'],
  ['@peartube/get-video-recommendations', 91],
  [91, '@peartube/get-video-recommendations'],
  ['@peartube/update-video-metadata', 92],
  [92, '@peartube/update-video-metadata'],
  ['@peartube/web-prepare-playback', 93],
  [93, '@peartube/web-prepare-playback'],
  ['@peartube/desktop-bootstrap', 94],
  [94, '@peartube/desktop-bootstrap'],
  ['@peartube/desktop-shutdown', 95],
  [95, '@peartube/desktop-shutdown'],
  ['@peartube/desktop-refresh-browse', 96],
  [96, '@peartube/desktop-refresh-browse'],
  ['@peartube/mpv-available', 97],
  [97, '@peartube/mpv-available'],
  ['@peartube/mpv-create', 98],
  [98, '@peartube/mpv-create'],
  ['@peartube/mpv-load-file', 99],
  [99, '@peartube/mpv-load-file'],
  ['@peartube/mpv-play', 100],
  [100, '@peartube/mpv-play'],
  ['@peartube/mpv-pause', 101],
  [101, '@peartube/mpv-pause'],
  ['@peartube/mpv-seek', 102],
  [102, '@peartube/mpv-seek'],
  ['@peartube/mpv-get-state', 103],
  [103, '@peartube/mpv-get-state'],
  ['@peartube/mpv-render-frame', 104],
  [104, '@peartube/mpv-render-frame'],
  ['@peartube/mpv-destroy', 105],
  [105, '@peartube/mpv-destroy'],
  ['@peartube/ffmpeg-decode-available', 106],
  [106, '@peartube/ffmpeg-decode-available'],
  ['@peartube/update-channel-avatar', 107],
  [107, '@peartube/update-channel-avatar'],
  ['@peartube/transcode-start', 108],
  [108, '@peartube/transcode-start'],
  ['@peartube/transcode-stop', 109],
  [109, '@peartube/transcode-stop'],
  ['@peartube/transcode-status', 110],
  [110, '@peartube/transcode-status'],
  ['@peartube/event-transcode-progress', 111],
  [111, '@peartube/event-transcode-progress']
])

class HRPC {
  constructor(stream) {
    this._stream = stream
    this._handlers = []
    this._requestEncodings = new Map([
      ['@peartube/create-identity', getEncoding('@peartube/create-identity-request')],
      ['@peartube/get-identity', getEncoding('@peartube/get-identity-request')],
      ['@peartube/get-identities', getEncoding('@peartube/get-identities-request')],
      ['@peartube/set-active-identity', getEncoding('@peartube/set-active-identity-request')],
      ['@peartube/recover-identity', getEncoding('@peartube/recover-identity-request')],
      ['@peartube/bootstrap-device', getEncoding('@peartube/bootstrap-device-request')],
      ['@peartube/attest-device', getEncoding('@peartube/attest-device-request')],
      ['@peartube/verify-attestation', getEncoding('@peartube/verify-attestation-request')],
      ['@peartube/get-channel', getEncoding('@peartube/get-channel-request')],
      ['@peartube/update-channel', getEncoding('@peartube/update-channel-request')],
      ['@peartube/list-videos', getEncoding('@peartube/list-videos-request')],
      ['@peartube/get-video-url', getEncoding('@peartube/get-video-url-request')],
      ['@peartube/prepare-playback', getEncoding('@peartube/prepare-playback-request')],
      ['@peartube/get-video-data', getEncoding('@peartube/get-video-data-request')],
      ['@peartube/upload-video', getEncoding('@peartube/upload-video-request')],
      ['@peartube/download-video', getEncoding('@peartube/download-video-request')],
      ['@peartube/delete-video', getEncoding('@peartube/delete-video-request')],
      ['@peartube/subscribe-channel', getEncoding('@peartube/subscribe-channel-request')],
      ['@peartube/unsubscribe-channel', getEncoding('@peartube/unsubscribe-channel-request')],
      ['@peartube/get-subscriptions', getEncoding('@peartube/get-subscriptions-request')],
      ['@peartube/join-channel', getEncoding('@peartube/join-channel-request')],
      ['@peartube/get-public-feed', getEncoding('@peartube/get-public-feed-request')],
      ['@peartube/refresh-feed', getEncoding('@peartube/refresh-feed-request')],
      ['@peartube/submit-to-feed', getEncoding('@peartube/submit-to-feed-request')],
      ['@peartube/unpublish-from-feed', getEncoding('@peartube/unpublish-from-feed-request')],
      ['@peartube/is-channel-published', getEncoding('@peartube/is-channel-published-request')],
      ['@peartube/hide-channel', getEncoding('@peartube/hide-channel-request')],
      ['@peartube/get-channel-meta', getEncoding('@peartube/get-channel-meta-request')],
      ['@peartube/get-swarm-status', getEncoding('@peartube/get-swarm-status-request')],
      ['@peartube/create-device-invite', getEncoding('@peartube/create-device-invite-request')],
      ['@peartube/pair-device', getEncoding('@peartube/pair-device-request')],
      ['@peartube/list-devices', getEncoding('@peartube/list-devices-request')],
      ['@peartube/retry-sync-channel', getEncoding('@peartube/retry-sync-channel-request')],
      ['@peartube/prefetch-video', getEncoding('@peartube/prefetch-video-request')],
      ['@peartube/get-video-stats', getEncoding('@peartube/get-video-stats-request')],
      ['@peartube/get-seeding-status', getEncoding('@peartube/get-seeding-status-request')],
      ['@peartube/set-seeding-config', getEncoding('@peartube/set-seeding-config-request')],
      ['@peartube/get-transcode-settings', getEncoding('@peartube/get-transcode-settings-request')],
      ['@peartube/set-transcode-settings', getEncoding('@peartube/set-transcode-settings-request')],
      ['@peartube/pin-channel', getEncoding('@peartube/pin-channel-request')],
      ['@peartube/unpin-channel', getEncoding('@peartube/unpin-channel-request')],
      ['@peartube/get-pinned-channels', getEncoding('@peartube/get-pinned-channels-request')],
      ['@peartube/get-storage-stats', getEncoding('@peartube/get-storage-stats-request')],
      ['@peartube/set-storage-limit', getEncoding('@peartube/set-storage-limit-request')],
      ['@peartube/clear-cache', getEncoding('@peartube/clear-cache-request')],
      ['@peartube/get-video-thumbnail', getEncoding('@peartube/get-video-thumbnail-request')],
      ['@peartube/get-video-metadata', getEncoding('@peartube/get-video-metadata-request')],
      ['@peartube/set-video-thumbnail', getEncoding('@peartube/set-video-thumbnail-request')],
      ['@peartube/set-video-thumbnail-from-file', getEncoding('@peartube/set-video-thumbnail-from-file-request')],
      ['@peartube/get-status', getEncoding('@peartube/get-status-request')],
      ['@peartube/pick-video-file', getEncoding('@peartube/pick-video-file-request')],
      ['@peartube/pick-image-file', getEncoding('@peartube/pick-image-file-request')],
      ['@peartube/get-blob-server-port', getEncoding('@peartube/get-blob-server-port-request')],
      ['@peartube/global-search-videos', getEncoding('@peartube/global-search-videos-request')],
      ['@peartube/add-comment', getEncoding('@peartube/add-comment-request')],
      ['@peartube/list-comments', getEncoding('@peartube/list-comments-request')],
      ['@peartube/hide-comment', getEncoding('@peartube/hide-comment-request')],
      ['@peartube/remove-comment', getEncoding('@peartube/remove-comment-request')],
      ['@peartube/add-reaction', getEncoding('@peartube/add-reaction-request')],
      ['@peartube/remove-reaction', getEncoding('@peartube/remove-reaction-request')],
      ['@peartube/get-reactions', getEncoding('@peartube/get-reactions-request')],
      ['@peartube/event-ready', getEncoding('@peartube/event-ready')],
      ['@peartube/event-error', getEncoding('@peartube/event-error')],
      ['@peartube/event-upload-progress', getEncoding('@peartube/event-upload-progress')],
      ['@peartube/event-download-progress', getEncoding('@peartube/event-download-progress')],
      ['@peartube/event-feed-update', getEncoding('@peartube/event-feed-update')],
      ['@peartube/event-log', getEncoding('@peartube/event-log')],
      ['@peartube/event-video-stats', getEncoding('@peartube/event-video-stats')],
      ['@peartube/cast-available', getEncoding('@peartube/cast-available-request')],
      ['@peartube/cast-start-discovery', getEncoding('@peartube/cast-start-discovery-request')],
      ['@peartube/cast-stop-discovery', getEncoding('@peartube/cast-stop-discovery-request')],
      ['@peartube/cast-get-devices', getEncoding('@peartube/cast-get-devices-request')],
      ['@peartube/cast-add-manual-device', getEncoding('@peartube/cast-add-manual-device-request')],
      ['@peartube/cast-connect', getEncoding('@peartube/cast-connect-request')],
      ['@peartube/cast-disconnect', getEncoding('@peartube/cast-disconnect-request')],
      ['@peartube/cast-play', getEncoding('@peartube/cast-play-request')],
      ['@peartube/cast-pause', getEncoding('@peartube/cast-pause-request')],
      ['@peartube/cast-resume', getEncoding('@peartube/cast-resume-request')],
      ['@peartube/cast-stop', getEncoding('@peartube/cast-stop-request')],
      ['@peartube/cast-seek', getEncoding('@peartube/cast-seek-request')],
      ['@peartube/cast-set-volume', getEncoding('@peartube/cast-set-volume-request')],
      ['@peartube/cast-get-state', getEncoding('@peartube/cast-get-state-request')],
      ['@peartube/cast-is-connected', getEncoding('@peartube/cast-is-connected-request')],
      ['@peartube/event-cast-device-found', getEncoding('@peartube/event-cast-device-found')],
      ['@peartube/event-cast-device-lost', getEncoding('@peartube/event-cast-device-lost')],
      ['@peartube/event-cast-playback-state', getEncoding('@peartube/event-cast-playback-state')],
      ['@peartube/event-cast-time-update', getEncoding('@peartube/event-cast-time-update')],
      ['@peartube/search-videos', getEncoding('@peartube/search-videos-request')],
      ['@peartube/log-watch-event', getEncoding('@peartube/log-watch-event-request')],
      ['@peartube/index-video-vectors', getEncoding('@peartube/index-video-vectors-request')],
      ['@peartube/get-recommendations', getEncoding('@peartube/get-recommendations-request')],
      ['@peartube/get-video-recommendations', getEncoding('@peartube/get-video-recommendations-request')],
      ['@peartube/update-video-metadata', getEncoding('@peartube/update-video-metadata-request')],
      ['@peartube/web-prepare-playback', getEncoding('@peartube/prepare-playback-request')],
      ['@peartube/desktop-bootstrap', getEncoding('@peartube/desktop-bootstrap-request')],
      ['@peartube/desktop-shutdown', getEncoding('@peartube/desktop-shutdown-request')],
      ['@peartube/desktop-refresh-browse', getEncoding('@peartube/desktop-refresh-browse-request')],
      ['@peartube/mpv-available', getEncoding('@peartube/mpv-available-request')],
      ['@peartube/mpv-create', getEncoding('@peartube/mpv-create-request')],
      ['@peartube/mpv-load-file', getEncoding('@peartube/mpv-load-file-request')],
      ['@peartube/mpv-play', getEncoding('@peartube/mpv-player-request')],
      ['@peartube/mpv-pause', getEncoding('@peartube/mpv-player-request')],
      ['@peartube/mpv-seek', getEncoding('@peartube/mpv-seek-request')],
      ['@peartube/mpv-get-state', getEncoding('@peartube/mpv-player-request')],
      ['@peartube/mpv-render-frame', getEncoding('@peartube/mpv-player-request')],
      ['@peartube/mpv-destroy', getEncoding('@peartube/mpv-player-request')],
      ['@peartube/ffmpeg-decode-available', getEncoding('@peartube/ffmpeg-decode-available-request')],
      ['@peartube/update-channel-avatar', getEncoding('@peartube/update-channel-avatar-request')],
      ['@peartube/transcode-start', getEncoding('@peartube/transcode-start-request')],
      ['@peartube/transcode-stop', getEncoding('@peartube/transcode-stop-request')],
      ['@peartube/transcode-status', getEncoding('@peartube/transcode-status-request')],
      ['@peartube/event-transcode-progress', getEncoding('@peartube/event-transcode-progress')]
    ])
    this._responseEncodings = new Map([
      ['@peartube/create-identity', getEncoding('@peartube/create-identity-response')],
      ['@peartube/get-identity', getEncoding('@peartube/get-identity-response')],
      ['@peartube/get-identities', getEncoding('@peartube/get-identities-response')],
      ['@peartube/set-active-identity', getEncoding('@peartube/set-active-identity-response')],
      ['@peartube/recover-identity', getEncoding('@peartube/recover-identity-response')],
      ['@peartube/bootstrap-device', getEncoding('@peartube/bootstrap-device-response')],
      ['@peartube/attest-device', getEncoding('@peartube/attest-device-response')],
      ['@peartube/verify-attestation', getEncoding('@peartube/verify-attestation-response')],
      ['@peartube/get-channel', getEncoding('@peartube/get-channel-response')],
      ['@peartube/update-channel', getEncoding('@peartube/update-channel-response')],
      ['@peartube/list-videos', getEncoding('@peartube/list-videos-response')],
      ['@peartube/get-video-url', getEncoding('@peartube/get-video-url-response')],
      ['@peartube/prepare-playback', getEncoding('@peartube/prepare-playback-response')],
      ['@peartube/get-video-data', getEncoding('@peartube/get-video-data-response')],
      ['@peartube/upload-video', getEncoding('@peartube/upload-video-response')],
      ['@peartube/download-video', getEncoding('@peartube/download-video-response')],
      ['@peartube/delete-video', getEncoding('@peartube/delete-video-response')],
      ['@peartube/subscribe-channel', getEncoding('@peartube/subscribe-channel-response')],
      ['@peartube/unsubscribe-channel', getEncoding('@peartube/unsubscribe-channel-response')],
      ['@peartube/get-subscriptions', getEncoding('@peartube/get-subscriptions-response')],
      ['@peartube/join-channel', getEncoding('@peartube/join-channel-response')],
      ['@peartube/get-public-feed', getEncoding('@peartube/get-public-feed-response')],
      ['@peartube/refresh-feed', getEncoding('@peartube/refresh-feed-response')],
      ['@peartube/submit-to-feed', getEncoding('@peartube/submit-to-feed-response')],
      ['@peartube/unpublish-from-feed', getEncoding('@peartube/unpublish-from-feed-response')],
      ['@peartube/is-channel-published', getEncoding('@peartube/is-channel-published-response')],
      ['@peartube/hide-channel', getEncoding('@peartube/hide-channel-response')],
      ['@peartube/get-channel-meta', getEncoding('@peartube/get-channel-meta-response')],
      ['@peartube/get-swarm-status', getEncoding('@peartube/get-swarm-status-response')],
      ['@peartube/create-device-invite', getEncoding('@peartube/create-device-invite-response')],
      ['@peartube/pair-device', getEncoding('@peartube/pair-device-response')],
      ['@peartube/list-devices', getEncoding('@peartube/list-devices-response')],
      ['@peartube/retry-sync-channel', getEncoding('@peartube/retry-sync-channel-response')],
      ['@peartube/prefetch-video', getEncoding('@peartube/prefetch-video-response')],
      ['@peartube/get-video-stats', getEncoding('@peartube/get-video-stats-response')],
      ['@peartube/get-seeding-status', getEncoding('@peartube/get-seeding-status-response')],
      ['@peartube/set-seeding-config', getEncoding('@peartube/set-seeding-config-response')],
      ['@peartube/get-transcode-settings', getEncoding('@peartube/get-transcode-settings-response')],
      ['@peartube/set-transcode-settings', getEncoding('@peartube/set-transcode-settings-response')],
      ['@peartube/pin-channel', getEncoding('@peartube/pin-channel-response')],
      ['@peartube/unpin-channel', getEncoding('@peartube/unpin-channel-response')],
      ['@peartube/get-pinned-channels', getEncoding('@peartube/get-pinned-channels-response')],
      ['@peartube/get-storage-stats', getEncoding('@peartube/get-storage-stats-response')],
      ['@peartube/set-storage-limit', getEncoding('@peartube/set-storage-limit-response')],
      ['@peartube/clear-cache', getEncoding('@peartube/clear-cache-response')],
      ['@peartube/get-video-thumbnail', getEncoding('@peartube/get-video-thumbnail-response')],
      ['@peartube/get-video-metadata', getEncoding('@peartube/get-video-metadata-response')],
      ['@peartube/set-video-thumbnail', getEncoding('@peartube/set-video-thumbnail-response')],
      ['@peartube/set-video-thumbnail-from-file', getEncoding('@peartube/set-video-thumbnail-from-file-response')],
      ['@peartube/get-status', getEncoding('@peartube/get-status-response')],
      ['@peartube/pick-video-file', getEncoding('@peartube/pick-video-file-response')],
      ['@peartube/pick-image-file', getEncoding('@peartube/pick-image-file-response')],
      ['@peartube/get-blob-server-port', getEncoding('@peartube/get-blob-server-port-response')],
      ['@peartube/global-search-videos', getEncoding('@peartube/global-search-videos-response')],
      ['@peartube/add-comment', getEncoding('@peartube/add-comment-response')],
      ['@peartube/list-comments', getEncoding('@peartube/list-comments-response')],
      ['@peartube/hide-comment', getEncoding('@peartube/hide-comment-response')],
      ['@peartube/remove-comment', getEncoding('@peartube/remove-comment-response')],
      ['@peartube/add-reaction', getEncoding('@peartube/add-reaction-response')],
      ['@peartube/remove-reaction', getEncoding('@peartube/remove-reaction-response')],
      ['@peartube/get-reactions', getEncoding('@peartube/get-reactions-response')],
      ['@peartube/cast-available', getEncoding('@peartube/cast-available-response')],
      ['@peartube/cast-start-discovery', getEncoding('@peartube/cast-start-discovery-response')],
      ['@peartube/cast-stop-discovery', getEncoding('@peartube/cast-stop-discovery-response')],
      ['@peartube/cast-get-devices', getEncoding('@peartube/cast-get-devices-response')],
      ['@peartube/cast-add-manual-device', getEncoding('@peartube/cast-add-manual-device-response')],
      ['@peartube/cast-connect', getEncoding('@peartube/cast-connect-response')],
      ['@peartube/cast-disconnect', getEncoding('@peartube/cast-disconnect-response')],
      ['@peartube/cast-play', getEncoding('@peartube/cast-play-response')],
      ['@peartube/cast-pause', getEncoding('@peartube/cast-pause-response')],
      ['@peartube/cast-resume', getEncoding('@peartube/cast-resume-response')],
      ['@peartube/cast-stop', getEncoding('@peartube/cast-stop-response')],
      ['@peartube/cast-seek', getEncoding('@peartube/cast-seek-response')],
      ['@peartube/cast-set-volume', getEncoding('@peartube/cast-set-volume-response')],
      ['@peartube/cast-get-state', getEncoding('@peartube/cast-get-state-response')],
      ['@peartube/cast-is-connected', getEncoding('@peartube/cast-is-connected-response')],
      ['@peartube/search-videos', getEncoding('@peartube/search-videos-response')],
      ['@peartube/log-watch-event', getEncoding('@peartube/log-watch-event-response')],
      ['@peartube/index-video-vectors', getEncoding('@peartube/index-video-vectors-response')],
      ['@peartube/get-recommendations', getEncoding('@peartube/get-recommendations-response')],
      ['@peartube/get-video-recommendations', getEncoding('@peartube/get-video-recommendations-response')],
      ['@peartube/update-video-metadata', getEncoding('@peartube/update-video-metadata-response')],
      ['@peartube/web-prepare-playback', getEncoding('@peartube/web-prepare-playback-response')],
      ['@peartube/desktop-bootstrap', getEncoding('@peartube/desktop-bootstrap-response')],
      ['@peartube/desktop-shutdown', getEncoding('@peartube/desktop-shutdown-response')],
      ['@peartube/desktop-refresh-browse', getEncoding('@peartube/desktop-refresh-browse-response')],
      ['@peartube/mpv-available', getEncoding('@peartube/mpv-available-response')],
      ['@peartube/mpv-create', getEncoding('@peartube/mpv-create-response')],
      ['@peartube/mpv-load-file', getEncoding('@peartube/mpv-player-response')],
      ['@peartube/mpv-play', getEncoding('@peartube/mpv-player-response')],
      ['@peartube/mpv-pause', getEncoding('@peartube/mpv-player-response')],
      ['@peartube/mpv-seek', getEncoding('@peartube/mpv-player-response')],
      ['@peartube/mpv-get-state', getEncoding('@peartube/mpv-state-response')],
      ['@peartube/mpv-render-frame', getEncoding('@peartube/mpv-render-frame-response')],
      ['@peartube/mpv-destroy', getEncoding('@peartube/mpv-player-response')],
      ['@peartube/ffmpeg-decode-available', getEncoding('@peartube/ffmpeg-decode-available-response')],
      ['@peartube/update-channel-avatar', getEncoding('@peartube/update-channel-avatar-response')],
      ['@peartube/transcode-start', getEncoding('@peartube/transcode-start-response')],
      ['@peartube/transcode-stop', getEncoding('@peartube/transcode-stop-response')],
      ['@peartube/transcode-status', getEncoding('@peartube/transcode-status-response')]
    ])
    this._rpc = new RPC(stream, async (req) => {
      const command = methods.get(req.command)
      if (!command || typeof this._handlers[command] !== 'function') return
      const responseEncoding = this._responseEncodings.get(command)
      const requestEncoding = this._requestEncodings.get(command)
      if (this._requestIsSend(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        await this._handlers[command](request)
        return
      }
      if (!this._requestIsStream(command) && !this._responseIsStream(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        const response = await this._handlers[command](request)
        req.reply(c.encode(responseEncoding, response))
      }
      if (!this._requestIsStream(command) && this._responseIsStream(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        const responseStream = new RPCStream(
          null,
          null,
          req.createResponseStream(),
          responseEncoding
        )
        responseStream.data = request
        await this._handlers[command](responseStream)
      }
      if (this._requestIsStream(command) && !this._responseIsStream(command)) {
        const requestStream = new RPCRequestStream(
          req,
          responseEncoding,
          req.createRequestStream(),
          requestEncoding
        )
        const response = await this._handlers[command](requestStream)
        req.reply(c.encode(responseEncoding, response))
      }
      if (this._requestIsStream(command) && this._responseIsStream(command)) {
        const requestStream = new RPCRequestStream(
          req,
          responseEncoding,
          req.createRequestStream(),
          requestEncoding,
          req.createResponseStream(),
          responseEncoding
        )
        await this._handlers[command](requestStream)
      }
    })
  }

  async _call(name, args) {
    const requestEncoding = this._requestEncodings.get(name)
    const responseEncoding = this._responseEncodings.get(name)
    const request = this._rpc.request(methods.get(name))
    const encoded = c.encode(requestEncoding, args)
    request.send(encoded)
    return c.decode(responseEncoding, await request.reply())
  }

  _callSync(name, args) {
    const requestEncoding = this._requestEncodings.get(name)
    const responseEncoding = this._responseEncodings.get(name)
    if (this._requestIsSend(name)) {
      const encoded = c.encode(requestEncoding, args)
      const request = this._rpc.event(methods.get(name))
      request.send(encoded)
    }

    const request = this._rpc.request(methods.get(name))

    if (!this._requestIsStream(name) && this._responseIsStream(name)) {
      const encoded = c.encode(requestEncoding, args)
      request.send(encoded)
      return new RPCStream(request.createResponseStream(), responseEncoding)
    }
    if (this._requestIsStream(name) && !this._responseIsStream(name)) {
      return new RPCRequestStream(
        request,
        responseEncoding,
        null,
        null,
        request.createRequestStream(),
        requestEncoding
      )
    }
    if (this._requestIsStream(name) && this._responseIsStream(name)) {
      return new RPCRequestStream(
        request,
        responseEncoding,
        request.createResponseStream(),
        responseEncoding,
        request.createRequestStream(),
        requestEncoding
      )
    }
  }

  async createIdentity(args) {
    return this._call('@peartube/create-identity', args)
  }

  async getIdentity(args) {
    return this._call('@peartube/get-identity', args)
  }

  async getIdentities(args) {
    return this._call('@peartube/get-identities', args)
  }

  async setActiveIdentity(args) {
    return this._call('@peartube/set-active-identity', args)
  }

  async recoverIdentity(args) {
    return this._call('@peartube/recover-identity', args)
  }

  async bootstrapDevice(args) {
    return this._call('@peartube/bootstrap-device', args)
  }

  async attestDevice(args) {
    return this._call('@peartube/attest-device', args)
  }

  async verifyAttestation(args) {
    return this._call('@peartube/verify-attestation', args)
  }

  async getChannel(args) {
    return this._call('@peartube/get-channel', args)
  }

  async updateChannel(args) {
    return this._call('@peartube/update-channel', args)
  }

  async listVideos(args) {
    return this._call('@peartube/list-videos', args)
  }

  async getVideoUrl(args) {
    return this._call('@peartube/get-video-url', args)
  }

  async preparePlayback(args) {
    return this._call('@peartube/prepare-playback', args)
  }

  async getVideoData(args) {
    return this._call('@peartube/get-video-data', args)
  }

  async uploadVideo(args) {
    return this._call('@peartube/upload-video', args)
  }

  async downloadVideo(args) {
    return this._call('@peartube/download-video', args)
  }

  async deleteVideo(args) {
    return this._call('@peartube/delete-video', args)
  }

  async subscribeChannel(args) {
    return this._call('@peartube/subscribe-channel', args)
  }

  async unsubscribeChannel(args) {
    return this._call('@peartube/unsubscribe-channel', args)
  }

  async getSubscriptions(args) {
    return this._call('@peartube/get-subscriptions', args)
  }

  async joinChannel(args) {
    return this._call('@peartube/join-channel', args)
  }

  async getPublicFeed(args) {
    return this._call('@peartube/get-public-feed', args)
  }

  async refreshFeed(args) {
    return this._call('@peartube/refresh-feed', args)
  }

  async submitToFeed(args) {
    return this._call('@peartube/submit-to-feed', args)
  }

  async unpublishFromFeed(args) {
    return this._call('@peartube/unpublish-from-feed', args)
  }

  async isChannelPublished(args) {
    return this._call('@peartube/is-channel-published', args)
  }

  async hideChannel(args) {
    return this._call('@peartube/hide-channel', args)
  }

  async getChannelMeta(args) {
    return this._call('@peartube/get-channel-meta', args)
  }

  async getSwarmStatus(args) {
    return this._call('@peartube/get-swarm-status', args)
  }

  async createDeviceInvite(args) {
    return this._call('@peartube/create-device-invite', args)
  }

  async pairDevice(args) {
    return this._call('@peartube/pair-device', args)
  }

  async listDevices(args) {
    return this._call('@peartube/list-devices', args)
  }

  async retrySyncChannel(args) {
    return this._call('@peartube/retry-sync-channel', args)
  }

  async prefetchVideo(args) {
    return this._call('@peartube/prefetch-video', args)
  }

  async getVideoStats(args) {
    return this._call('@peartube/get-video-stats', args)
  }

  async getSeedingStatus(args) {
    return this._call('@peartube/get-seeding-status', args)
  }

  async setSeedingConfig(args) {
    return this._call('@peartube/set-seeding-config', args)
  }

  async getTranscodeSettings(args) {
    return this._call('@peartube/get-transcode-settings', args)
  }

  async setTranscodeSettings(args) {
    return this._call('@peartube/set-transcode-settings', args)
  }

  async pinChannel(args) {
    return this._call('@peartube/pin-channel', args)
  }

  async unpinChannel(args) {
    return this._call('@peartube/unpin-channel', args)
  }

  async getPinnedChannels(args) {
    return this._call('@peartube/get-pinned-channels', args)
  }

  async getStorageStats(args) {
    return this._call('@peartube/get-storage-stats', args)
  }

  async setStorageLimit(args) {
    return this._call('@peartube/set-storage-limit', args)
  }

  async clearCache(args) {
    return this._call('@peartube/clear-cache', args)
  }

  async getVideoThumbnail(args) {
    return this._call('@peartube/get-video-thumbnail', args)
  }

  async getVideoMetadata(args) {
    return this._call('@peartube/get-video-metadata', args)
  }

  async setVideoThumbnail(args) {
    return this._call('@peartube/set-video-thumbnail', args)
  }

  async setVideoThumbnailFromFile(args) {
    return this._call('@peartube/set-video-thumbnail-from-file', args)
  }

  async getStatus(args) {
    return this._call('@peartube/get-status', args)
  }

  async pickVideoFile(args) {
    return this._call('@peartube/pick-video-file', args)
  }

  async pickImageFile(args) {
    return this._call('@peartube/pick-image-file', args)
  }

  async getBlobServerPort(args) {
    return this._call('@peartube/get-blob-server-port', args)
  }

  async globalSearchVideos(args) {
    return this._call('@peartube/global-search-videos', args)
  }

  async addComment(args) {
    return this._call('@peartube/add-comment', args)
  }

  async listComments(args) {
    return this._call('@peartube/list-comments', args)
  }

  async hideComment(args) {
    return this._call('@peartube/hide-comment', args)
  }

  async removeComment(args) {
    return this._call('@peartube/remove-comment', args)
  }

  async addReaction(args) {
    return this._call('@peartube/add-reaction', args)
  }

  async removeReaction(args) {
    return this._call('@peartube/remove-reaction', args)
  }

  async getReactions(args) {
    return this._call('@peartube/get-reactions', args)
  }

  eventReady(args) {
    return this._callSync('@peartube/event-ready', args)
  }

  eventError(args) {
    return this._callSync('@peartube/event-error', args)
  }

  eventUploadProgress(args) {
    return this._callSync('@peartube/event-upload-progress', args)
  }

  eventDownloadProgress(args) {
    return this._callSync('@peartube/event-download-progress', args)
  }

  eventFeedUpdate(args) {
    return this._callSync('@peartube/event-feed-update', args)
  }

  eventLog(args) {
    return this._callSync('@peartube/event-log', args)
  }

  eventVideoStats(args) {
    return this._callSync('@peartube/event-video-stats', args)
  }

  async castAvailable(args) {
    return this._call('@peartube/cast-available', args)
  }

  async castStartDiscovery(args) {
    return this._call('@peartube/cast-start-discovery', args)
  }

  async castStopDiscovery(args) {
    return this._call('@peartube/cast-stop-discovery', args)
  }

  async castGetDevices(args) {
    return this._call('@peartube/cast-get-devices', args)
  }

  async castAddManualDevice(args) {
    return this._call('@peartube/cast-add-manual-device', args)
  }

  async castConnect(args) {
    return this._call('@peartube/cast-connect', args)
  }

  async castDisconnect(args) {
    return this._call('@peartube/cast-disconnect', args)
  }

  async castPlay(args) {
    return this._call('@peartube/cast-play', args)
  }

  async castPause(args) {
    return this._call('@peartube/cast-pause', args)
  }

  async castResume(args) {
    return this._call('@peartube/cast-resume', args)
  }

  async castStop(args) {
    return this._call('@peartube/cast-stop', args)
  }

  async castSeek(args) {
    return this._call('@peartube/cast-seek', args)
  }

  async castSetVolume(args) {
    return this._call('@peartube/cast-set-volume', args)
  }

  async castGetState(args) {
    return this._call('@peartube/cast-get-state', args)
  }

  async castIsConnected(args) {
    return this._call('@peartube/cast-is-connected', args)
  }

  eventCastDeviceFound(args) {
    return this._callSync('@peartube/event-cast-device-found', args)
  }

  eventCastDeviceLost(args) {
    return this._callSync('@peartube/event-cast-device-lost', args)
  }

  eventCastPlaybackState(args) {
    return this._callSync('@peartube/event-cast-playback-state', args)
  }

  eventCastTimeUpdate(args) {
    return this._callSync('@peartube/event-cast-time-update', args)
  }

  async searchVideos(args) {
    return this._call('@peartube/search-videos', args)
  }

  async logWatchEvent(args) {
    return this._call('@peartube/log-watch-event', args)
  }

  async indexVideoVectors(args) {
    return this._call('@peartube/index-video-vectors', args)
  }

  async getRecommendations(args) {
    return this._call('@peartube/get-recommendations', args)
  }

  async getVideoRecommendations(args) {
    return this._call('@peartube/get-video-recommendations', args)
  }

  async updateVideoMetadata(args) {
    return this._call('@peartube/update-video-metadata', args)
  }

  async webPreparePlayback(args) {
    return this._call('@peartube/web-prepare-playback', args)
  }

  async desktopBootstrap(args) {
    return this._call('@peartube/desktop-bootstrap', args)
  }

  async desktopShutdown(args) {
    return this._call('@peartube/desktop-shutdown', args)
  }

  async desktopRefreshBrowse(args) {
    return this._call('@peartube/desktop-refresh-browse', args)
  }

  async mpvAvailable(args) {
    return this._call('@peartube/mpv-available', args)
  }

  async mpvCreate(args) {
    return this._call('@peartube/mpv-create', args)
  }

  async mpvLoadFile(args) {
    return this._call('@peartube/mpv-load-file', args)
  }

  async mpvPlay(args) {
    return this._call('@peartube/mpv-play', args)
  }

  async mpvPause(args) {
    return this._call('@peartube/mpv-pause', args)
  }

  async mpvSeek(args) {
    return this._call('@peartube/mpv-seek', args)
  }

  async mpvGetState(args) {
    return this._call('@peartube/mpv-get-state', args)
  }

  async mpvRenderFrame(args) {
    return this._call('@peartube/mpv-render-frame', args)
  }

  async mpvDestroy(args) {
    return this._call('@peartube/mpv-destroy', args)
  }

  async ffmpegDecodeAvailable(args) {
    return this._call('@peartube/ffmpeg-decode-available', args)
  }

  async updateChannelAvatar(args) {
    return this._call('@peartube/update-channel-avatar', args)
  }

  async transcodeStart(args) {
    return this._call('@peartube/transcode-start', args)
  }

  async transcodeStop(args) {
    return this._call('@peartube/transcode-stop', args)
  }

  async transcodeStatus(args) {
    return this._call('@peartube/transcode-status', args)
  }

  eventTranscodeProgress(args) {
    return this._callSync('@peartube/event-transcode-progress', args)
  }

  onCreateIdentity(responseFn) {
    this._handlers['@peartube/create-identity'] = responseFn
  }

  onGetIdentity(responseFn) {
    this._handlers['@peartube/get-identity'] = responseFn
  }

  onGetIdentities(responseFn) {
    this._handlers['@peartube/get-identities'] = responseFn
  }

  onSetActiveIdentity(responseFn) {
    this._handlers['@peartube/set-active-identity'] = responseFn
  }

  onRecoverIdentity(responseFn) {
    this._handlers['@peartube/recover-identity'] = responseFn
  }

  onBootstrapDevice(responseFn) {
    this._handlers['@peartube/bootstrap-device'] = responseFn
  }

  onAttestDevice(responseFn) {
    this._handlers['@peartube/attest-device'] = responseFn
  }

  onVerifyAttestation(responseFn) {
    this._handlers['@peartube/verify-attestation'] = responseFn
  }

  onGetChannel(responseFn) {
    this._handlers['@peartube/get-channel'] = responseFn
  }

  onUpdateChannel(responseFn) {
    this._handlers['@peartube/update-channel'] = responseFn
  }

  onListVideos(responseFn) {
    this._handlers['@peartube/list-videos'] = responseFn
  }

  onGetVideoUrl(responseFn) {
    this._handlers['@peartube/get-video-url'] = responseFn
  }

  onPreparePlayback(responseFn) {
    this._handlers['@peartube/prepare-playback'] = responseFn
  }

  onGetVideoData(responseFn) {
    this._handlers['@peartube/get-video-data'] = responseFn
  }

  onUploadVideo(responseFn) {
    this._handlers['@peartube/upload-video'] = responseFn
  }

  onDownloadVideo(responseFn) {
    this._handlers['@peartube/download-video'] = responseFn
  }

  onDeleteVideo(responseFn) {
    this._handlers['@peartube/delete-video'] = responseFn
  }

  onSubscribeChannel(responseFn) {
    this._handlers['@peartube/subscribe-channel'] = responseFn
  }

  onUnsubscribeChannel(responseFn) {
    this._handlers['@peartube/unsubscribe-channel'] = responseFn
  }

  onGetSubscriptions(responseFn) {
    this._handlers['@peartube/get-subscriptions'] = responseFn
  }

  onJoinChannel(responseFn) {
    this._handlers['@peartube/join-channel'] = responseFn
  }

  onGetPublicFeed(responseFn) {
    this._handlers['@peartube/get-public-feed'] = responseFn
  }

  onRefreshFeed(responseFn) {
    this._handlers['@peartube/refresh-feed'] = responseFn
  }

  onSubmitToFeed(responseFn) {
    this._handlers['@peartube/submit-to-feed'] = responseFn
  }

  onUnpublishFromFeed(responseFn) {
    this._handlers['@peartube/unpublish-from-feed'] = responseFn
  }

  onIsChannelPublished(responseFn) {
    this._handlers['@peartube/is-channel-published'] = responseFn
  }

  onHideChannel(responseFn) {
    this._handlers['@peartube/hide-channel'] = responseFn
  }

  onGetChannelMeta(responseFn) {
    this._handlers['@peartube/get-channel-meta'] = responseFn
  }

  onGetSwarmStatus(responseFn) {
    this._handlers['@peartube/get-swarm-status'] = responseFn
  }

  onCreateDeviceInvite(responseFn) {
    this._handlers['@peartube/create-device-invite'] = responseFn
  }

  onPairDevice(responseFn) {
    this._handlers['@peartube/pair-device'] = responseFn
  }

  onListDevices(responseFn) {
    this._handlers['@peartube/list-devices'] = responseFn
  }

  onRetrySyncChannel(responseFn) {
    this._handlers['@peartube/retry-sync-channel'] = responseFn
  }

  onPrefetchVideo(responseFn) {
    this._handlers['@peartube/prefetch-video'] = responseFn
  }

  onGetVideoStats(responseFn) {
    this._handlers['@peartube/get-video-stats'] = responseFn
  }

  onGetSeedingStatus(responseFn) {
    this._handlers['@peartube/get-seeding-status'] = responseFn
  }

  onSetSeedingConfig(responseFn) {
    this._handlers['@peartube/set-seeding-config'] = responseFn
  }

  onGetTranscodeSettings(responseFn) {
    this._handlers['@peartube/get-transcode-settings'] = responseFn
  }

  onSetTranscodeSettings(responseFn) {
    this._handlers['@peartube/set-transcode-settings'] = responseFn
  }

  onPinChannel(responseFn) {
    this._handlers['@peartube/pin-channel'] = responseFn
  }

  onUnpinChannel(responseFn) {
    this._handlers['@peartube/unpin-channel'] = responseFn
  }

  onGetPinnedChannels(responseFn) {
    this._handlers['@peartube/get-pinned-channels'] = responseFn
  }

  onGetStorageStats(responseFn) {
    this._handlers['@peartube/get-storage-stats'] = responseFn
  }

  onSetStorageLimit(responseFn) {
    this._handlers['@peartube/set-storage-limit'] = responseFn
  }

  onClearCache(responseFn) {
    this._handlers['@peartube/clear-cache'] = responseFn
  }

  onGetVideoThumbnail(responseFn) {
    this._handlers['@peartube/get-video-thumbnail'] = responseFn
  }

  onGetVideoMetadata(responseFn) {
    this._handlers['@peartube/get-video-metadata'] = responseFn
  }

  onSetVideoThumbnail(responseFn) {
    this._handlers['@peartube/set-video-thumbnail'] = responseFn
  }

  onSetVideoThumbnailFromFile(responseFn) {
    this._handlers['@peartube/set-video-thumbnail-from-file'] = responseFn
  }

  onGetStatus(responseFn) {
    this._handlers['@peartube/get-status'] = responseFn
  }

  onPickVideoFile(responseFn) {
    this._handlers['@peartube/pick-video-file'] = responseFn
  }

  onPickImageFile(responseFn) {
    this._handlers['@peartube/pick-image-file'] = responseFn
  }

  onGetBlobServerPort(responseFn) {
    this._handlers['@peartube/get-blob-server-port'] = responseFn
  }

  onGlobalSearchVideos(responseFn) {
    this._handlers['@peartube/global-search-videos'] = responseFn
  }

  onAddComment(responseFn) {
    this._handlers['@peartube/add-comment'] = responseFn
  }

  onListComments(responseFn) {
    this._handlers['@peartube/list-comments'] = responseFn
  }

  onHideComment(responseFn) {
    this._handlers['@peartube/hide-comment'] = responseFn
  }

  onRemoveComment(responseFn) {
    this._handlers['@peartube/remove-comment'] = responseFn
  }

  onAddReaction(responseFn) {
    this._handlers['@peartube/add-reaction'] = responseFn
  }

  onRemoveReaction(responseFn) {
    this._handlers['@peartube/remove-reaction'] = responseFn
  }

  onGetReactions(responseFn) {
    this._handlers['@peartube/get-reactions'] = responseFn
  }

  onEventReady(responseFn) {
    this._handlers['@peartube/event-ready'] = responseFn
  }

  onEventError(responseFn) {
    this._handlers['@peartube/event-error'] = responseFn
  }

  onEventUploadProgress(responseFn) {
    this._handlers['@peartube/event-upload-progress'] = responseFn
  }

  onEventDownloadProgress(responseFn) {
    this._handlers['@peartube/event-download-progress'] = responseFn
  }

  onEventFeedUpdate(responseFn) {
    this._handlers['@peartube/event-feed-update'] = responseFn
  }

  onEventLog(responseFn) {
    this._handlers['@peartube/event-log'] = responseFn
  }

  onEventVideoStats(responseFn) {
    this._handlers['@peartube/event-video-stats'] = responseFn
  }

  onCastAvailable(responseFn) {
    this._handlers['@peartube/cast-available'] = responseFn
  }

  onCastStartDiscovery(responseFn) {
    this._handlers['@peartube/cast-start-discovery'] = responseFn
  }

  onCastStopDiscovery(responseFn) {
    this._handlers['@peartube/cast-stop-discovery'] = responseFn
  }

  onCastGetDevices(responseFn) {
    this._handlers['@peartube/cast-get-devices'] = responseFn
  }

  onCastAddManualDevice(responseFn) {
    this._handlers['@peartube/cast-add-manual-device'] = responseFn
  }

  onCastConnect(responseFn) {
    this._handlers['@peartube/cast-connect'] = responseFn
  }

  onCastDisconnect(responseFn) {
    this._handlers['@peartube/cast-disconnect'] = responseFn
  }

  onCastPlay(responseFn) {
    this._handlers['@peartube/cast-play'] = responseFn
  }

  onCastPause(responseFn) {
    this._handlers['@peartube/cast-pause'] = responseFn
  }

  onCastResume(responseFn) {
    this._handlers['@peartube/cast-resume'] = responseFn
  }

  onCastStop(responseFn) {
    this._handlers['@peartube/cast-stop'] = responseFn
  }

  onCastSeek(responseFn) {
    this._handlers['@peartube/cast-seek'] = responseFn
  }

  onCastSetVolume(responseFn) {
    this._handlers['@peartube/cast-set-volume'] = responseFn
  }

  onCastGetState(responseFn) {
    this._handlers['@peartube/cast-get-state'] = responseFn
  }

  onCastIsConnected(responseFn) {
    this._handlers['@peartube/cast-is-connected'] = responseFn
  }

  onEventCastDeviceFound(responseFn) {
    this._handlers['@peartube/event-cast-device-found'] = responseFn
  }

  onEventCastDeviceLost(responseFn) {
    this._handlers['@peartube/event-cast-device-lost'] = responseFn
  }

  onEventCastPlaybackState(responseFn) {
    this._handlers['@peartube/event-cast-playback-state'] = responseFn
  }

  onEventCastTimeUpdate(responseFn) {
    this._handlers['@peartube/event-cast-time-update'] = responseFn
  }

  onSearchVideos(responseFn) {
    this._handlers['@peartube/search-videos'] = responseFn
  }

  onLogWatchEvent(responseFn) {
    this._handlers['@peartube/log-watch-event'] = responseFn
  }

  onIndexVideoVectors(responseFn) {
    this._handlers['@peartube/index-video-vectors'] = responseFn
  }

  onGetRecommendations(responseFn) {
    this._handlers['@peartube/get-recommendations'] = responseFn
  }

  onGetVideoRecommendations(responseFn) {
    this._handlers['@peartube/get-video-recommendations'] = responseFn
  }

  onUpdateVideoMetadata(responseFn) {
    this._handlers['@peartube/update-video-metadata'] = responseFn
  }

  onWebPreparePlayback(responseFn) {
    this._handlers['@peartube/web-prepare-playback'] = responseFn
  }

  onDesktopBootstrap(responseFn) {
    this._handlers['@peartube/desktop-bootstrap'] = responseFn
  }

  onDesktopShutdown(responseFn) {
    this._handlers['@peartube/desktop-shutdown'] = responseFn
  }

  onDesktopRefreshBrowse(responseFn) {
    this._handlers['@peartube/desktop-refresh-browse'] = responseFn
  }

  onMpvAvailable(responseFn) {
    this._handlers['@peartube/mpv-available'] = responseFn
  }

  onMpvCreate(responseFn) {
    this._handlers['@peartube/mpv-create'] = responseFn
  }

  onMpvLoadFile(responseFn) {
    this._handlers['@peartube/mpv-load-file'] = responseFn
  }

  onMpvPlay(responseFn) {
    this._handlers['@peartube/mpv-play'] = responseFn
  }

  onMpvPause(responseFn) {
    this._handlers['@peartube/mpv-pause'] = responseFn
  }

  onMpvSeek(responseFn) {
    this._handlers['@peartube/mpv-seek'] = responseFn
  }

  onMpvGetState(responseFn) {
    this._handlers['@peartube/mpv-get-state'] = responseFn
  }

  onMpvRenderFrame(responseFn) {
    this._handlers['@peartube/mpv-render-frame'] = responseFn
  }

  onMpvDestroy(responseFn) {
    this._handlers['@peartube/mpv-destroy'] = responseFn
  }

  onFfmpegDecodeAvailable(responseFn) {
    this._handlers['@peartube/ffmpeg-decode-available'] = responseFn
  }

  onUpdateChannelAvatar(responseFn) {
    this._handlers['@peartube/update-channel-avatar'] = responseFn
  }

  onTranscodeStart(responseFn) {
    this._handlers['@peartube/transcode-start'] = responseFn
  }

  onTranscodeStop(responseFn) {
    this._handlers['@peartube/transcode-stop'] = responseFn
  }

  onTranscodeStatus(responseFn) {
    this._handlers['@peartube/transcode-status'] = responseFn
  }

  onEventTranscodeProgress(responseFn) {
    this._handlers['@peartube/event-transcode-progress'] = responseFn
  }

  _requestIsStream(command) {
    return [
    ].includes(command)
  }

  _responseIsStream(command) {
    return [
    ].includes(command)
  }

  // prettier-ignore-start
  _requestIsSend(command) {
    return [
      // prettier-ignore
      '@peartube/event-ready',
      '@peartube/event-error',
      '@peartube/event-upload-progress',
      '@peartube/event-download-progress',
      '@peartube/event-feed-update',
      '@peartube/event-log',
      '@peartube/event-video-stats',
      '@peartube/event-cast-device-found',
      '@peartube/event-cast-device-lost',
      '@peartube/event-cast-playback-state',
      '@peartube/event-cast-time-update',
      '@peartube/event-transcode-progress'
    ].includes(command)
  }
}

module.exports = HRPC
