/* eslint-disable @typescript-eslint/no-require-imports */
// This file is autogenerated by the hrpc compiler
/* eslint-disable camelcase */
/* eslint-disable space-before-function-paren */

const { c, RPC, RPCStream, RPCRequestStream } = require('hrpc/runtime')
const { getEncoding } = require('./messages.js')

const methods = new Map([
  ['@peartube/create-identity', 0],
  [0, '@peartube/create-identity'],
  ['@peartube/get-identity', 1],
  [1, '@peartube/get-identity'],
  ['@peartube/get-identities', 2],
  [2, '@peartube/get-identities'],
  ['@peartube/set-active-identity', 3],
  [3, '@peartube/set-active-identity'],
  ['@peartube/recover-identity', 4],
  [4, '@peartube/recover-identity'],
  ['@peartube/bootstrap-device', 5],
  [5, '@peartube/bootstrap-device'],
  ['@peartube/attest-device', 6],
  [6, '@peartube/attest-device'],
  ['@peartube/provision-publisher-catalog', 7],
  [7, '@peartube/provision-publisher-catalog'],
  ['@peartube/verify-attestation', 8],
  [8, '@peartube/verify-attestation'],
  ['@peartube/prepare-publisher-root-operation', 9],
  [9, '@peartube/prepare-publisher-root-operation'],
  ['@peartube/submit-publisher-root-operation', 10],
  [10, '@peartube/submit-publisher-root-operation'],
  ['@peartube/get-channel', 11],
  [11, '@peartube/get-channel'],
  ['@peartube/update-channel', 12],
  [12, '@peartube/update-channel'],
  ['@peartube/get-content-catalog', 13],
  [13, '@peartube/get-content-catalog'],
  ['@peartube/get-content-items', 14],
  [14, '@peartube/get-content-items'],
  ['@peartube/list-videos', 15],
  [15, '@peartube/list-videos'],
  ['@peartube/get-video-url', 16],
  [16, '@peartube/get-video-url'],
  ['@peartube/prepare-playback', 17],
  [17, '@peartube/prepare-playback'],
  ['@peartube/web-prepare-playback', 18],
  [18, '@peartube/web-prepare-playback'],
  ['@peartube/get-video-data', 19],
  [19, '@peartube/get-video-data'],
  ['@peartube/upload-video', 20],
  [20, '@peartube/upload-video'],
  ['@peartube/download-video', 21],
  [21, '@peartube/download-video'],
  ['@peartube/delete-video', 22],
  [22, '@peartube/delete-video'],
  ['@peartube/start-livestream', 23],
  [23, '@peartube/start-livestream'],
  ['@peartube/stop-livestream', 24],
  [24, '@peartube/stop-livestream'],
  ['@peartube/get-livestream-status', 25],
  [25, '@peartube/get-livestream-status'],
  ['@peartube/prepare-live-playback', 26],
  [26, '@peartube/prepare-live-playback'],
  ['@peartube/subscribe-channel', 27],
  [27, '@peartube/subscribe-channel'],
  ['@peartube/unsubscribe-channel', 28],
  [28, '@peartube/unsubscribe-channel'],
  ['@peartube/get-subscriptions', 29],
  [29, '@peartube/get-subscriptions'],
  ['@peartube/get-playlists', 30],
  [30, '@peartube/get-playlists'],
  ['@peartube/get-playlist-items', 31],
  [31, '@peartube/get-playlist-items'],
  ['@peartube/create-playlist', 32],
  [32, '@peartube/create-playlist'],
  ['@peartube/update-playlist', 33],
  [33, '@peartube/update-playlist'],
  ['@peartube/delete-playlist', 34],
  [34, '@peartube/delete-playlist'],
  ['@peartube/add-to-playlist', 35],
  [35, '@peartube/add-to-playlist'],
  ['@peartube/remove-from-playlist', 36],
  [36, '@peartube/remove-from-playlist'],
  ['@peartube/log-watch-history', 37],
  [37, '@peartube/log-watch-history'],
  ['@peartube/get-watch-history', 38],
  [38, '@peartube/get-watch-history'],
  ['@peartube/get-resume-position', 39],
  [39, '@peartube/get-resume-position'],
  ['@peartube/list-resume-positions', 40],
  [40, '@peartube/list-resume-positions'],
  ['@peartube/set-personal-setting', 41],
  [41, '@peartube/set-personal-setting'],
  ['@peartube/get-personal-settings', 42],
  [42, '@peartube/get-personal-settings'],
  ['@peartube/provision-personal-encryption', 43],
  [43, '@peartube/provision-personal-encryption'],
  ['@peartube/create-personal-device-invite', 44],
  [44, '@peartube/create-personal-device-invite'],
  ['@peartube/redeem-personal-device-invite', 45],
  [45, '@peartube/redeem-personal-device-invite'],
  ['@peartube/list-personal-devices', 46],
  [46, '@peartube/list-personal-devices'],
  ['@peartube/revoke-personal-device', 47],
  [47, '@peartube/revoke-personal-device'],
  ['@peartube/join-channel', 48],
  [48, '@peartube/join-channel'],
  ['@peartube/hide-channel', 49],
  [49, '@peartube/hide-channel'],
  ['@peartube/get-channel-meta', 50],
  [50, '@peartube/get-channel-meta'],
  ['@peartube/get-swarm-status', 51],
  [51, '@peartube/get-swarm-status'],
  ['@peartube/create-device-invite', 52],
  [52, '@peartube/create-device-invite'],
  ['@peartube/pair-device', 53],
  [53, '@peartube/pair-device'],
  ['@peartube/list-devices', 54],
  [54, '@peartube/list-devices'],
  ['@peartube/retry-sync-channel', 55],
  [55, '@peartube/retry-sync-channel'],
  ['@peartube/prefetch-video', 56],
  [56, '@peartube/prefetch-video'],
  ['@peartube/get-video-stats', 57],
  [57, '@peartube/get-video-stats'],
  ['@peartube/get-seeding-status', 58],
  [58, '@peartube/get-seeding-status'],
  ['@peartube/set-seeding-config', 59],
  [59, '@peartube/set-seeding-config'],
  ['@peartube/get-transcode-settings', 60],
  [60, '@peartube/get-transcode-settings'],
  ['@peartube/set-transcode-settings', 61],
  [61, '@peartube/set-transcode-settings'],
  ['@peartube/pin-channel', 62],
  [62, '@peartube/pin-channel'],
  ['@peartube/unpin-channel', 63],
  [63, '@peartube/unpin-channel'],
  ['@peartube/get-pinned-channels', 64],
  [64, '@peartube/get-pinned-channels'],
  ['@peartube/get-storage-stats', 65],
  [65, '@peartube/get-storage-stats'],
  ['@peartube/set-storage-limit', 66],
  [66, '@peartube/set-storage-limit'],
  ['@peartube/get-migration-status', 67],
  [67, '@peartube/get-migration-status'],
  ['@peartube/retry-migration', 68],
  [68, '@peartube/retry-migration'],
  ['@peartube/export-migration-report', 69],
  [69, '@peartube/export-migration-report'],
  ['@peartube/get-publisher-device-status', 70],
  [70, '@peartube/get-publisher-device-status'],
  ['@peartube/export-portable-state', 71],
  [71, '@peartube/export-portable-state'],
  ['@peartube/restore-portable-state', 72],
  [72, '@peartube/restore-portable-state'],
  ['@peartube/preview-storage-limit', 73],
  [73, '@peartube/preview-storage-limit'],
  ['@peartube/get-archive-operator-status', 74],
  [74, '@peartube/get-archive-operator-status'],
  ['@peartube/get-archive-participation', 75],
  [75, '@peartube/get-archive-participation'],
  ['@peartube/set-archive-participation', 76],
  [76, '@peartube/set-archive-participation'],
  ['@peartube/request-archive-publication', 77],
  [77, '@peartube/request-archive-publication'],
  ['@peartube/get-network-policy', 78],
  [78, '@peartube/get-network-policy'],
  ['@peartube/set-network-policy', 79],
  [79, '@peartube/set-network-policy'],
  ['@peartube/clear-cache', 80],
  [80, '@peartube/clear-cache'],
  ['@peartube/assess-source-offload', 81],
  [81, '@peartube/assess-source-offload'],
  ['@peartube/confirm-source-offload', 82],
  [82, '@peartube/confirm-source-offload'],
  ['@peartube/get-video-thumbnail', 83],
  [83, '@peartube/get-video-thumbnail'],
  ['@peartube/get-video-metadata', 84],
  [84, '@peartube/get-video-metadata'],
  ['@peartube/set-video-thumbnail', 85],
  [85, '@peartube/set-video-thumbnail'],
  ['@peartube/set-video-thumbnail-from-file', 86],
  [86, '@peartube/set-video-thumbnail-from-file'],
  ['@peartube/get-status', 87],
  [87, '@peartube/get-status'],
  ['@peartube/pick-video-file', 88],
  [88, '@peartube/pick-video-file'],
  ['@peartube/pick-image-file', 89],
  [89, '@peartube/pick-image-file'],
  ['@peartube/get-blob-server-port', 90],
  [90, '@peartube/get-blob-server-port'],
  ['@peartube/global-search-videos', 91],
  [91, '@peartube/global-search-videos'],
  ['@peartube/add-comment', 92],
  [92, '@peartube/add-comment'],
  ['@peartube/list-comments', 93],
  [93, '@peartube/list-comments'],
  ['@peartube/hide-comment', 94],
  [94, '@peartube/hide-comment'],
  ['@peartube/remove-comment', 95],
  [95, '@peartube/remove-comment'],
  ['@peartube/add-reaction', 96],
  [96, '@peartube/add-reaction'],
  ['@peartube/remove-reaction', 97],
  [97, '@peartube/remove-reaction'],
  ['@peartube/get-reactions', 98],
  [98, '@peartube/get-reactions'],
  ['@peartube/event-ready', 99],
  [99, '@peartube/event-ready'],
  ['@peartube/event-error', 100],
  [100, '@peartube/event-error'],
  ['@peartube/event-upload-progress', 101],
  [101, '@peartube/event-upload-progress'],
  ['@peartube/event-download-progress', 102],
  [102, '@peartube/event-download-progress'],
  ['@peartube/event-media-graph-update', 103],
  [103, '@peartube/event-media-graph-update'],
  ['@peartube/event-log', 104],
  [104, '@peartube/event-log'],
  ['@peartube/event-video-stats', 105],
  [105, '@peartube/event-video-stats'],
  ['@peartube/cast-available', 106],
  [106, '@peartube/cast-available'],
  ['@peartube/cast-start-discovery', 107],
  [107, '@peartube/cast-start-discovery'],
  ['@peartube/cast-stop-discovery', 108],
  [108, '@peartube/cast-stop-discovery'],
  ['@peartube/cast-get-devices', 109],
  [109, '@peartube/cast-get-devices'],
  ['@peartube/cast-add-manual-device', 110],
  [110, '@peartube/cast-add-manual-device'],
  ['@peartube/cast-connect', 111],
  [111, '@peartube/cast-connect'],
  ['@peartube/cast-disconnect', 112],
  [112, '@peartube/cast-disconnect'],
  ['@peartube/cast-play', 113],
  [113, '@peartube/cast-play'],
  ['@peartube/cast-pause', 114],
  [114, '@peartube/cast-pause'],
  ['@peartube/cast-resume', 115],
  [115, '@peartube/cast-resume'],
  ['@peartube/cast-stop', 116],
  [116, '@peartube/cast-stop'],
  ['@peartube/cast-seek', 117],
  [117, '@peartube/cast-seek'],
  ['@peartube/cast-set-volume', 118],
  [118, '@peartube/cast-set-volume'],
  ['@peartube/cast-get-state', 119],
  [119, '@peartube/cast-get-state'],
  ['@peartube/cast-is-connected', 120],
  [120, '@peartube/cast-is-connected'],
  ['@peartube/event-cast-device-found', 121],
  [121, '@peartube/event-cast-device-found'],
  ['@peartube/event-cast-device-lost', 122],
  [122, '@peartube/event-cast-device-lost'],
  ['@peartube/event-cast-playback-state', 123],
  [123, '@peartube/event-cast-playback-state'],
  ['@peartube/event-cast-time-update', 124],
  [124, '@peartube/event-cast-time-update'],
  ['@peartube/search-videos', 125],
  [125, '@peartube/search-videos'],
  ['@peartube/index-video-vectors', 126],
  [126, '@peartube/index-video-vectors'],
  ['@peartube/update-video-metadata', 127],
  [127, '@peartube/update-video-metadata'],
  ['@peartube/get-media-catalog', 128],
  [128, '@peartube/get-media-catalog'],
  ['@peartube/get-media-entity', 129],
  [129, '@peartube/get-media-entity'],
  ['@peartube/get-media-collection', 130],
  [130, '@peartube/get-media-collection'],
  ['@peartube/get-media-collection-items', 131],
  [131, '@peartube/get-media-collection-items'],
  ['@peartube/get-media-agent', 132],
  [132, '@peartube/get-media-agent'],
  ['@peartube/get-agent-contributions', 133],
  [133, '@peartube/get-agent-contributions'],
  ['@peartube/get-publication-sources', 134],
  [134, '@peartube/get-publication-sources'],
  ['@peartube/get-entity-artwork', 135],
  [135, '@peartube/get-entity-artwork'],
  ['@peartube/get-claim-provenance', 136],
  [136, '@peartube/get-claim-provenance'],
  ['@peartube/set-source-preference', 137],
  [137, '@peartube/set-source-preference'],
  ['@peartube/prepare-media-playback', 138],
  [138, '@peartube/prepare-media-playback'],
  ['@peartube/desktop-bootstrap', 139],
  [139, '@peartube/desktop-bootstrap'],
  ['@peartube/desktop-shutdown', 140],
  [140, '@peartube/desktop-shutdown'],
  ['@peartube/desktop-refresh-browse', 141],
  [141, '@peartube/desktop-refresh-browse'],
  ['@peartube/ffmpeg-decode-available', 142],
  [142, '@peartube/ffmpeg-decode-available'],
  ['@peartube/update-channel-avatar', 143],
  [143, '@peartube/update-channel-avatar'],
  ['@peartube/transcode-start', 144],
  [144, '@peartube/transcode-start'],
  ['@peartube/transcode-stop', 145],
  [145, '@peartube/transcode-stop'],
  ['@peartube/transcode-status', 146],
  [146, '@peartube/transcode-status'],
  ['@peartube/event-transcode-progress', 147],
  [147, '@peartube/event-transcode-progress']
])

class HRPC {
  constructor(stream) {
    this._stream = stream
    this._handlers = []
    this._requestEncodings = new Map([
      ['@peartube/create-identity', getEncoding('@peartube/create-identity-request')],
      ['@peartube/get-identity', getEncoding('@peartube/get-identity-request')],
      ['@peartube/get-identities', getEncoding('@peartube/get-identities-request')],
      ['@peartube/set-active-identity', getEncoding('@peartube/set-active-identity-request')],
      ['@peartube/recover-identity', getEncoding('@peartube/recover-identity-request')],
      ['@peartube/bootstrap-device', getEncoding('@peartube/bootstrap-device-request')],
      ['@peartube/attest-device', getEncoding('@peartube/attest-device-request')],
      ['@peartube/provision-publisher-catalog', getEncoding('@peartube/provision-publisher-catalog-request')],
      ['@peartube/verify-attestation', getEncoding('@peartube/verify-attestation-request')],
      ['@peartube/prepare-publisher-root-operation', getEncoding('@peartube/prepare-publisher-root-operation-request')],
      ['@peartube/submit-publisher-root-operation', getEncoding('@peartube/submit-publisher-root-operation-request')],
      ['@peartube/get-channel', getEncoding('@peartube/get-channel-request')],
      ['@peartube/update-channel', getEncoding('@peartube/update-channel-request')],
      ['@peartube/get-content-catalog', getEncoding('@peartube/get-content-catalog-request')],
      ['@peartube/get-content-items', getEncoding('@peartube/get-content-items-request')],
      ['@peartube/list-videos', getEncoding('@peartube/list-videos-request')],
      ['@peartube/get-video-url', getEncoding('@peartube/get-video-url-request')],
      ['@peartube/prepare-playback', getEncoding('@peartube/prepare-playback-request')],
      ['@peartube/web-prepare-playback', getEncoding('@peartube/prepare-playback-request')],
      ['@peartube/get-video-data', getEncoding('@peartube/get-video-data-request')],
      ['@peartube/upload-video', getEncoding('@peartube/upload-video-request')],
      ['@peartube/download-video', getEncoding('@peartube/download-video-request')],
      ['@peartube/delete-video', getEncoding('@peartube/delete-video-request')],
      ['@peartube/start-livestream', getEncoding('@peartube/start-livestream-request')],
      ['@peartube/stop-livestream', getEncoding('@peartube/stop-livestream-request')],
      ['@peartube/get-livestream-status', getEncoding('@peartube/get-livestream-status-request')],
      ['@peartube/prepare-live-playback', getEncoding('@peartube/prepare-live-playback-request')],
      ['@peartube/subscribe-channel', getEncoding('@peartube/subscribe-channel-request')],
      ['@peartube/unsubscribe-channel', getEncoding('@peartube/unsubscribe-channel-request')],
      ['@peartube/get-subscriptions', getEncoding('@peartube/get-subscriptions-request')],
      ['@peartube/get-playlists', getEncoding('@peartube/get-playlists-request')],
      ['@peartube/get-playlist-items', getEncoding('@peartube/get-playlist-items-request')],
      ['@peartube/create-playlist', getEncoding('@peartube/create-playlist-request')],
      ['@peartube/update-playlist', getEncoding('@peartube/update-playlist-request')],
      ['@peartube/delete-playlist', getEncoding('@peartube/delete-playlist-request')],
      ['@peartube/add-to-playlist', getEncoding('@peartube/add-to-playlist-request')],
      ['@peartube/remove-from-playlist', getEncoding('@peartube/remove-from-playlist-request')],
      ['@peartube/log-watch-history', getEncoding('@peartube/log-watch-history-request')],
      ['@peartube/get-watch-history', getEncoding('@peartube/get-watch-history-request')],
      ['@peartube/get-resume-position', getEncoding('@peartube/get-resume-position-request')],
      ['@peartube/list-resume-positions', getEncoding('@peartube/list-resume-positions-request')],
      ['@peartube/set-personal-setting', getEncoding('@peartube/set-personal-setting-request')],
      ['@peartube/get-personal-settings', getEncoding('@peartube/get-personal-settings-request')],
      ['@peartube/provision-personal-encryption', getEncoding('@peartube/provision-personal-encryption-request')],
      ['@peartube/create-personal-device-invite', getEncoding('@peartube/create-personal-device-invite-request')],
      ['@peartube/redeem-personal-device-invite', getEncoding('@peartube/redeem-personal-device-invite-request')],
      ['@peartube/list-personal-devices', getEncoding('@peartube/list-personal-devices-request')],
      ['@peartube/revoke-personal-device', getEncoding('@peartube/revoke-personal-device-request')],
      ['@peartube/join-channel', getEncoding('@peartube/join-channel-request')],
      ['@peartube/hide-channel', getEncoding('@peartube/hide-channel-request')],
      ['@peartube/get-channel-meta', getEncoding('@peartube/get-channel-meta-request')],
      ['@peartube/get-swarm-status', getEncoding('@peartube/get-swarm-status-request')],
      ['@peartube/create-device-invite', getEncoding('@peartube/create-device-invite-request')],
      ['@peartube/pair-device', getEncoding('@peartube/pair-device-request')],
      ['@peartube/list-devices', getEncoding('@peartube/list-devices-request')],
      ['@peartube/retry-sync-channel', getEncoding('@peartube/retry-sync-channel-request')],
      ['@peartube/prefetch-video', getEncoding('@peartube/prefetch-video-request')],
      ['@peartube/get-video-stats', getEncoding('@peartube/get-video-stats-request')],
      ['@peartube/get-seeding-status', getEncoding('@peartube/get-seeding-status-request')],
      ['@peartube/set-seeding-config', getEncoding('@peartube/set-seeding-config-request')],
      ['@peartube/get-transcode-settings', getEncoding('@peartube/get-transcode-settings-request')],
      ['@peartube/set-transcode-settings', getEncoding('@peartube/set-transcode-settings-request')],
      ['@peartube/pin-channel', getEncoding('@peartube/pin-channel-request')],
      ['@peartube/unpin-channel', getEncoding('@peartube/unpin-channel-request')],
      ['@peartube/get-pinned-channels', getEncoding('@peartube/get-pinned-channels-request')],
      ['@peartube/get-storage-stats', getEncoding('@peartube/get-storage-stats-request')],
      ['@peartube/set-storage-limit', getEncoding('@peartube/set-storage-limit-request')],
      ['@peartube/get-migration-status', getEncoding('@peartube/get-migration-status-request')],
      ['@peartube/retry-migration', getEncoding('@peartube/retry-migration-request')],
      ['@peartube/export-migration-report', getEncoding('@peartube/export-migration-report-request')],
      ['@peartube/get-publisher-device-status', getEncoding('@peartube/get-publisher-device-status-request')],
      ['@peartube/export-portable-state', getEncoding('@peartube/export-portable-state-request')],
      ['@peartube/restore-portable-state', getEncoding('@peartube/restore-portable-state-request')],
      ['@peartube/preview-storage-limit', getEncoding('@peartube/preview-storage-limit-request')],
      ['@peartube/get-archive-operator-status', getEncoding('@peartube/get-archive-operator-status-request')],
      ['@peartube/get-archive-participation', getEncoding('@peartube/get-archive-participation-request')],
      ['@peartube/set-archive-participation', getEncoding('@peartube/set-archive-participation-request')],
      ['@peartube/request-archive-publication', getEncoding('@peartube/request-archive-publication-request')],
      ['@peartube/get-network-policy', getEncoding('@peartube/get-network-policy-request')],
      ['@peartube/set-network-policy', getEncoding('@peartube/set-network-policy-request')],
      ['@peartube/clear-cache', getEncoding('@peartube/clear-cache-request')],
      ['@peartube/assess-source-offload', getEncoding('@peartube/assess-source-offload-request')],
      ['@peartube/confirm-source-offload', getEncoding('@peartube/confirm-source-offload-request')],
      ['@peartube/get-video-thumbnail', getEncoding('@peartube/get-video-thumbnail-request')],
      ['@peartube/get-video-metadata', getEncoding('@peartube/get-video-metadata-request')],
      ['@peartube/set-video-thumbnail', getEncoding('@peartube/set-video-thumbnail-request')],
      ['@peartube/set-video-thumbnail-from-file', getEncoding('@peartube/set-video-thumbnail-from-file-request')],
      ['@peartube/get-status', getEncoding('@peartube/get-status-request')],
      ['@peartube/pick-video-file', getEncoding('@peartube/pick-video-file-request')],
      ['@peartube/pick-image-file', getEncoding('@peartube/pick-image-file-request')],
      ['@peartube/get-blob-server-port', getEncoding('@peartube/get-blob-server-port-request')],
      ['@peartube/global-search-videos', getEncoding('@peartube/global-search-videos-request')],
      ['@peartube/add-comment', getEncoding('@peartube/add-comment-request')],
      ['@peartube/list-comments', getEncoding('@peartube/list-comments-request')],
      ['@peartube/hide-comment', getEncoding('@peartube/hide-comment-request')],
      ['@peartube/remove-comment', getEncoding('@peartube/remove-comment-request')],
      ['@peartube/add-reaction', getEncoding('@peartube/add-reaction-request')],
      ['@peartube/remove-reaction', getEncoding('@peartube/remove-reaction-request')],
      ['@peartube/get-reactions', getEncoding('@peartube/get-reactions-request')],
      ['@peartube/event-ready', getEncoding('@peartube/event-ready')],
      ['@peartube/event-error', getEncoding('@peartube/event-error')],
      ['@peartube/event-upload-progress', getEncoding('@peartube/event-upload-progress')],
      ['@peartube/event-download-progress', getEncoding('@peartube/event-download-progress')],
      ['@peartube/event-media-graph-update', getEncoding('@peartube/event-media-graph-update')],
      ['@peartube/event-log', getEncoding('@peartube/event-log')],
      ['@peartube/event-video-stats', getEncoding('@peartube/event-video-stats')],
      ['@peartube/cast-available', getEncoding('@peartube/cast-available-request')],
      ['@peartube/cast-start-discovery', getEncoding('@peartube/cast-start-discovery-request')],
      ['@peartube/cast-stop-discovery', getEncoding('@peartube/cast-stop-discovery-request')],
      ['@peartube/cast-get-devices', getEncoding('@peartube/cast-get-devices-request')],
      ['@peartube/cast-add-manual-device', getEncoding('@peartube/cast-add-manual-device-request')],
      ['@peartube/cast-connect', getEncoding('@peartube/cast-connect-request')],
      ['@peartube/cast-disconnect', getEncoding('@peartube/cast-disconnect-request')],
      ['@peartube/cast-play', getEncoding('@peartube/cast-play-request')],
      ['@peartube/cast-pause', getEncoding('@peartube/cast-pause-request')],
      ['@peartube/cast-resume', getEncoding('@peartube/cast-resume-request')],
      ['@peartube/cast-stop', getEncoding('@peartube/cast-stop-request')],
      ['@peartube/cast-seek', getEncoding('@peartube/cast-seek-request')],
      ['@peartube/cast-set-volume', getEncoding('@peartube/cast-set-volume-request')],
      ['@peartube/cast-get-state', getEncoding('@peartube/cast-get-state-request')],
      ['@peartube/cast-is-connected', getEncoding('@peartube/cast-is-connected-request')],
      ['@peartube/event-cast-device-found', getEncoding('@peartube/event-cast-device-found')],
      ['@peartube/event-cast-device-lost', getEncoding('@peartube/event-cast-device-lost')],
      ['@peartube/event-cast-playback-state', getEncoding('@peartube/event-cast-playback-state')],
      ['@peartube/event-cast-time-update', getEncoding('@peartube/event-cast-time-update')],
      ['@peartube/search-videos', getEncoding('@peartube/search-videos-request')],
      ['@peartube/index-video-vectors', getEncoding('@peartube/index-video-vectors-request')],
      ['@peartube/update-video-metadata', getEncoding('@peartube/update-video-metadata-request')],
      ['@peartube/get-media-catalog', getEncoding('@peartube/media-page-request')],
      ['@peartube/get-media-entity', getEncoding('@peartube/get-media-entity-request')],
      ['@peartube/get-media-collection', getEncoding('@peartube/get-media-collection-request')],
      ['@peartube/get-media-collection-items', getEncoding('@peartube/get-media-collection-items-request')],
      ['@peartube/get-media-agent', getEncoding('@peartube/get-media-agent-request')],
      ['@peartube/get-agent-contributions', getEncoding('@peartube/get-agent-contributions-request')],
      ['@peartube/get-publication-sources', getEncoding('@peartube/get-publication-sources-request')],
      ['@peartube/get-entity-artwork', getEncoding('@peartube/get-entity-artwork-request')],
      ['@peartube/get-claim-provenance', getEncoding('@peartube/get-claim-provenance-request')],
      ['@peartube/set-source-preference', getEncoding('@peartube/set-source-preference-request')],
      ['@peartube/prepare-media-playback', getEncoding('@peartube/prepare-media-playback-request')],
      ['@peartube/desktop-bootstrap', getEncoding('@peartube/desktop-bootstrap-request')],
      ['@peartube/desktop-shutdown', getEncoding('@peartube/desktop-shutdown-request')],
      ['@peartube/desktop-refresh-browse', getEncoding('@peartube/desktop-refresh-browse-request')],
      ['@peartube/ffmpeg-decode-available', getEncoding('@peartube/ffmpeg-decode-available-request')],
      ['@peartube/update-channel-avatar', getEncoding('@peartube/update-channel-avatar-request')],
      ['@peartube/transcode-start', getEncoding('@peartube/transcode-start-request')],
      ['@peartube/transcode-stop', getEncoding('@peartube/transcode-stop-request')],
      ['@peartube/transcode-status', getEncoding('@peartube/transcode-status-request')],
      ['@peartube/event-transcode-progress', getEncoding('@peartube/event-transcode-progress')]
    ])
    this._responseEncodings = new Map([
      ['@peartube/create-identity', getEncoding('@peartube/create-identity-response')],
      ['@peartube/get-identity', getEncoding('@peartube/get-identity-response')],
      ['@peartube/get-identities', getEncoding('@peartube/get-identities-response')],
      ['@peartube/set-active-identity', getEncoding('@peartube/set-active-identity-response')],
      ['@peartube/recover-identity', getEncoding('@peartube/recover-identity-response')],
      ['@peartube/bootstrap-device', getEncoding('@peartube/bootstrap-device-response')],
      ['@peartube/attest-device', getEncoding('@peartube/attest-device-response')],
      ['@peartube/provision-publisher-catalog', getEncoding('@peartube/provision-publisher-catalog-response')],
      ['@peartube/verify-attestation', getEncoding('@peartube/verify-attestation-response')],
      ['@peartube/prepare-publisher-root-operation', getEncoding('@peartube/prepare-publisher-root-operation-response')],
      ['@peartube/submit-publisher-root-operation', getEncoding('@peartube/submit-publisher-root-operation-response')],
      ['@peartube/get-channel', getEncoding('@peartube/get-channel-response')],
      ['@peartube/update-channel', getEncoding('@peartube/update-channel-response')],
      ['@peartube/get-content-catalog', getEncoding('@peartube/get-content-catalog-response')],
      ['@peartube/get-content-items', getEncoding('@peartube/get-content-items-response')],
      ['@peartube/list-videos', getEncoding('@peartube/list-videos-response')],
      ['@peartube/get-video-url', getEncoding('@peartube/get-video-url-response')],
      ['@peartube/prepare-playback', getEncoding('@peartube/prepare-playback-response')],
      ['@peartube/web-prepare-playback', getEncoding('@peartube/web-prepare-playback-response')],
      ['@peartube/get-video-data', getEncoding('@peartube/get-video-data-response')],
      ['@peartube/upload-video', getEncoding('@peartube/upload-video-response')],
      ['@peartube/download-video', getEncoding('@peartube/download-video-response')],
      ['@peartube/delete-video', getEncoding('@peartube/delete-video-response')],
      ['@peartube/start-livestream', getEncoding('@peartube/start-livestream-response')],
      ['@peartube/stop-livestream', getEncoding('@peartube/stop-livestream-response')],
      ['@peartube/get-livestream-status', getEncoding('@peartube/get-livestream-status-response')],
      ['@peartube/prepare-live-playback', getEncoding('@peartube/prepare-live-playback-response')],
      ['@peartube/subscribe-channel', getEncoding('@peartube/subscribe-channel-response')],
      ['@peartube/unsubscribe-channel', getEncoding('@peartube/unsubscribe-channel-response')],
      ['@peartube/get-subscriptions', getEncoding('@peartube/get-subscriptions-response')],
      ['@peartube/get-playlists', getEncoding('@peartube/get-playlists-response')],
      ['@peartube/get-playlist-items', getEncoding('@peartube/get-playlist-items-response')],
      ['@peartube/create-playlist', getEncoding('@peartube/create-playlist-response')],
      ['@peartube/update-playlist', getEncoding('@peartube/update-playlist-response')],
      ['@peartube/delete-playlist', getEncoding('@peartube/delete-playlist-response')],
      ['@peartube/add-to-playlist', getEncoding('@peartube/add-to-playlist-response')],
      ['@peartube/remove-from-playlist', getEncoding('@peartube/remove-from-playlist-response')],
      ['@peartube/log-watch-history', getEncoding('@peartube/log-watch-history-response')],
      ['@peartube/get-watch-history', getEncoding('@peartube/get-watch-history-response')],
      ['@peartube/get-resume-position', getEncoding('@peartube/get-resume-position-response')],
      ['@peartube/list-resume-positions', getEncoding('@peartube/list-resume-positions-response')],
      ['@peartube/set-personal-setting', getEncoding('@peartube/set-personal-setting-response')],
      ['@peartube/get-personal-settings', getEncoding('@peartube/get-personal-settings-response')],
      ['@peartube/provision-personal-encryption', getEncoding('@peartube/provision-personal-encryption-response')],
      ['@peartube/create-personal-device-invite', getEncoding('@peartube/create-personal-device-invite-response')],
      ['@peartube/redeem-personal-device-invite', getEncoding('@peartube/redeem-personal-device-invite-response')],
      ['@peartube/list-personal-devices', getEncoding('@peartube/list-personal-devices-response')],
      ['@peartube/revoke-personal-device', getEncoding('@peartube/revoke-personal-device-response')],
      ['@peartube/join-channel', getEncoding('@peartube/join-channel-response')],
      ['@peartube/hide-channel', getEncoding('@peartube/hide-channel-response')],
      ['@peartube/get-channel-meta', getEncoding('@peartube/get-channel-meta-response')],
      ['@peartube/get-swarm-status', getEncoding('@peartube/get-swarm-status-response')],
      ['@peartube/create-device-invite', getEncoding('@peartube/create-device-invite-response')],
      ['@peartube/pair-device', getEncoding('@peartube/pair-device-response')],
      ['@peartube/list-devices', getEncoding('@peartube/list-devices-response')],
      ['@peartube/retry-sync-channel', getEncoding('@peartube/retry-sync-channel-response')],
      ['@peartube/prefetch-video', getEncoding('@peartube/prefetch-video-response')],
      ['@peartube/get-video-stats', getEncoding('@peartube/get-video-stats-response')],
      ['@peartube/get-seeding-status', getEncoding('@peartube/get-seeding-status-response')],
      ['@peartube/set-seeding-config', getEncoding('@peartube/set-seeding-config-response')],
      ['@peartube/get-transcode-settings', getEncoding('@peartube/get-transcode-settings-response')],
      ['@peartube/set-transcode-settings', getEncoding('@peartube/set-transcode-settings-response')],
      ['@peartube/pin-channel', getEncoding('@peartube/pin-channel-response')],
      ['@peartube/unpin-channel', getEncoding('@peartube/unpin-channel-response')],
      ['@peartube/get-pinned-channels', getEncoding('@peartube/get-pinned-channels-response')],
      ['@peartube/get-storage-stats', getEncoding('@peartube/get-storage-stats-response')],
      ['@peartube/set-storage-limit', getEncoding('@peartube/set-storage-limit-response')],
      ['@peartube/get-migration-status', getEncoding('@peartube/get-migration-status-response')],
      ['@peartube/retry-migration', getEncoding('@peartube/retry-migration-response')],
      ['@peartube/export-migration-report', getEncoding('@peartube/export-migration-report-response')],
      ['@peartube/get-publisher-device-status', getEncoding('@peartube/get-publisher-device-status-response')],
      ['@peartube/export-portable-state', getEncoding('@peartube/export-portable-state-response')],
      ['@peartube/restore-portable-state', getEncoding('@peartube/restore-portable-state-response')],
      ['@peartube/preview-storage-limit', getEncoding('@peartube/preview-storage-limit-response')],
      ['@peartube/get-archive-operator-status', getEncoding('@peartube/get-archive-operator-status-response')],
      ['@peartube/get-archive-participation', getEncoding('@peartube/get-archive-participation-response')],
      ['@peartube/set-archive-participation', getEncoding('@peartube/set-archive-participation-response')],
      ['@peartube/request-archive-publication', getEncoding('@peartube/request-archive-publication-response')],
      ['@peartube/get-network-policy', getEncoding('@peartube/get-network-policy-response')],
      ['@peartube/set-network-policy', getEncoding('@peartube/set-network-policy-response')],
      ['@peartube/clear-cache', getEncoding('@peartube/clear-cache-response')],
      ['@peartube/assess-source-offload', getEncoding('@peartube/assess-source-offload-response')],
      ['@peartube/confirm-source-offload', getEncoding('@peartube/confirm-source-offload-response')],
      ['@peartube/get-video-thumbnail', getEncoding('@peartube/get-video-thumbnail-response')],
      ['@peartube/get-video-metadata', getEncoding('@peartube/get-video-metadata-response')],
      ['@peartube/set-video-thumbnail', getEncoding('@peartube/set-video-thumbnail-response')],
      ['@peartube/set-video-thumbnail-from-file', getEncoding('@peartube/set-video-thumbnail-from-file-response')],
      ['@peartube/get-status', getEncoding('@peartube/get-status-response')],
      ['@peartube/pick-video-file', getEncoding('@peartube/pick-video-file-response')],
      ['@peartube/pick-image-file', getEncoding('@peartube/pick-image-file-response')],
      ['@peartube/get-blob-server-port', getEncoding('@peartube/get-blob-server-port-response')],
      ['@peartube/global-search-videos', getEncoding('@peartube/global-search-videos-response')],
      ['@peartube/add-comment', getEncoding('@peartube/add-comment-response')],
      ['@peartube/list-comments', getEncoding('@peartube/list-comments-response')],
      ['@peartube/hide-comment', getEncoding('@peartube/hide-comment-response')],
      ['@peartube/remove-comment', getEncoding('@peartube/remove-comment-response')],
      ['@peartube/add-reaction', getEncoding('@peartube/add-reaction-response')],
      ['@peartube/remove-reaction', getEncoding('@peartube/remove-reaction-response')],
      ['@peartube/get-reactions', getEncoding('@peartube/get-reactions-response')],
      ['@peartube/cast-available', getEncoding('@peartube/cast-available-response')],
      ['@peartube/cast-start-discovery', getEncoding('@peartube/cast-start-discovery-response')],
      ['@peartube/cast-stop-discovery', getEncoding('@peartube/cast-stop-discovery-response')],
      ['@peartube/cast-get-devices', getEncoding('@peartube/cast-get-devices-response')],
      ['@peartube/cast-add-manual-device', getEncoding('@peartube/cast-add-manual-device-response')],
      ['@peartube/cast-connect', getEncoding('@peartube/cast-connect-response')],
      ['@peartube/cast-disconnect', getEncoding('@peartube/cast-disconnect-response')],
      ['@peartube/cast-play', getEncoding('@peartube/cast-play-response')],
      ['@peartube/cast-pause', getEncoding('@peartube/cast-pause-response')],
      ['@peartube/cast-resume', getEncoding('@peartube/cast-resume-response')],
      ['@peartube/cast-stop', getEncoding('@peartube/cast-stop-response')],
      ['@peartube/cast-seek', getEncoding('@peartube/cast-seek-response')],
      ['@peartube/cast-set-volume', getEncoding('@peartube/cast-set-volume-response')],
      ['@peartube/cast-get-state', getEncoding('@peartube/cast-get-state-response')],
      ['@peartube/cast-is-connected', getEncoding('@peartube/cast-is-connected-response')],
      ['@peartube/search-videos', getEncoding('@peartube/search-videos-response')],
      ['@peartube/index-video-vectors', getEncoding('@peartube/index-video-vectors-response')],
      ['@peartube/update-video-metadata', getEncoding('@peartube/update-video-metadata-response')],
      ['@peartube/get-media-catalog', getEncoding('@peartube/get-media-catalog-response')],
      ['@peartube/get-media-entity', getEncoding('@peartube/get-media-entity-response')],
      ['@peartube/get-media-collection', getEncoding('@peartube/get-media-collection-response')],
      ['@peartube/get-media-collection-items', getEncoding('@peartube/get-media-collection-items-response')],
      ['@peartube/get-media-agent', getEncoding('@peartube/get-media-agent-response')],
      ['@peartube/get-agent-contributions', getEncoding('@peartube/get-agent-contributions-response')],
      ['@peartube/get-publication-sources', getEncoding('@peartube/get-publication-sources-response')],
      ['@peartube/get-entity-artwork', getEncoding('@peartube/get-entity-artwork-response')],
      ['@peartube/get-claim-provenance', getEncoding('@peartube/get-claim-provenance-response')],
      ['@peartube/set-source-preference', getEncoding('@peartube/set-source-preference-response')],
      ['@peartube/prepare-media-playback', getEncoding('@peartube/prepare-media-playback-response')],
      ['@peartube/desktop-bootstrap', getEncoding('@peartube/desktop-bootstrap-response')],
      ['@peartube/desktop-shutdown', getEncoding('@peartube/desktop-shutdown-response')],
      ['@peartube/desktop-refresh-browse', getEncoding('@peartube/desktop-refresh-browse-response')],
      ['@peartube/ffmpeg-decode-available', getEncoding('@peartube/ffmpeg-decode-available-response')],
      ['@peartube/update-channel-avatar', getEncoding('@peartube/update-channel-avatar-response')],
      ['@peartube/transcode-start', getEncoding('@peartube/transcode-start-response')],
      ['@peartube/transcode-stop', getEncoding('@peartube/transcode-stop-response')],
      ['@peartube/transcode-status', getEncoding('@peartube/transcode-status-response')]
    ])
    this._rpc = new RPC(stream, async (req) => {
      const command = methods.get(req.command)
      if (!command || typeof this._handlers[command] !== 'function') return
      const responseEncoding = this._responseEncodings.get(command)
      const requestEncoding = this._requestEncodings.get(command)
      if (this._requestIsSend(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        await this._handlers[command](request)
        return
      }
      if (!this._requestIsStream(command) && !this._responseIsStream(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        const response = await this._handlers[command](request)
        req.reply(c.encode(responseEncoding, response))
      }
      if (!this._requestIsStream(command) && this._responseIsStream(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        const responseStream = new RPCStream(
          null,
          null,
          req.createResponseStream(),
          responseEncoding
        )
        responseStream.data = request
        await this._handlers[command](responseStream)
      }
      if (this._requestIsStream(command) && !this._responseIsStream(command)) {
        const requestStream = new RPCRequestStream(
          req,
          responseEncoding,
          req.createRequestStream(),
          requestEncoding
        )
        const response = await this._handlers[command](requestStream)
        req.reply(c.encode(responseEncoding, response))
      }
      if (this._requestIsStream(command) && this._responseIsStream(command)) {
        const requestStream = new RPCRequestStream(
          req,
          responseEncoding,
          req.createRequestStream(),
          requestEncoding,
          req.createResponseStream(),
          responseEncoding
        )
        await this._handlers[command](requestStream)
      }
    })
  }

  async _call(name, args) {
    const requestEncoding = this._requestEncodings.get(name)
    const responseEncoding = this._responseEncodings.get(name)
    const request = this._rpc.request(methods.get(name))
    const encoded = c.encode(requestEncoding, args)
    request.send(encoded)
    return c.decode(responseEncoding, await request.reply())
  }

  _callSync(name, args) {
    const requestEncoding = this._requestEncodings.get(name)
    const responseEncoding = this._responseEncodings.get(name)
    if (this._requestIsSend(name)) {
      const encoded = c.encode(requestEncoding, args)
      const request = this._rpc.event(methods.get(name))
      request.send(encoded)
    }

    const request = this._rpc.request(methods.get(name))

    if (!this._requestIsStream(name) && this._responseIsStream(name)) {
      const encoded = c.encode(requestEncoding, args)
      request.send(encoded)
      return new RPCStream(request.createResponseStream(), responseEncoding)
    }
    if (this._requestIsStream(name) && !this._responseIsStream(name)) {
      return new RPCRequestStream(
        request,
        responseEncoding,
        null,
        null,
        request.createRequestStream(),
        requestEncoding
      )
    }
    if (this._requestIsStream(name) && this._responseIsStream(name)) {
      return new RPCRequestStream(
        request,
        responseEncoding,
        request.createResponseStream(),
        responseEncoding,
        request.createRequestStream(),
        requestEncoding
      )
    }
  }

  async createIdentity(args) {
    return this._call('@peartube/create-identity', args)
  }

  async getIdentity(args) {
    return this._call('@peartube/get-identity', args)
  }

  async getIdentities(args) {
    return this._call('@peartube/get-identities', args)
  }

  async setActiveIdentity(args) {
    return this._call('@peartube/set-active-identity', args)
  }

  async recoverIdentity(args) {
    return this._call('@peartube/recover-identity', args)
  }

  async bootstrapDevice(args) {
    return this._call('@peartube/bootstrap-device', args)
  }

  async attestDevice(args) {
    return this._call('@peartube/attest-device', args)
  }

  async provisionPublisherCatalog(args) {
    return this._call('@peartube/provision-publisher-catalog', args)
  }

  async verifyAttestation(args) {
    return this._call('@peartube/verify-attestation', args)
  }

  async preparePublisherRootOperation(args) {
    return this._call('@peartube/prepare-publisher-root-operation', args)
  }

  async submitPublisherRootOperation(args) {
    return this._call('@peartube/submit-publisher-root-operation', args)
  }

  async getChannel(args) {
    return this._call('@peartube/get-channel', args)
  }

  async updateChannel(args) {
    return this._call('@peartube/update-channel', args)
  }

  async getContentCatalog(args) {
    return this._call('@peartube/get-content-catalog', args)
  }

  async getContentItems(args) {
    return this._call('@peartube/get-content-items', args)
  }

  async listVideos(args) {
    return this._call('@peartube/list-videos', args)
  }

  async getVideoUrl(args) {
    return this._call('@peartube/get-video-url', args)
  }

  async preparePlayback(args) {
    return this._call('@peartube/prepare-playback', args)
  }

  async webPreparePlayback(args) {
    return this._call('@peartube/web-prepare-playback', args)
  }

  async getVideoData(args) {
    return this._call('@peartube/get-video-data', args)
  }

  async uploadVideo(args) {
    return this._call('@peartube/upload-video', args)
  }

  async downloadVideo(args) {
    return this._call('@peartube/download-video', args)
  }

  async deleteVideo(args) {
    return this._call('@peartube/delete-video', args)
  }

  async startLivestream(args) {
    return this._call('@peartube/start-livestream', args)
  }

  async stopLivestream(args) {
    return this._call('@peartube/stop-livestream', args)
  }

  async getLivestreamStatus(args) {
    return this._call('@peartube/get-livestream-status', args)
  }

  async prepareLivePlayback(args) {
    return this._call('@peartube/prepare-live-playback', args)
  }

  async subscribeChannel(args) {
    return this._call('@peartube/subscribe-channel', args)
  }

  async unsubscribeChannel(args) {
    return this._call('@peartube/unsubscribe-channel', args)
  }

  async getSubscriptions(args) {
    return this._call('@peartube/get-subscriptions', args)
  }

  async getPlaylists(args) {
    return this._call('@peartube/get-playlists', args)
  }

  async getPlaylistItems(args) {
    return this._call('@peartube/get-playlist-items', args)
  }

  async createPlaylist(args) {
    return this._call('@peartube/create-playlist', args)
  }

  async updatePlaylist(args) {
    return this._call('@peartube/update-playlist', args)
  }

  async deletePlaylist(args) {
    return this._call('@peartube/delete-playlist', args)
  }

  async addToPlaylist(args) {
    return this._call('@peartube/add-to-playlist', args)
  }

  async removeFromPlaylist(args) {
    return this._call('@peartube/remove-from-playlist', args)
  }

  async logWatchHistory(args) {
    return this._call('@peartube/log-watch-history', args)
  }

  async getWatchHistory(args) {
    return this._call('@peartube/get-watch-history', args)
  }

  async getResumePosition(args) {
    return this._call('@peartube/get-resume-position', args)
  }

  async listResumePositions(args) {
    return this._call('@peartube/list-resume-positions', args)
  }

  async setPersonalSetting(args) {
    return this._call('@peartube/set-personal-setting', args)
  }

  async getPersonalSettings(args) {
    return this._call('@peartube/get-personal-settings', args)
  }

  async provisionPersonalEncryption(args) {
    return this._call('@peartube/provision-personal-encryption', args)
  }

  async createPersonalDeviceInvite(args) {
    return this._call('@peartube/create-personal-device-invite', args)
  }

  async redeemPersonalDeviceInvite(args) {
    return this._call('@peartube/redeem-personal-device-invite', args)
  }

  async listPersonalDevices(args) {
    return this._call('@peartube/list-personal-devices', args)
  }

  async revokePersonalDevice(args) {
    return this._call('@peartube/revoke-personal-device', args)
  }

  async joinChannel(args) {
    return this._call('@peartube/join-channel', args)
  }

  async hideChannel(args) {
    return this._call('@peartube/hide-channel', args)
  }

  async getChannelMeta(args) {
    return this._call('@peartube/get-channel-meta', args)
  }

  async getSwarmStatus(args) {
    return this._call('@peartube/get-swarm-status', args)
  }

  async createDeviceInvite(args) {
    return this._call('@peartube/create-device-invite', args)
  }

  async pairDevice(args) {
    return this._call('@peartube/pair-device', args)
  }

  async listDevices(args) {
    return this._call('@peartube/list-devices', args)
  }

  async retrySyncChannel(args) {
    return this._call('@peartube/retry-sync-channel', args)
  }

  async prefetchVideo(args) {
    return this._call('@peartube/prefetch-video', args)
  }

  async getVideoStats(args) {
    return this._call('@peartube/get-video-stats', args)
  }

  async getSeedingStatus(args) {
    return this._call('@peartube/get-seeding-status', args)
  }

  async setSeedingConfig(args) {
    return this._call('@peartube/set-seeding-config', args)
  }

  async getTranscodeSettings(args) {
    return this._call('@peartube/get-transcode-settings', args)
  }

  async setTranscodeSettings(args) {
    return this._call('@peartube/set-transcode-settings', args)
  }

  async pinChannel(args) {
    return this._call('@peartube/pin-channel', args)
  }

  async unpinChannel(args) {
    return this._call('@peartube/unpin-channel', args)
  }

  async getPinnedChannels(args) {
    return this._call('@peartube/get-pinned-channels', args)
  }

  async getStorageStats(args) {
    return this._call('@peartube/get-storage-stats', args)
  }

  async setStorageLimit(args) {
    return this._call('@peartube/set-storage-limit', args)
  }

  async getMigrationStatus(args) {
    return this._call('@peartube/get-migration-status', args)
  }

  async retryMigration(args) {
    return this._call('@peartube/retry-migration', args)
  }

  async exportMigrationReport(args) {
    return this._call('@peartube/export-migration-report', args)
  }

  async getPublisherDeviceStatus(args) {
    return this._call('@peartube/get-publisher-device-status', args)
  }

  async exportPortableState(args) {
    return this._call('@peartube/export-portable-state', args)
  }

  async restorePortableState(args) {
    return this._call('@peartube/restore-portable-state', args)
  }

  async previewStorageLimit(args) {
    return this._call('@peartube/preview-storage-limit', args)
  }

  async getArchiveOperatorStatus(args) {
    return this._call('@peartube/get-archive-operator-status', args)
  }

  async getArchiveParticipation(args) {
    return this._call('@peartube/get-archive-participation', args)
  }

  async setArchiveParticipation(args) {
    return this._call('@peartube/set-archive-participation', args)
  }

  async requestArchivePublication(args) {
    return this._call('@peartube/request-archive-publication', args)
  }

  async getNetworkPolicy(args) {
    return this._call('@peartube/get-network-policy', args)
  }

  async setNetworkPolicy(args) {
    return this._call('@peartube/set-network-policy', args)
  }

  async clearCache(args) {
    return this._call('@peartube/clear-cache', args)
  }

  async assessSourceOffload(args) {
    return this._call('@peartube/assess-source-offload', args)
  }

  async confirmSourceOffload(args) {
    return this._call('@peartube/confirm-source-offload', args)
  }

  async getVideoThumbnail(args) {
    return this._call('@peartube/get-video-thumbnail', args)
  }

  async getVideoMetadata(args) {
    return this._call('@peartube/get-video-metadata', args)
  }

  async setVideoThumbnail(args) {
    return this._call('@peartube/set-video-thumbnail', args)
  }

  async setVideoThumbnailFromFile(args) {
    return this._call('@peartube/set-video-thumbnail-from-file', args)
  }

  async getStatus(args) {
    return this._call('@peartube/get-status', args)
  }

  async pickVideoFile(args) {
    return this._call('@peartube/pick-video-file', args)
  }

  async pickImageFile(args) {
    return this._call('@peartube/pick-image-file', args)
  }

  async getBlobServerPort(args) {
    return this._call('@peartube/get-blob-server-port', args)
  }

  async globalSearchVideos(args) {
    return this._call('@peartube/global-search-videos', args)
  }

  async addComment(args) {
    return this._call('@peartube/add-comment', args)
  }

  async listComments(args) {
    return this._call('@peartube/list-comments', args)
  }

  async hideComment(args) {
    return this._call('@peartube/hide-comment', args)
  }

  async removeComment(args) {
    return this._call('@peartube/remove-comment', args)
  }

  async addReaction(args) {
    return this._call('@peartube/add-reaction', args)
  }

  async removeReaction(args) {
    return this._call('@peartube/remove-reaction', args)
  }

  async getReactions(args) {
    return this._call('@peartube/get-reactions', args)
  }

  eventReady(args) {
    return this._callSync('@peartube/event-ready', args)
  }

  eventError(args) {
    return this._callSync('@peartube/event-error', args)
  }

  eventUploadProgress(args) {
    return this._callSync('@peartube/event-upload-progress', args)
  }

  eventDownloadProgress(args) {
    return this._callSync('@peartube/event-download-progress', args)
  }

  eventMediaGraphUpdate(args) {
    return this._callSync('@peartube/event-media-graph-update', args)
  }

  eventLog(args) {
    return this._callSync('@peartube/event-log', args)
  }

  eventVideoStats(args) {
    return this._callSync('@peartube/event-video-stats', args)
  }

  async castAvailable(args) {
    return this._call('@peartube/cast-available', args)
  }

  async castStartDiscovery(args) {
    return this._call('@peartube/cast-start-discovery', args)
  }

  async castStopDiscovery(args) {
    return this._call('@peartube/cast-stop-discovery', args)
  }

  async castGetDevices(args) {
    return this._call('@peartube/cast-get-devices', args)
  }

  async castAddManualDevice(args) {
    return this._call('@peartube/cast-add-manual-device', args)
  }

  async castConnect(args) {
    return this._call('@peartube/cast-connect', args)
  }

  async castDisconnect(args) {
    return this._call('@peartube/cast-disconnect', args)
  }

  async castPlay(args) {
    return this._call('@peartube/cast-play', args)
  }

  async castPause(args) {
    return this._call('@peartube/cast-pause', args)
  }

  async castResume(args) {
    return this._call('@peartube/cast-resume', args)
  }

  async castStop(args) {
    return this._call('@peartube/cast-stop', args)
  }

  async castSeek(args) {
    return this._call('@peartube/cast-seek', args)
  }

  async castSetVolume(args) {
    return this._call('@peartube/cast-set-volume', args)
  }

  async castGetState(args) {
    return this._call('@peartube/cast-get-state', args)
  }

  async castIsConnected(args) {
    return this._call('@peartube/cast-is-connected', args)
  }

  eventCastDeviceFound(args) {
    return this._callSync('@peartube/event-cast-device-found', args)
  }

  eventCastDeviceLost(args) {
    return this._callSync('@peartube/event-cast-device-lost', args)
  }

  eventCastPlaybackState(args) {
    return this._callSync('@peartube/event-cast-playback-state', args)
  }

  eventCastTimeUpdate(args) {
    return this._callSync('@peartube/event-cast-time-update', args)
  }

  async searchVideos(args) {
    return this._call('@peartube/search-videos', args)
  }

  async indexVideoVectors(args) {
    return this._call('@peartube/index-video-vectors', args)
  }

  async updateVideoMetadata(args) {
    return this._call('@peartube/update-video-metadata', args)
  }

  async getMediaCatalog(args) {
    return this._call('@peartube/get-media-catalog', args)
  }

  async getMediaEntity(args) {
    return this._call('@peartube/get-media-entity', args)
  }

  async getMediaCollection(args) {
    return this._call('@peartube/get-media-collection', args)
  }

  async getMediaCollectionItems(args) {
    return this._call('@peartube/get-media-collection-items', args)
  }

  async getMediaAgent(args) {
    return this._call('@peartube/get-media-agent', args)
  }

  async getAgentContributions(args) {
    return this._call('@peartube/get-agent-contributions', args)
  }

  async getPublicationSources(args) {
    return this._call('@peartube/get-publication-sources', args)
  }

  async getEntityArtwork(args) {
    return this._call('@peartube/get-entity-artwork', args)
  }

  async getClaimProvenance(args) {
    return this._call('@peartube/get-claim-provenance', args)
  }

  async setSourcePreference(args) {
    return this._call('@peartube/set-source-preference', args)
  }

  async prepareMediaPlayback(args) {
    return this._call('@peartube/prepare-media-playback', args)
  }

  async desktopBootstrap(args) {
    return this._call('@peartube/desktop-bootstrap', args)
  }

  async desktopShutdown(args) {
    return this._call('@peartube/desktop-shutdown', args)
  }

  async desktopRefreshBrowse(args) {
    return this._call('@peartube/desktop-refresh-browse', args)
  }

  async ffmpegDecodeAvailable(args) {
    return this._call('@peartube/ffmpeg-decode-available', args)
  }

  async updateChannelAvatar(args) {
    return this._call('@peartube/update-channel-avatar', args)
  }

  async transcodeStart(args) {
    return this._call('@peartube/transcode-start', args)
  }

  async transcodeStop(args) {
    return this._call('@peartube/transcode-stop', args)
  }

  async transcodeStatus(args) {
    return this._call('@peartube/transcode-status', args)
  }

  eventTranscodeProgress(args) {
    return this._callSync('@peartube/event-transcode-progress', args)
  }

  onCreateIdentity(responseFn) {
    this._handlers['@peartube/create-identity'] = responseFn
  }

  onGetIdentity(responseFn) {
    this._handlers['@peartube/get-identity'] = responseFn
  }

  onGetIdentities(responseFn) {
    this._handlers['@peartube/get-identities'] = responseFn
  }

  onSetActiveIdentity(responseFn) {
    this._handlers['@peartube/set-active-identity'] = responseFn
  }

  onRecoverIdentity(responseFn) {
    this._handlers['@peartube/recover-identity'] = responseFn
  }

  onBootstrapDevice(responseFn) {
    this._handlers['@peartube/bootstrap-device'] = responseFn
  }

  onAttestDevice(responseFn) {
    this._handlers['@peartube/attest-device'] = responseFn
  }

  onProvisionPublisherCatalog(responseFn) {
    this._handlers['@peartube/provision-publisher-catalog'] = responseFn
  }

  onVerifyAttestation(responseFn) {
    this._handlers['@peartube/verify-attestation'] = responseFn
  }

  onPreparePublisherRootOperation(responseFn) {
    this._handlers['@peartube/prepare-publisher-root-operation'] = responseFn
  }

  onSubmitPublisherRootOperation(responseFn) {
    this._handlers['@peartube/submit-publisher-root-operation'] = responseFn
  }

  onGetChannel(responseFn) {
    this._handlers['@peartube/get-channel'] = responseFn
  }

  onUpdateChannel(responseFn) {
    this._handlers['@peartube/update-channel'] = responseFn
  }

  onGetContentCatalog(responseFn) {
    this._handlers['@peartube/get-content-catalog'] = responseFn
  }

  onGetContentItems(responseFn) {
    this._handlers['@peartube/get-content-items'] = responseFn
  }

  onListVideos(responseFn) {
    this._handlers['@peartube/list-videos'] = responseFn
  }

  onGetVideoUrl(responseFn) {
    this._handlers['@peartube/get-video-url'] = responseFn
  }

  onPreparePlayback(responseFn) {
    this._handlers['@peartube/prepare-playback'] = responseFn
  }

  onWebPreparePlayback(responseFn) {
    this._handlers['@peartube/web-prepare-playback'] = responseFn
  }

  onGetVideoData(responseFn) {
    this._handlers['@peartube/get-video-data'] = responseFn
  }

  onUploadVideo(responseFn) {
    this._handlers['@peartube/upload-video'] = responseFn
  }

  onDownloadVideo(responseFn) {
    this._handlers['@peartube/download-video'] = responseFn
  }

  onDeleteVideo(responseFn) {
    this._handlers['@peartube/delete-video'] = responseFn
  }

  onStartLivestream(responseFn) {
    this._handlers['@peartube/start-livestream'] = responseFn
  }

  onStopLivestream(responseFn) {
    this._handlers['@peartube/stop-livestream'] = responseFn
  }

  onGetLivestreamStatus(responseFn) {
    this._handlers['@peartube/get-livestream-status'] = responseFn
  }

  onPrepareLivePlayback(responseFn) {
    this._handlers['@peartube/prepare-live-playback'] = responseFn
  }

  onSubscribeChannel(responseFn) {
    this._handlers['@peartube/subscribe-channel'] = responseFn
  }

  onUnsubscribeChannel(responseFn) {
    this._handlers['@peartube/unsubscribe-channel'] = responseFn
  }

  onGetSubscriptions(responseFn) {
    this._handlers['@peartube/get-subscriptions'] = responseFn
  }

  onGetPlaylists(responseFn) {
    this._handlers['@peartube/get-playlists'] = responseFn
  }

  onGetPlaylistItems(responseFn) {
    this._handlers['@peartube/get-playlist-items'] = responseFn
  }

  onCreatePlaylist(responseFn) {
    this._handlers['@peartube/create-playlist'] = responseFn
  }

  onUpdatePlaylist(responseFn) {
    this._handlers['@peartube/update-playlist'] = responseFn
  }

  onDeletePlaylist(responseFn) {
    this._handlers['@peartube/delete-playlist'] = responseFn
  }

  onAddToPlaylist(responseFn) {
    this._handlers['@peartube/add-to-playlist'] = responseFn
  }

  onRemoveFromPlaylist(responseFn) {
    this._handlers['@peartube/remove-from-playlist'] = responseFn
  }

  onLogWatchHistory(responseFn) {
    this._handlers['@peartube/log-watch-history'] = responseFn
  }

  onGetWatchHistory(responseFn) {
    this._handlers['@peartube/get-watch-history'] = responseFn
  }

  onGetResumePosition(responseFn) {
    this._handlers['@peartube/get-resume-position'] = responseFn
  }

  onListResumePositions(responseFn) {
    this._handlers['@peartube/list-resume-positions'] = responseFn
  }

  onSetPersonalSetting(responseFn) {
    this._handlers['@peartube/set-personal-setting'] = responseFn
  }

  onGetPersonalSettings(responseFn) {
    this._handlers['@peartube/get-personal-settings'] = responseFn
  }

  onProvisionPersonalEncryption(responseFn) {
    this._handlers['@peartube/provision-personal-encryption'] = responseFn
  }

  onCreatePersonalDeviceInvite(responseFn) {
    this._handlers['@peartube/create-personal-device-invite'] = responseFn
  }

  onRedeemPersonalDeviceInvite(responseFn) {
    this._handlers['@peartube/redeem-personal-device-invite'] = responseFn
  }

  onListPersonalDevices(responseFn) {
    this._handlers['@peartube/list-personal-devices'] = responseFn
  }

  onRevokePersonalDevice(responseFn) {
    this._handlers['@peartube/revoke-personal-device'] = responseFn
  }

  onJoinChannel(responseFn) {
    this._handlers['@peartube/join-channel'] = responseFn
  }

  onHideChannel(responseFn) {
    this._handlers['@peartube/hide-channel'] = responseFn
  }

  onGetChannelMeta(responseFn) {
    this._handlers['@peartube/get-channel-meta'] = responseFn
  }

  onGetSwarmStatus(responseFn) {
    this._handlers['@peartube/get-swarm-status'] = responseFn
  }

  onCreateDeviceInvite(responseFn) {
    this._handlers['@peartube/create-device-invite'] = responseFn
  }

  onPairDevice(responseFn) {
    this._handlers['@peartube/pair-device'] = responseFn
  }

  onListDevices(responseFn) {
    this._handlers['@peartube/list-devices'] = responseFn
  }

  onRetrySyncChannel(responseFn) {
    this._handlers['@peartube/retry-sync-channel'] = responseFn
  }

  onPrefetchVideo(responseFn) {
    this._handlers['@peartube/prefetch-video'] = responseFn
  }

  onGetVideoStats(responseFn) {
    this._handlers['@peartube/get-video-stats'] = responseFn
  }

  onGetSeedingStatus(responseFn) {
    this._handlers['@peartube/get-seeding-status'] = responseFn
  }

  onSetSeedingConfig(responseFn) {
    this._handlers['@peartube/set-seeding-config'] = responseFn
  }

  onGetTranscodeSettings(responseFn) {
    this._handlers['@peartube/get-transcode-settings'] = responseFn
  }

  onSetTranscodeSettings(responseFn) {
    this._handlers['@peartube/set-transcode-settings'] = responseFn
  }

  onPinChannel(responseFn) {
    this._handlers['@peartube/pin-channel'] = responseFn
  }

  onUnpinChannel(responseFn) {
    this._handlers['@peartube/unpin-channel'] = responseFn
  }

  onGetPinnedChannels(responseFn) {
    this._handlers['@peartube/get-pinned-channels'] = responseFn
  }

  onGetStorageStats(responseFn) {
    this._handlers['@peartube/get-storage-stats'] = responseFn
  }

  onSetStorageLimit(responseFn) {
    this._handlers['@peartube/set-storage-limit'] = responseFn
  }

  onGetMigrationStatus(responseFn) {
    this._handlers['@peartube/get-migration-status'] = responseFn
  }

  onRetryMigration(responseFn) {
    this._handlers['@peartube/retry-migration'] = responseFn
  }

  onExportMigrationReport(responseFn) {
    this._handlers['@peartube/export-migration-report'] = responseFn
  }

  onGetPublisherDeviceStatus(responseFn) {
    this._handlers['@peartube/get-publisher-device-status'] = responseFn
  }

  onExportPortableState(responseFn) {
    this._handlers['@peartube/export-portable-state'] = responseFn
  }

  onRestorePortableState(responseFn) {
    this._handlers['@peartube/restore-portable-state'] = responseFn
  }

  onPreviewStorageLimit(responseFn) {
    this._handlers['@peartube/preview-storage-limit'] = responseFn
  }

  onGetArchiveOperatorStatus(responseFn) {
    this._handlers['@peartube/get-archive-operator-status'] = responseFn
  }

  onGetArchiveParticipation(responseFn) {
    this._handlers['@peartube/get-archive-participation'] = responseFn
  }

  onSetArchiveParticipation(responseFn) {
    this._handlers['@peartube/set-archive-participation'] = responseFn
  }

  onRequestArchivePublication(responseFn) {
    this._handlers['@peartube/request-archive-publication'] = responseFn
  }

  onGetNetworkPolicy(responseFn) {
    this._handlers['@peartube/get-network-policy'] = responseFn
  }

  onSetNetworkPolicy(responseFn) {
    this._handlers['@peartube/set-network-policy'] = responseFn
  }

  onClearCache(responseFn) {
    this._handlers['@peartube/clear-cache'] = responseFn
  }

  onAssessSourceOffload(responseFn) {
    this._handlers['@peartube/assess-source-offload'] = responseFn
  }

  onConfirmSourceOffload(responseFn) {
    this._handlers['@peartube/confirm-source-offload'] = responseFn
  }

  onGetVideoThumbnail(responseFn) {
    this._handlers['@peartube/get-video-thumbnail'] = responseFn
  }

  onGetVideoMetadata(responseFn) {
    this._handlers['@peartube/get-video-metadata'] = responseFn
  }

  onSetVideoThumbnail(responseFn) {
    this._handlers['@peartube/set-video-thumbnail'] = responseFn
  }

  onSetVideoThumbnailFromFile(responseFn) {
    this._handlers['@peartube/set-video-thumbnail-from-file'] = responseFn
  }

  onGetStatus(responseFn) {
    this._handlers['@peartube/get-status'] = responseFn
  }

  onPickVideoFile(responseFn) {
    this._handlers['@peartube/pick-video-file'] = responseFn
  }

  onPickImageFile(responseFn) {
    this._handlers['@peartube/pick-image-file'] = responseFn
  }

  onGetBlobServerPort(responseFn) {
    this._handlers['@peartube/get-blob-server-port'] = responseFn
  }

  onGlobalSearchVideos(responseFn) {
    this._handlers['@peartube/global-search-videos'] = responseFn
  }

  onAddComment(responseFn) {
    this._handlers['@peartube/add-comment'] = responseFn
  }

  onListComments(responseFn) {
    this._handlers['@peartube/list-comments'] = responseFn
  }

  onHideComment(responseFn) {
    this._handlers['@peartube/hide-comment'] = responseFn
  }

  onRemoveComment(responseFn) {
    this._handlers['@peartube/remove-comment'] = responseFn
  }

  onAddReaction(responseFn) {
    this._handlers['@peartube/add-reaction'] = responseFn
  }

  onRemoveReaction(responseFn) {
    this._handlers['@peartube/remove-reaction'] = responseFn
  }

  onGetReactions(responseFn) {
    this._handlers['@peartube/get-reactions'] = responseFn
  }

  onEventReady(responseFn) {
    this._handlers['@peartube/event-ready'] = responseFn
  }

  onEventError(responseFn) {
    this._handlers['@peartube/event-error'] = responseFn
  }

  onEventUploadProgress(responseFn) {
    this._handlers['@peartube/event-upload-progress'] = responseFn
  }

  onEventDownloadProgress(responseFn) {
    this._handlers['@peartube/event-download-progress'] = responseFn
  }

  onEventMediaGraphUpdate(responseFn) {
    this._handlers['@peartube/event-media-graph-update'] = responseFn
  }

  onEventLog(responseFn) {
    this._handlers['@peartube/event-log'] = responseFn
  }

  onEventVideoStats(responseFn) {
    this._handlers['@peartube/event-video-stats'] = responseFn
  }

  onCastAvailable(responseFn) {
    this._handlers['@peartube/cast-available'] = responseFn
  }

  onCastStartDiscovery(responseFn) {
    this._handlers['@peartube/cast-start-discovery'] = responseFn
  }

  onCastStopDiscovery(responseFn) {
    this._handlers['@peartube/cast-stop-discovery'] = responseFn
  }

  onCastGetDevices(responseFn) {
    this._handlers['@peartube/cast-get-devices'] = responseFn
  }

  onCastAddManualDevice(responseFn) {
    this._handlers['@peartube/cast-add-manual-device'] = responseFn
  }

  onCastConnect(responseFn) {
    this._handlers['@peartube/cast-connect'] = responseFn
  }

  onCastDisconnect(responseFn) {
    this._handlers['@peartube/cast-disconnect'] = responseFn
  }

  onCastPlay(responseFn) {
    this._handlers['@peartube/cast-play'] = responseFn
  }

  onCastPause(responseFn) {
    this._handlers['@peartube/cast-pause'] = responseFn
  }

  onCastResume(responseFn) {
    this._handlers['@peartube/cast-resume'] = responseFn
  }

  onCastStop(responseFn) {
    this._handlers['@peartube/cast-stop'] = responseFn
  }

  onCastSeek(responseFn) {
    this._handlers['@peartube/cast-seek'] = responseFn
  }

  onCastSetVolume(responseFn) {
    this._handlers['@peartube/cast-set-volume'] = responseFn
  }

  onCastGetState(responseFn) {
    this._handlers['@peartube/cast-get-state'] = responseFn
  }

  onCastIsConnected(responseFn) {
    this._handlers['@peartube/cast-is-connected'] = responseFn
  }

  onEventCastDeviceFound(responseFn) {
    this._handlers['@peartube/event-cast-device-found'] = responseFn
  }

  onEventCastDeviceLost(responseFn) {
    this._handlers['@peartube/event-cast-device-lost'] = responseFn
  }

  onEventCastPlaybackState(responseFn) {
    this._handlers['@peartube/event-cast-playback-state'] = responseFn
  }

  onEventCastTimeUpdate(responseFn) {
    this._handlers['@peartube/event-cast-time-update'] = responseFn
  }

  onSearchVideos(responseFn) {
    this._handlers['@peartube/search-videos'] = responseFn
  }

  onIndexVideoVectors(responseFn) {
    this._handlers['@peartube/index-video-vectors'] = responseFn
  }

  onUpdateVideoMetadata(responseFn) {
    this._handlers['@peartube/update-video-metadata'] = responseFn
  }

  onGetMediaCatalog(responseFn) {
    this._handlers['@peartube/get-media-catalog'] = responseFn
  }

  onGetMediaEntity(responseFn) {
    this._handlers['@peartube/get-media-entity'] = responseFn
  }

  onGetMediaCollection(responseFn) {
    this._handlers['@peartube/get-media-collection'] = responseFn
  }

  onGetMediaCollectionItems(responseFn) {
    this._handlers['@peartube/get-media-collection-items'] = responseFn
  }

  onGetMediaAgent(responseFn) {
    this._handlers['@peartube/get-media-agent'] = responseFn
  }

  onGetAgentContributions(responseFn) {
    this._handlers['@peartube/get-agent-contributions'] = responseFn
  }

  onGetPublicationSources(responseFn) {
    this._handlers['@peartube/get-publication-sources'] = responseFn
  }

  onGetEntityArtwork(responseFn) {
    this._handlers['@peartube/get-entity-artwork'] = responseFn
  }

  onGetClaimProvenance(responseFn) {
    this._handlers['@peartube/get-claim-provenance'] = responseFn
  }

  onSetSourcePreference(responseFn) {
    this._handlers['@peartube/set-source-preference'] = responseFn
  }

  onPrepareMediaPlayback(responseFn) {
    this._handlers['@peartube/prepare-media-playback'] = responseFn
  }

  onDesktopBootstrap(responseFn) {
    this._handlers['@peartube/desktop-bootstrap'] = responseFn
  }

  onDesktopShutdown(responseFn) {
    this._handlers['@peartube/desktop-shutdown'] = responseFn
  }

  onDesktopRefreshBrowse(responseFn) {
    this._handlers['@peartube/desktop-refresh-browse'] = responseFn
  }

  onFfmpegDecodeAvailable(responseFn) {
    this._handlers['@peartube/ffmpeg-decode-available'] = responseFn
  }

  onUpdateChannelAvatar(responseFn) {
    this._handlers['@peartube/update-channel-avatar'] = responseFn
  }

  onTranscodeStart(responseFn) {
    this._handlers['@peartube/transcode-start'] = responseFn
  }

  onTranscodeStop(responseFn) {
    this._handlers['@peartube/transcode-stop'] = responseFn
  }

  onTranscodeStatus(responseFn) {
    this._handlers['@peartube/transcode-status'] = responseFn
  }

  onEventTranscodeProgress(responseFn) {
    this._handlers['@peartube/event-transcode-progress'] = responseFn
  }

  _requestIsStream(command) {
    return [
    ].includes(command)
  }

  _responseIsStream(command) {
    return [
    ].includes(command)
  }

  // prettier-ignore-start
  _requestIsSend(command) {
    return [
      // prettier-ignore
      '@peartube/event-ready',
      '@peartube/event-error',
      '@peartube/event-upload-progress',
      '@peartube/event-download-progress',
      '@peartube/event-media-graph-update',
      '@peartube/event-log',
      '@peartube/event-video-stats',
      '@peartube/event-cast-device-found',
      '@peartube/event-cast-device-lost',
      '@peartube/event-cast-playback-state',
      '@peartube/event-cast-time-update',
      '@peartube/event-transcode-progress'
    ].includes(command)
  }
}

module.exports = HRPC
