// This file is autogenerated by the hrpc compiler
/* eslint-disable camelcase */
/* eslint-disable space-before-function-paren */

const { c, RPC, RPCStream, RPCRequestStream } = require('hrpc/runtime')
const { getEncoding } = require('./messages.js')

const methods = new Map([
  ['@peartube/create-identity', 0],
  [0, '@peartube/create-identity'],
  ['@peartube/get-identity', 1],
  [1, '@peartube/get-identity'],
  ['@peartube/get-identities', 2],
  [2, '@peartube/get-identities'],
  ['@peartube/set-active-identity', 3],
  [3, '@peartube/set-active-identity'],
  ['@peartube/recover-identity', 4],
  [4, '@peartube/recover-identity'],
  ['@peartube/get-channel', 5],
  [5, '@peartube/get-channel'],
  ['@peartube/update-channel', 6],
  [6, '@peartube/update-channel'],
  ['@peartube/list-videos', 7],
  [7, '@peartube/list-videos'],
  ['@peartube/get-video-url', 8],
  [8, '@peartube/get-video-url'],
  ['@peartube/get-video-data', 9],
  [9, '@peartube/get-video-data'],
  ['@peartube/upload-video', 10],
  [10, '@peartube/upload-video'],
  ['@peartube/download-video', 11],
  [11, '@peartube/download-video'],
  ['@peartube/delete-video', 12],
  [12, '@peartube/delete-video'],
  ['@peartube/subscribe-channel', 13],
  [13, '@peartube/subscribe-channel'],
  ['@peartube/unsubscribe-channel', 14],
  [14, '@peartube/unsubscribe-channel'],
  ['@peartube/get-subscriptions', 15],
  [15, '@peartube/get-subscriptions'],
  ['@peartube/join-channel', 16],
  [16, '@peartube/join-channel'],
  ['@peartube/get-public-feed', 17],
  [17, '@peartube/get-public-feed'],
  ['@peartube/refresh-feed', 18],
  [18, '@peartube/refresh-feed'],
  ['@peartube/submit-to-feed', 19],
  [19, '@peartube/submit-to-feed'],
  ['@peartube/unpublish-from-feed', 20],
  [20, '@peartube/unpublish-from-feed'],
  ['@peartube/is-channel-published', 21],
  [21, '@peartube/is-channel-published'],
  ['@peartube/hide-channel', 22],
  [22, '@peartube/hide-channel'],
  ['@peartube/get-channel-meta', 23],
  [23, '@peartube/get-channel-meta'],
  ['@peartube/get-swarm-status', 24],
  [24, '@peartube/get-swarm-status'],
  ['@peartube/create-device-invite', 25],
  [25, '@peartube/create-device-invite'],
  ['@peartube/pair-device', 26],
  [26, '@peartube/pair-device'],
  ['@peartube/list-devices', 27],
  [27, '@peartube/list-devices'],
  ['@peartube/retry-sync-channel', 28],
  [28, '@peartube/retry-sync-channel'],
  ['@peartube/search-videos', 29],
  [29, '@peartube/search-videos'],
  ['@peartube/index-video-vectors', 30],
  [30, '@peartube/index-video-vectors'],
  ['@peartube/add-comment', 31],
  [31, '@peartube/add-comment'],
  ['@peartube/list-comments', 32],
  [32, '@peartube/list-comments'],
  ['@peartube/hide-comment', 33],
  [33, '@peartube/hide-comment'],
  ['@peartube/remove-comment', 34],
  [34, '@peartube/remove-comment'],
  ['@peartube/add-reaction', 35],
  [35, '@peartube/add-reaction'],
  ['@peartube/remove-reaction', 36],
  [36, '@peartube/remove-reaction'],
  ['@peartube/get-reactions', 37],
  [37, '@peartube/get-reactions'],
  ['@peartube/log-watch-event', 38],
  [38, '@peartube/log-watch-event'],
  ['@peartube/get-recommendations', 39],
  [39, '@peartube/get-recommendations'],
  ['@peartube/get-video-recommendations', 40],
  [40, '@peartube/get-video-recommendations'],
  ['@peartube/prefetch-video', 41],
  [41, '@peartube/prefetch-video'],
  ['@peartube/get-video-stats', 42],
  [42, '@peartube/get-video-stats'],
  ['@peartube/get-seeding-status', 43],
  [43, '@peartube/get-seeding-status'],
  ['@peartube/set-seeding-config', 44],
  [44, '@peartube/set-seeding-config'],
  ['@peartube/pin-channel', 45],
  [45, '@peartube/pin-channel'],
  ['@peartube/unpin-channel', 46],
  [46, '@peartube/unpin-channel'],
  ['@peartube/get-pinned-channels', 47],
  [47, '@peartube/get-pinned-channels'],
  ['@peartube/get-storage-stats', 48],
  [48, '@peartube/get-storage-stats'],
  ['@peartube/set-storage-limit', 49],
  [49, '@peartube/set-storage-limit'],
  ['@peartube/clear-cache', 50],
  [50, '@peartube/clear-cache'],
  ['@peartube/get-video-thumbnail', 51],
  [51, '@peartube/get-video-thumbnail'],
  ['@peartube/get-video-metadata', 52],
  [52, '@peartube/get-video-metadata'],
  ['@peartube/set-video-thumbnail', 53],
  [53, '@peartube/set-video-thumbnail'],
  ['@peartube/set-video-thumbnail-from-file', 54],
  [54, '@peartube/set-video-thumbnail-from-file'],
  ['@peartube/get-status', 55],
  [55, '@peartube/get-status'],
  ['@peartube/pick-video-file', 56],
  [56, '@peartube/pick-video-file'],
  ['@peartube/pick-image-file', 57],
  [57, '@peartube/pick-image-file'],
  ['@peartube/get-blob-server-port', 58],
  [58, '@peartube/get-blob-server-port'],
  ['@peartube/event-ready', 59],
  [59, '@peartube/event-ready'],
  ['@peartube/event-error', 60],
  [60, '@peartube/event-error'],
  ['@peartube/event-upload-progress', 61],
  [61, '@peartube/event-upload-progress'],
  ['@peartube/event-feed-update', 62],
  [62, '@peartube/event-feed-update'],
  ['@peartube/event-log', 63],
  [63, '@peartube/event-log'],
  ['@peartube/event-video-stats', 64],
  [64, '@peartube/event-video-stats']
])

class HRPC {
  constructor(stream) {
    this._stream = stream
    this._handlers = []
    this._requestEncodings = new Map([
      ['@peartube/create-identity', getEncoding('@peartube/create-identity-request')],
      ['@peartube/get-identity', getEncoding('@peartube/get-identity-request')],
      ['@peartube/get-identities', getEncoding('@peartube/get-identities-request')],
      ['@peartube/set-active-identity', getEncoding('@peartube/set-active-identity-request')],
      ['@peartube/recover-identity', getEncoding('@peartube/recover-identity-request')],
      ['@peartube/get-channel', getEncoding('@peartube/get-channel-request')],
      ['@peartube/update-channel', getEncoding('@peartube/update-channel-request')],
      ['@peartube/list-videos', getEncoding('@peartube/list-videos-request')],
      ['@peartube/get-video-url', getEncoding('@peartube/get-video-url-request')],
      ['@peartube/get-video-data', getEncoding('@peartube/get-video-data-request')],
      ['@peartube/upload-video', getEncoding('@peartube/upload-video-request')],
      ['@peartube/download-video', getEncoding('@peartube/download-video-request')],
      ['@peartube/delete-video', getEncoding('@peartube/delete-video-request')],
      ['@peartube/subscribe-channel', getEncoding('@peartube/subscribe-channel-request')],
      ['@peartube/unsubscribe-channel', getEncoding('@peartube/unsubscribe-channel-request')],
      ['@peartube/get-subscriptions', getEncoding('@peartube/get-subscriptions-request')],
      ['@peartube/join-channel', getEncoding('@peartube/join-channel-request')],
      ['@peartube/get-public-feed', getEncoding('@peartube/get-public-feed-request')],
      ['@peartube/refresh-feed', getEncoding('@peartube/refresh-feed-request')],
      ['@peartube/submit-to-feed', getEncoding('@peartube/submit-to-feed-request')],
      ['@peartube/unpublish-from-feed', getEncoding('@peartube/unpublish-from-feed-request')],
      ['@peartube/is-channel-published', getEncoding('@peartube/is-channel-published-request')],
      ['@peartube/hide-channel', getEncoding('@peartube/hide-channel-request')],
      ['@peartube/get-channel-meta', getEncoding('@peartube/get-channel-meta-request')],
      ['@peartube/get-swarm-status', getEncoding('@peartube/get-swarm-status-request')],
      ['@peartube/create-device-invite', getEncoding('@peartube/create-device-invite-request')],
      ['@peartube/pair-device', getEncoding('@peartube/pair-device-request')],
      ['@peartube/list-devices', getEncoding('@peartube/list-devices-request')],
      ['@peartube/retry-sync-channel', getEncoding('@peartube/retry-sync-channel-request')],
      ['@peartube/search-videos', getEncoding('@peartube/search-videos-request')],
      ['@peartube/index-video-vectors', getEncoding('@peartube/index-video-vectors-request')],
      ['@peartube/add-comment', getEncoding('@peartube/add-comment-request')],
      ['@peartube/list-comments', getEncoding('@peartube/list-comments-request')],
      ['@peartube/hide-comment', getEncoding('@peartube/hide-comment-request')],
      ['@peartube/remove-comment', getEncoding('@peartube/remove-comment-request')],
      ['@peartube/add-reaction', getEncoding('@peartube/add-reaction-request')],
      ['@peartube/remove-reaction', getEncoding('@peartube/remove-reaction-request')],
      ['@peartube/get-reactions', getEncoding('@peartube/get-reactions-request')],
      ['@peartube/log-watch-event', getEncoding('@peartube/log-watch-event-request')],
      ['@peartube/get-recommendations', getEncoding('@peartube/get-recommendations-request')],
      ['@peartube/get-video-recommendations', getEncoding('@peartube/get-video-recommendations-request')],
      ['@peartube/prefetch-video', getEncoding('@peartube/prefetch-video-request')],
      ['@peartube/get-video-stats', getEncoding('@peartube/get-video-stats-request')],
      ['@peartube/get-seeding-status', getEncoding('@peartube/get-seeding-status-request')],
      ['@peartube/set-seeding-config', getEncoding('@peartube/set-seeding-config-request')],
      ['@peartube/pin-channel', getEncoding('@peartube/pin-channel-request')],
      ['@peartube/unpin-channel', getEncoding('@peartube/unpin-channel-request')],
      ['@peartube/get-pinned-channels', getEncoding('@peartube/get-pinned-channels-request')],
      ['@peartube/get-storage-stats', getEncoding('@peartube/get-storage-stats-request')],
      ['@peartube/set-storage-limit', getEncoding('@peartube/set-storage-limit-request')],
      ['@peartube/clear-cache', getEncoding('@peartube/clear-cache-request')],
      ['@peartube/get-video-thumbnail', getEncoding('@peartube/get-video-thumbnail-request')],
      ['@peartube/get-video-metadata', getEncoding('@peartube/get-video-metadata-request')],
      ['@peartube/set-video-thumbnail', getEncoding('@peartube/set-video-thumbnail-request')],
      ['@peartube/set-video-thumbnail-from-file', getEncoding('@peartube/set-video-thumbnail-from-file-request')],
      ['@peartube/get-status', getEncoding('@peartube/get-status-request')],
      ['@peartube/pick-video-file', getEncoding('@peartube/pick-video-file-request')],
      ['@peartube/pick-image-file', getEncoding('@peartube/pick-image-file-request')],
      ['@peartube/get-blob-server-port', getEncoding('@peartube/get-blob-server-port-request')],
      ['@peartube/event-ready', getEncoding('@peartube/event-ready')],
      ['@peartube/event-error', getEncoding('@peartube/event-error')],
      ['@peartube/event-upload-progress', getEncoding('@peartube/event-upload-progress')],
      ['@peartube/event-feed-update', getEncoding('@peartube/event-feed-update')],
      ['@peartube/event-log', getEncoding('@peartube/event-log')],
      ['@peartube/event-video-stats', getEncoding('@peartube/event-video-stats')]
    ])
    this._responseEncodings = new Map([
      ['@peartube/create-identity', getEncoding('@peartube/create-identity-response')],
      ['@peartube/get-identity', getEncoding('@peartube/get-identity-response')],
      ['@peartube/get-identities', getEncoding('@peartube/get-identities-response')],
      ['@peartube/set-active-identity', getEncoding('@peartube/set-active-identity-response')],
      ['@peartube/recover-identity', getEncoding('@peartube/recover-identity-response')],
      ['@peartube/get-channel', getEncoding('@peartube/get-channel-response')],
      ['@peartube/update-channel', getEncoding('@peartube/update-channel-response')],
      ['@peartube/list-videos', getEncoding('@peartube/list-videos-response')],
      ['@peartube/get-video-url', getEncoding('@peartube/get-video-url-response')],
      ['@peartube/get-video-data', getEncoding('@peartube/get-video-data-response')],
      ['@peartube/upload-video', getEncoding('@peartube/upload-video-response')],
      ['@peartube/download-video', getEncoding('@peartube/download-video-response')],
      ['@peartube/delete-video', getEncoding('@peartube/delete-video-response')],
      ['@peartube/subscribe-channel', getEncoding('@peartube/subscribe-channel-response')],
      ['@peartube/unsubscribe-channel', getEncoding('@peartube/unsubscribe-channel-response')],
      ['@peartube/get-subscriptions', getEncoding('@peartube/get-subscriptions-response')],
      ['@peartube/join-channel', getEncoding('@peartube/join-channel-response')],
      ['@peartube/get-public-feed', getEncoding('@peartube/get-public-feed-response')],
      ['@peartube/refresh-feed', getEncoding('@peartube/refresh-feed-response')],
      ['@peartube/submit-to-feed', getEncoding('@peartube/submit-to-feed-response')],
      ['@peartube/unpublish-from-feed', getEncoding('@peartube/unpublish-from-feed-response')],
      ['@peartube/is-channel-published', getEncoding('@peartube/is-channel-published-response')],
      ['@peartube/hide-channel', getEncoding('@peartube/hide-channel-response')],
      ['@peartube/get-channel-meta', getEncoding('@peartube/get-channel-meta-response')],
      ['@peartube/get-swarm-status', getEncoding('@peartube/get-swarm-status-response')],
      ['@peartube/create-device-invite', getEncoding('@peartube/create-device-invite-response')],
      ['@peartube/pair-device', getEncoding('@peartube/pair-device-response')],
      ['@peartube/list-devices', getEncoding('@peartube/list-devices-response')],
      ['@peartube/retry-sync-channel', getEncoding('@peartube/retry-sync-channel-response')],
      ['@peartube/search-videos', getEncoding('@peartube/search-videos-response')],
      ['@peartube/index-video-vectors', getEncoding('@peartube/index-video-vectors-response')],
      ['@peartube/add-comment', getEncoding('@peartube/add-comment-response')],
      ['@peartube/list-comments', getEncoding('@peartube/list-comments-response')],
      ['@peartube/hide-comment', getEncoding('@peartube/hide-comment-response')],
      ['@peartube/remove-comment', getEncoding('@peartube/remove-comment-response')],
      ['@peartube/add-reaction', getEncoding('@peartube/add-reaction-response')],
      ['@peartube/remove-reaction', getEncoding('@peartube/remove-reaction-response')],
      ['@peartube/get-reactions', getEncoding('@peartube/get-reactions-response')],
      ['@peartube/log-watch-event', getEncoding('@peartube/log-watch-event-response')],
      ['@peartube/get-recommendations', getEncoding('@peartube/get-recommendations-response')],
      ['@peartube/get-video-recommendations', getEncoding('@peartube/get-video-recommendations-response')],
      ['@peartube/prefetch-video', getEncoding('@peartube/prefetch-video-response')],
      ['@peartube/get-video-stats', getEncoding('@peartube/get-video-stats-response')],
      ['@peartube/get-seeding-status', getEncoding('@peartube/get-seeding-status-response')],
      ['@peartube/set-seeding-config', getEncoding('@peartube/set-seeding-config-response')],
      ['@peartube/pin-channel', getEncoding('@peartube/pin-channel-response')],
      ['@peartube/unpin-channel', getEncoding('@peartube/unpin-channel-response')],
      ['@peartube/get-pinned-channels', getEncoding('@peartube/get-pinned-channels-response')],
      ['@peartube/get-storage-stats', getEncoding('@peartube/get-storage-stats-response')],
      ['@peartube/set-storage-limit', getEncoding('@peartube/set-storage-limit-response')],
      ['@peartube/clear-cache', getEncoding('@peartube/clear-cache-response')],
      ['@peartube/get-video-thumbnail', getEncoding('@peartube/get-video-thumbnail-response')],
      ['@peartube/get-video-metadata', getEncoding('@peartube/get-video-metadata-response')],
      ['@peartube/set-video-thumbnail', getEncoding('@peartube/set-video-thumbnail-response')],
      ['@peartube/set-video-thumbnail-from-file', getEncoding('@peartube/set-video-thumbnail-from-file-response')],
      ['@peartube/get-status', getEncoding('@peartube/get-status-response')],
      ['@peartube/pick-video-file', getEncoding('@peartube/pick-video-file-response')],
      ['@peartube/pick-image-file', getEncoding('@peartube/pick-image-file-response')],
      ['@peartube/get-blob-server-port', getEncoding('@peartube/get-blob-server-port-response')]
    ])
    this._rpc = new RPC(stream, async (req) => {
      const command = methods.get(req.command)
      if (!command) {
        console.error('[HRPC] Unknown command:', req.command)
        return
      }
      const handler = this._handlers[command]
      if (typeof handler !== 'function') {
        console.error('[HRPC] Missing handler:', command, 'raw:', req.command)
        return
      }
      const responseEncoding = this._responseEncodings.get(command)
      const requestEncoding = this._requestEncodings.get(command)
      if (this._requestIsSend(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        await handler(request)
        return
      }
      if (!this._requestIsStream(command) && !this._responseIsStream(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        const response = await handler(request)
        req.reply(c.encode(responseEncoding, response))
      }
      if (!this._requestIsStream(command) && this._responseIsStream(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        const responseStream = new RPCStream(
          null,
          null,
          req.createResponseStream(),
          responseEncoding
        )
        responseStream.data = request
        await handler(responseStream)
      }
      if (this._requestIsStream(command) && !this._responseIsStream(command)) {
        const requestStream = new RPCRequestStream(
          req,
          responseEncoding,
          req.createRequestStream(),
          requestEncoding
        )
        const response = await handler(requestStream)
        req.reply(c.encode(responseEncoding, response))
      }
      if (this._requestIsStream(command) && this._responseIsStream(command)) {
        const requestStream = new RPCRequestStream(
          req,
          responseEncoding,
          req.createRequestStream(),
          requestEncoding,
          req.createResponseStream(),
          responseEncoding
        )
        await handler(requestStream)
      }
    })
  }

  async _call(name, args) {
    const requestEncoding = this._requestEncodings.get(name)
    const responseEncoding = this._responseEncodings.get(name)
    const request = this._rpc.request(methods.get(name))
    const encoded = c.encode(requestEncoding, args)
    request.send(encoded)
    return c.decode(responseEncoding, await request.reply())
  }

  _callSync(name, args) {
    const requestEncoding = this._requestEncodings.get(name)
    const responseEncoding = this._responseEncodings.get(name)
    const request = this._rpc.request(methods.get(name))
    if (this._requestIsSend(name)) {
      const encoded = c.encode(requestEncoding, args)
      request.send(encoded)
    }
    if (!this._requestIsStream(name) && this._responseIsStream(name)) {
      const encoded = c.encode(requestEncoding, args)
      request.send(encoded)
      return new RPCStream(request.createResponseStream(), responseEncoding)
    }
    if (this._requestIsStream(name) && !this._responseIsStream(name)) {
      return new RPCRequestStream(
        request,
        responseEncoding,
        null,
        null,
        request.createRequestStream(),
        requestEncoding
      )
    }
    if (this._requestIsStream(name) && this._responseIsStream(name)) {
      return new RPCRequestStream(
        request,
        responseEncoding,
        request.createResponseStream(),
        responseEncoding,
        request.createRequestStream(),
        requestEncoding
      )
    }
  }

  async createIdentity(args) {
    return this._call('@peartube/create-identity', args)
  }

  async getIdentity(args) {
    return this._call('@peartube/get-identity', args)
  }

  async getIdentities(args) {
    return this._call('@peartube/get-identities', args)
  }

  async setActiveIdentity(args) {
    return this._call('@peartube/set-active-identity', args)
  }

  async recoverIdentity(args) {
    return this._call('@peartube/recover-identity', args)
  }

  async getChannel(args) {
    return this._call('@peartube/get-channel', args)
  }

  async updateChannel(args) {
    return this._call('@peartube/update-channel', args)
  }

  async listVideos(args) {
    return this._call('@peartube/list-videos', args)
  }

  async getVideoUrl(args) {
    return this._call('@peartube/get-video-url', args)
  }

  async getVideoData(args) {
    return this._call('@peartube/get-video-data', args)
  }

  async uploadVideo(args) {
    return this._call('@peartube/upload-video', args)
  }

  async downloadVideo(args) {
    return this._call('@peartube/download-video', args)
  }

  async deleteVideo(args) {
    return this._call('@peartube/delete-video', args)
  }

  async subscribeChannel(args) {
    return this._call('@peartube/subscribe-channel', args)
  }

  async unsubscribeChannel(args) {
    return this._call('@peartube/unsubscribe-channel', args)
  }

  async getSubscriptions(args) {
    return this._call('@peartube/get-subscriptions', args)
  }

  async joinChannel(args) {
    return this._call('@peartube/join-channel', args)
  }

  async getPublicFeed(args) {
    return this._call('@peartube/get-public-feed', args)
  }

  async refreshFeed(args) {
    return this._call('@peartube/refresh-feed', args)
  }

  async submitToFeed(args) {
    return this._call('@peartube/submit-to-feed', args)
  }

  async unpublishFromFeed(args) {
    return this._call('@peartube/unpublish-from-feed', args)
  }

  async isChannelPublished(args) {
    return this._call('@peartube/is-channel-published', args)
  }

  async hideChannel(args) {
    return this._call('@peartube/hide-channel', args)
  }

  async getChannelMeta(args) {
    return this._call('@peartube/get-channel-meta', args)
  }

  async getSwarmStatus(args) {
    return this._call('@peartube/get-swarm-status', args)
  }

  async createDeviceInvite(args) {
    return this._call('@peartube/create-device-invite', args)
  }

  async pairDevice(args) {
    return this._call('@peartube/pair-device', args)
  }

  async listDevices(args) {
    return this._call('@peartube/list-devices', args)
  }

  async retrySyncChannel(args) {
    return this._call('@peartube/retry-sync-channel', args)
  }

  async searchVideos(args) {
    return this._call('@peartube/search-videos', args)
  }

  async indexVideoVectors(args) {
    return this._call('@peartube/index-video-vectors', args)
  }

  async addComment(args) {
    return this._call('@peartube/add-comment', args)
  }

  async listComments(args) {
    return this._call('@peartube/list-comments', args)
  }

  async hideComment(args) {
    return this._call('@peartube/hide-comment', args)
  }

  async removeComment(args) {
    return this._call('@peartube/remove-comment', args)
  }

  async addReaction(args) {
    return this._call('@peartube/add-reaction', args)
  }

  async removeReaction(args) {
    return this._call('@peartube/remove-reaction', args)
  }

  async getReactions(args) {
    return this._call('@peartube/get-reactions', args)
  }

  async logWatchEvent(args) {
    return this._call('@peartube/log-watch-event', args)
  }

  async getRecommendations(args) {
    return this._call('@peartube/get-recommendations', args)
  }

  async getVideoRecommendations(args) {
    return this._call('@peartube/get-video-recommendations', args)
  }

  async prefetchVideo(args) {
    return this._call('@peartube/prefetch-video', args)
  }

  async getVideoStats(args) {
    return this._call('@peartube/get-video-stats', args)
  }

  async getSeedingStatus(args) {
    return this._call('@peartube/get-seeding-status', args)
  }

  async setSeedingConfig(args) {
    return this._call('@peartube/set-seeding-config', args)
  }

  async pinChannel(args) {
    return this._call('@peartube/pin-channel', args)
  }

  async unpinChannel(args) {
    return this._call('@peartube/unpin-channel', args)
  }

  async getPinnedChannels(args) {
    return this._call('@peartube/get-pinned-channels', args)
  }

  async getStorageStats(args) {
    return this._call('@peartube/get-storage-stats', args)
  }

  async setStorageLimit(args) {
    return this._call('@peartube/set-storage-limit', args)
  }

  async clearCache(args) {
    return this._call('@peartube/clear-cache', args)
  }

  async getVideoThumbnail(args) {
    return this._call('@peartube/get-video-thumbnail', args)
  }

  async getVideoMetadata(args) {
    return this._call('@peartube/get-video-metadata', args)
  }

  async setVideoThumbnail(args) {
    return this._call('@peartube/set-video-thumbnail', args)
  }

  async setVideoThumbnailFromFile(args) {
    return this._call('@peartube/set-video-thumbnail-from-file', args)
  }

  async getStatus(args) {
    return this._call('@peartube/get-status', args)
  }

  async pickVideoFile(args) {
    return this._call('@peartube/pick-video-file', args)
  }

  async pickImageFile(args) {
    return this._call('@peartube/pick-image-file', args)
  }

  async getBlobServerPort(args) {
    return this._call('@peartube/get-blob-server-port', args)
  }

  eventReady(args) {
    return this._callSync('@peartube/event-ready', args)
  }

  eventError(args) {
    return this._callSync('@peartube/event-error', args)
  }

  eventUploadProgress(args) {
    return this._callSync('@peartube/event-upload-progress', args)
  }

  eventFeedUpdate(args) {
    return this._callSync('@peartube/event-feed-update', args)
  }

  eventLog(args) {
    return this._callSync('@peartube/event-log', args)
  }

  eventVideoStats(args) {
    return this._callSync('@peartube/event-video-stats', args)
  }

  onCreateIdentity(responseFn) {
    this._handlers['@peartube/create-identity'] = responseFn
  }

  onGetIdentity(responseFn) {
    this._handlers['@peartube/get-identity'] = responseFn
  }

  onGetIdentities(responseFn) {
    this._handlers['@peartube/get-identities'] = responseFn
  }

  onSetActiveIdentity(responseFn) {
    this._handlers['@peartube/set-active-identity'] = responseFn
  }

  onRecoverIdentity(responseFn) {
    this._handlers['@peartube/recover-identity'] = responseFn
  }

  onGetChannel(responseFn) {
    this._handlers['@peartube/get-channel'] = responseFn
  }

  onUpdateChannel(responseFn) {
    this._handlers['@peartube/update-channel'] = responseFn
  }

  onListVideos(responseFn) {
    this._handlers['@peartube/list-videos'] = responseFn
  }

  onGetVideoUrl(responseFn) {
    this._handlers['@peartube/get-video-url'] = responseFn
  }

  onGetVideoData(responseFn) {
    this._handlers['@peartube/get-video-data'] = responseFn
  }

  onUploadVideo(responseFn) {
    this._handlers['@peartube/upload-video'] = responseFn
  }

  onDownloadVideo(responseFn) {
    this._handlers['@peartube/download-video'] = responseFn
  }

  onDeleteVideo(responseFn) {
    this._handlers['@peartube/delete-video'] = responseFn
  }

  onSubscribeChannel(responseFn) {
    this._handlers['@peartube/subscribe-channel'] = responseFn
  }

  onUnsubscribeChannel(responseFn) {
    this._handlers['@peartube/unsubscribe-channel'] = responseFn
  }

  onGetSubscriptions(responseFn) {
    this._handlers['@peartube/get-subscriptions'] = responseFn
  }

  onJoinChannel(responseFn) {
    this._handlers['@peartube/join-channel'] = responseFn
  }

  onGetPublicFeed(responseFn) {
    this._handlers['@peartube/get-public-feed'] = responseFn
  }

  onRefreshFeed(responseFn) {
    this._handlers['@peartube/refresh-feed'] = responseFn
  }

  onSubmitToFeed(responseFn) {
    this._handlers['@peartube/submit-to-feed'] = responseFn
  }

  onUnpublishFromFeed(responseFn) {
    this._handlers['@peartube/unpublish-from-feed'] = responseFn
  }

  onIsChannelPublished(responseFn) {
    this._handlers['@peartube/is-channel-published'] = responseFn
  }

  onHideChannel(responseFn) {
    this._handlers['@peartube/hide-channel'] = responseFn
  }

  onGetChannelMeta(responseFn) {
    this._handlers['@peartube/get-channel-meta'] = responseFn
  }

  onGetSwarmStatus(responseFn) {
    this._handlers['@peartube/get-swarm-status'] = responseFn
  }

  onCreateDeviceInvite(responseFn) {
    this._handlers['@peartube/create-device-invite'] = responseFn
  }

  onPairDevice(responseFn) {
    this._handlers['@peartube/pair-device'] = responseFn
  }

  onListDevices(responseFn) {
    this._handlers['@peartube/list-devices'] = responseFn
  }

  onRetrySyncChannel(responseFn) {
    this._handlers['@peartube/retry-sync-channel'] = responseFn
  }

  onSearchVideos(responseFn) {
    this._handlers['@peartube/search-videos'] = responseFn
  }

  onIndexVideoVectors(responseFn) {
    this._handlers['@peartube/index-video-vectors'] = responseFn
  }

  onAddComment(responseFn) {
    this._handlers['@peartube/add-comment'] = responseFn
  }

  onListComments(responseFn) {
    this._handlers['@peartube/list-comments'] = responseFn
  }

  onHideComment(responseFn) {
    this._handlers['@peartube/hide-comment'] = responseFn
  }

  onRemoveComment(responseFn) {
    this._handlers['@peartube/remove-comment'] = responseFn
  }

  onAddReaction(responseFn) {
    this._handlers['@peartube/add-reaction'] = responseFn
  }

  onRemoveReaction(responseFn) {
    this._handlers['@peartube/remove-reaction'] = responseFn
  }

  onGetReactions(responseFn) {
    this._handlers['@peartube/get-reactions'] = responseFn
  }

  onLogWatchEvent(responseFn) {
    this._handlers['@peartube/log-watch-event'] = responseFn
  }

  onGetRecommendations(responseFn) {
    this._handlers['@peartube/get-recommendations'] = responseFn
  }

  onGetVideoRecommendations(responseFn) {
    this._handlers['@peartube/get-video-recommendations'] = responseFn
  }

  onPrefetchVideo(responseFn) {
    this._handlers['@peartube/prefetch-video'] = responseFn
  }

  onGetVideoStats(responseFn) {
    this._handlers['@peartube/get-video-stats'] = responseFn
  }

  onGetSeedingStatus(responseFn) {
    this._handlers['@peartube/get-seeding-status'] = responseFn
  }

  onSetSeedingConfig(responseFn) {
    this._handlers['@peartube/set-seeding-config'] = responseFn
  }

  onPinChannel(responseFn) {
    this._handlers['@peartube/pin-channel'] = responseFn
  }

  onUnpinChannel(responseFn) {
    this._handlers['@peartube/unpin-channel'] = responseFn
  }

  onGetPinnedChannels(responseFn) {
    this._handlers['@peartube/get-pinned-channels'] = responseFn
  }

  onGetStorageStats(responseFn) {
    this._handlers['@peartube/get-storage-stats'] = responseFn
  }

  onSetStorageLimit(responseFn) {
    this._handlers['@peartube/set-storage-limit'] = responseFn
  }

  onClearCache(responseFn) {
    this._handlers['@peartube/clear-cache'] = responseFn
  }

  onGetVideoThumbnail(responseFn) {
    this._handlers['@peartube/get-video-thumbnail'] = responseFn
  }

  onGetVideoMetadata(responseFn) {
    this._handlers['@peartube/get-video-metadata'] = responseFn
  }

  onSetVideoThumbnail(responseFn) {
    this._handlers['@peartube/set-video-thumbnail'] = responseFn
  }

  onSetVideoThumbnailFromFile(responseFn) {
    this._handlers['@peartube/set-video-thumbnail-from-file'] = responseFn
  }

  onGetStatus(responseFn) {
    this._handlers['@peartube/get-status'] = responseFn
  }

  onPickVideoFile(responseFn) {
    this._handlers['@peartube/pick-video-file'] = responseFn
  }

  onPickImageFile(responseFn) {
    this._handlers['@peartube/pick-image-file'] = responseFn
  }

  onGetBlobServerPort(responseFn) {
    this._handlers['@peartube/get-blob-server-port'] = responseFn
  }

  onEventReady(responseFn) {
    this._handlers['@peartube/event-ready'] = responseFn
  }

  onEventError(responseFn) {
    this._handlers['@peartube/event-error'] = responseFn
  }

  onEventUploadProgress(responseFn) {
    this._handlers['@peartube/event-upload-progress'] = responseFn
  }

  onEventFeedUpdate(responseFn) {
    this._handlers['@peartube/event-feed-update'] = responseFn
  }

  onEventLog(responseFn) {
    this._handlers['@peartube/event-log'] = responseFn
  }

  onEventVideoStats(responseFn) {
    this._handlers['@peartube/event-video-stats'] = responseFn
  }

  _requestIsStream(command) {
    return [
    ].includes(command)
  }

  _responseIsStream(command) {
    return [
    ].includes(command)
  }

  // prettier-ignore-start
  _requestIsSend(command) {
    return [
      // prettier-ignore
      '@peartube/event-ready',
      '@peartube/event-error',
      '@peartube/event-upload-progress',
      '@peartube/event-feed-update',
      '@peartube/event-log',
      '@peartube/event-video-stats'
    ].includes(command)
  }
}

module.exports = HRPC
