// This file is autogenerated by the hyperschema compiler
// Schema Version: 2
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

import { c } from 'hyperschema/runtime'

const VERSION = 2

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @peartubePublic/metadata
const encoding0 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    state.end++ // flags are fixed size

    if (m.name) c.string.preencode(state, m.name)
    if (m.description) c.string.preencode(state, m.description)
    if (m.avatar) c.string.preencode(state, m.avatar)
    if (m.publicBeeKey) c.string.preencode(state, m.publicBeeKey)
    if (m.commentsDbKey) c.string.preencode(state, m.commentsDbKey)
    if (m.createdAt) c.uint64.preencode(state, m.createdAt)
    if (m.createdBy) c.string.preencode(state, m.createdBy)
    if (m.updatedAt) c.uint64.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags =
      (m.name ? 1 : 0) |
      (m.description ? 2 : 0) |
      (m.avatar ? 4 : 0) |
      (m.publicBeeKey ? 8 : 0) |
      (m.commentsDbKey ? 16 : 0) |
      (m.createdAt ? 32 : 0) |
      (m.createdBy ? 64 : 0) |
      (m.updatedAt ? 128 : 0)

    c.string.encode(state, m.key)
    c.uint8.encode(state, flags)

    if (m.name) c.string.encode(state, m.name)
    if (m.description) c.string.encode(state, m.description)
    if (m.avatar) c.string.encode(state, m.avatar)
    if (m.publicBeeKey) c.string.encode(state, m.publicBeeKey)
    if (m.commentsDbKey) c.string.encode(state, m.commentsDbKey)
    if (m.createdAt) c.uint64.encode(state, m.createdAt)
    if (m.createdBy) c.string.encode(state, m.createdBy)
    if (m.updatedAt) c.uint64.encode(state, m.updatedAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint8.decode(state)

    return {
      key: r0,
      name: (flags & 1) !== 0 ? c.string.decode(state) : null,
      description: (flags & 2) !== 0 ? c.string.decode(state) : null,
      avatar: (flags & 4) !== 0 ? c.string.decode(state) : null,
      publicBeeKey: (flags & 8) !== 0 ? c.string.decode(state) : null,
      commentsDbKey: (flags & 16) !== 0 ? c.string.decode(state) : null,
      createdAt: (flags & 32) !== 0 ? c.uint64.decode(state) : 0,
      createdBy: (flags & 64) !== 0 ? c.string.decode(state) : null,
      updatedAt: (flags & 128) !== 0 ? c.uint64.decode(state) : 0
    }
  }
}

// @peartubePublic/video
const encoding1 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    state.end += 3 // flags are fixed size

    if (m.title) c.string.preencode(state, m.title)
    if (m.description) c.string.preencode(state, m.description)
    if (m.path) c.string.preencode(state, m.path)
    if (m.duration) c.uint64.preencode(state, m.duration)
    if (m.thumbnail) c.string.preencode(state, m.thumbnail)
    if (m.thumbnailBlobId) c.string.preencode(state, m.thumbnailBlobId)
    if (m.thumbnailBlobsCoreKey) c.string.preencode(state, m.thumbnailBlobsCoreKey)
    if (m.thumbnailMimeType) c.string.preencode(state, m.thumbnailMimeType)
    if (m.blobId) c.string.preencode(state, m.blobId)
    if (m.blobsCoreKey) c.string.preencode(state, m.blobsCoreKey)
    if (m.blobDriveKey) c.string.preencode(state, m.blobDriveKey)
    if (m.mimeType) c.string.preencode(state, m.mimeType)
    if (m.size) c.uint64.preencode(state, m.size)
    if (m.category) c.string.preencode(state, m.category)
    if (m.views) c.uint64.preencode(state, m.views)
    if (m.uploadedAt) c.uint64.preencode(state, m.uploadedAt)
    if (m.uploadedBy) c.string.preencode(state, m.uploadedBy)
    if (m.updatedAt) c.uint64.preencode(state, m.updatedAt)
    if (m.updatedBy) c.string.preencode(state, m.updatedBy)
    if (m.syncedAt) c.uint64.preencode(state, m.syncedAt)
  },
  encode(state, m) {
    const flags =
      (m.title ? 1 : 0) |
      (m.description ? 2 : 0) |
      (m.path ? 4 : 0) |
      (m.duration ? 8 : 0) |
      (m.thumbnail ? 16 : 0) |
      (m.thumbnailBlobId ? 32 : 0) |
      (m.thumbnailBlobsCoreKey ? 64 : 0) |
      (m.thumbnailMimeType ? 128 : 0) |
      (m.blobId ? 256 : 0) |
      (m.blobsCoreKey ? 512 : 0) |
      (m.blobDriveKey ? 1024 : 0) |
      (m.mimeType ? 2048 : 0) |
      (m.size ? 4096 : 0) |
      (m.category ? 8192 : 0) |
      (m.views ? 16384 : 0) |
      (m.uploadedAt ? 32768 : 0) |
      (m.uploadedBy ? 65536 : 0) |
      (m.updatedAt ? 131072 : 0) |
      (m.updatedBy ? 262144 : 0) |
      (m.syncedAt ? 524288 : 0)

    c.string.encode(state, m.id)
    c.uint24.encode(state, flags)

    if (m.title) c.string.encode(state, m.title)
    if (m.description) c.string.encode(state, m.description)
    if (m.path) c.string.encode(state, m.path)
    if (m.duration) c.uint64.encode(state, m.duration)
    if (m.thumbnail) c.string.encode(state, m.thumbnail)
    if (m.thumbnailBlobId) c.string.encode(state, m.thumbnailBlobId)
    if (m.thumbnailBlobsCoreKey) c.string.encode(state, m.thumbnailBlobsCoreKey)
    if (m.thumbnailMimeType) c.string.encode(state, m.thumbnailMimeType)
    if (m.blobId) c.string.encode(state, m.blobId)
    if (m.blobsCoreKey) c.string.encode(state, m.blobsCoreKey)
    if (m.blobDriveKey) c.string.encode(state, m.blobDriveKey)
    if (m.mimeType) c.string.encode(state, m.mimeType)
    if (m.size) c.uint64.encode(state, m.size)
    if (m.category) c.string.encode(state, m.category)
    if (m.views) c.uint64.encode(state, m.views)
    if (m.uploadedAt) c.uint64.encode(state, m.uploadedAt)
    if (m.uploadedBy) c.string.encode(state, m.uploadedBy)
    if (m.updatedAt) c.uint64.encode(state, m.updatedAt)
    if (m.updatedBy) c.string.encode(state, m.updatedBy)
    if (m.syncedAt) c.uint64.encode(state, m.syncedAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint24.decode(state)

    return {
      id: r0,
      title: (flags & 1) !== 0 ? c.string.decode(state) : null,
      description: (flags & 2) !== 0 ? c.string.decode(state) : null,
      path: (flags & 4) !== 0 ? c.string.decode(state) : null,
      duration: (flags & 8) !== 0 ? c.uint64.decode(state) : 0,
      thumbnail: (flags & 16) !== 0 ? c.string.decode(state) : null,
      thumbnailBlobId: (flags & 32) !== 0 ? c.string.decode(state) : null,
      thumbnailBlobsCoreKey: (flags & 64) !== 0 ? c.string.decode(state) : null,
      thumbnailMimeType: (flags & 128) !== 0 ? c.string.decode(state) : null,
      blobId: (flags & 256) !== 0 ? c.string.decode(state) : null,
      blobsCoreKey: (flags & 512) !== 0 ? c.string.decode(state) : null,
      blobDriveKey: (flags & 1024) !== 0 ? c.string.decode(state) : null,
      mimeType: (flags & 2048) !== 0 ? c.string.decode(state) : null,
      size: (flags & 4096) !== 0 ? c.uint64.decode(state) : 0,
      category: (flags & 8192) !== 0 ? c.string.decode(state) : null,
      views: (flags & 16384) !== 0 ? c.uint64.decode(state) : 0,
      uploadedAt: (flags & 32768) !== 0 ? c.uint64.decode(state) : 0,
      uploadedBy: (flags & 65536) !== 0 ? c.string.decode(state) : null,
      updatedAt: (flags & 131072) !== 0 ? c.uint64.decode(state) : 0,
      updatedBy: (flags & 262144) !== 0 ? c.string.decode(state) : null,
      syncedAt: (flags & 524288) !== 0 ? c.uint64.decode(state) : 0
    }
  }
}

// @peartubePublic/videoSourceMetadata
const encoding2 = {
  preencode(state, m) {
    c.string.preencode(state, m.videoId)
    state.end += 2 // flags are fixed size

    if (version >= 2 && m.sourcePlatform) c.string.preencode(state, m.sourcePlatform)
    if (version >= 2 && m.sourcePlatformLabel) c.string.preencode(state, m.sourcePlatformLabel)
    if (version >= 2 && m.sourceUrl) c.string.preencode(state, m.sourceUrl)
    if (version >= 2 && m.sourceId) c.string.preencode(state, m.sourceId)
    if (version >= 2 && m.sourceCreatorName) c.string.preencode(state, m.sourceCreatorName)
    if (version >= 2 && m.sourceCreatorHandle) c.string.preencode(state, m.sourceCreatorHandle)
    if (version >= 2 && m.sourceCreatorUrl) c.string.preencode(state, m.sourceCreatorUrl)
    if (version >= 2 && m.sourcePublishedAt) c.uint64.preencode(state, m.sourcePublishedAt)
    if (version >= 2 && m.sourceViewCount) c.uint64.preencode(state, m.sourceViewCount)
    if (version >= 2 && m.sourceLikeCount) c.uint64.preencode(state, m.sourceLikeCount)
    if (version >= 2 && m.sourceCommentCount) c.uint64.preencode(state, m.sourceCommentCount)
    if (version >= 2 && m.sourceArchivedAt) c.uint64.preencode(state, m.sourceArchivedAt)
    if (version >= 2 && m.sourceRelayId) c.string.preencode(state, m.sourceRelayId)
    if (version >= 2 && m.sourceMetadataJson) c.string.preencode(state, m.sourceMetadataJson)
  },
  encode(state, m) {
    const flags =
      ((version >= 2 && m.sourcePlatform) ? 1 : 0) |
      ((version >= 2 && m.sourcePlatformLabel) ? 2 : 0) |
      ((version >= 2 && m.sourceUrl) ? 4 : 0) |
      ((version >= 2 && m.sourceId) ? 8 : 0) |
      ((version >= 2 && m.sourceCreatorName) ? 16 : 0) |
      ((version >= 2 && m.sourceCreatorHandle) ? 32 : 0) |
      ((version >= 2 && m.sourceCreatorUrl) ? 64 : 0) |
      ((version >= 2 && m.sourcePublishedAt) ? 128 : 0) |
      ((version >= 2 && m.sourceViewCount) ? 256 : 0) |
      ((version >= 2 && m.sourceLikeCount) ? 512 : 0) |
      ((version >= 2 && m.sourceCommentCount) ? 1024 : 0) |
      ((version >= 2 && m.sourceArchivedAt) ? 2048 : 0) |
      ((version >= 2 && m.sourceRelayId) ? 4096 : 0) |
      ((version >= 2 && m.sourceMetadataJson) ? 8192 : 0)

    c.string.encode(state, m.videoId)
    c.uint16.encode(state, flags)

    if (version >= 2 && m.sourcePlatform) c.string.encode(state, m.sourcePlatform)
    if (version >= 2 && m.sourcePlatformLabel) c.string.encode(state, m.sourcePlatformLabel)
    if (version >= 2 && m.sourceUrl) c.string.encode(state, m.sourceUrl)
    if (version >= 2 && m.sourceId) c.string.encode(state, m.sourceId)
    if (version >= 2 && m.sourceCreatorName) c.string.encode(state, m.sourceCreatorName)
    if (version >= 2 && m.sourceCreatorHandle) c.string.encode(state, m.sourceCreatorHandle)
    if (version >= 2 && m.sourceCreatorUrl) c.string.encode(state, m.sourceCreatorUrl)
    if (version >= 2 && m.sourcePublishedAt) c.uint64.encode(state, m.sourcePublishedAt)
    if (version >= 2 && m.sourceViewCount) c.uint64.encode(state, m.sourceViewCount)
    if (version >= 2 && m.sourceLikeCount) c.uint64.encode(state, m.sourceLikeCount)
    if (version >= 2 && m.sourceCommentCount) c.uint64.encode(state, m.sourceCommentCount)
    if (version >= 2 && m.sourceArchivedAt) c.uint64.encode(state, m.sourceArchivedAt)
    if (version >= 2 && m.sourceRelayId) c.string.encode(state, m.sourceRelayId)
    if (version >= 2 && m.sourceMetadataJson) c.string.encode(state, m.sourceMetadataJson)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint16.decode(state)

    return {
      videoId: r0,
      sourcePlatform: (version >= 2 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      sourcePlatformLabel: (version >= 2 && (flags & 2) !== 0) ? c.string.decode(state) : null,
      sourceUrl: (version >= 2 && (flags & 4) !== 0) ? c.string.decode(state) : null,
      sourceId: (version >= 2 && (flags & 8) !== 0) ? c.string.decode(state) : null,
      sourceCreatorName: (version >= 2 && (flags & 16) !== 0) ? c.string.decode(state) : null,
      sourceCreatorHandle: (version >= 2 && (flags & 32) !== 0) ? c.string.decode(state) : null,
      sourceCreatorUrl: (version >= 2 && (flags & 64) !== 0) ? c.string.decode(state) : null,
      sourcePublishedAt: (version >= 2 && (flags & 128) !== 0) ? c.uint64.decode(state) : 0,
      sourceViewCount: (version >= 2 && (flags & 256) !== 0) ? c.uint64.decode(state) : 0,
      sourceLikeCount: (version >= 2 && (flags & 512) !== 0) ? c.uint64.decode(state) : 0,
      sourceCommentCount: (version >= 2 && (flags & 1024) !== 0) ? c.uint64.decode(state) : 0,
      sourceArchivedAt: (version >= 2 && (flags & 2048) !== 0) ? c.uint64.decode(state) : 0,
      sourceRelayId: (version >= 2 && (flags & 4096) !== 0) ? c.string.decode(state) : null,
      sourceMetadataJson: (version >= 2 && (flags & 8192) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @peartubePublic/metadata/hyperdb#0
const encoding3 = {
  preencode(state, m) {
    state.end++ // flags are fixed size

    if (m.name) c.string.preencode(state, m.name)
    if (m.description) c.string.preencode(state, m.description)
    if (m.avatar) c.string.preencode(state, m.avatar)
    if (m.publicBeeKey) c.string.preencode(state, m.publicBeeKey)
    if (m.commentsDbKey) c.string.preencode(state, m.commentsDbKey)
    if (m.createdAt) c.uint64.preencode(state, m.createdAt)
    if (m.createdBy) c.string.preencode(state, m.createdBy)
    if (m.updatedAt) c.uint64.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags =
      (m.name ? 1 : 0) |
      (m.description ? 2 : 0) |
      (m.avatar ? 4 : 0) |
      (m.publicBeeKey ? 8 : 0) |
      (m.commentsDbKey ? 16 : 0) |
      (m.createdAt ? 32 : 0) |
      (m.createdBy ? 64 : 0) |
      (m.updatedAt ? 128 : 0)

    c.uint8.encode(state, flags)

    if (m.name) c.string.encode(state, m.name)
    if (m.description) c.string.encode(state, m.description)
    if (m.avatar) c.string.encode(state, m.avatar)
    if (m.publicBeeKey) c.string.encode(state, m.publicBeeKey)
    if (m.commentsDbKey) c.string.encode(state, m.commentsDbKey)
    if (m.createdAt) c.uint64.encode(state, m.createdAt)
    if (m.createdBy) c.string.encode(state, m.createdBy)
    if (m.updatedAt) c.uint64.encode(state, m.updatedAt)
  },
  decode(state) {
    const flags = c.uint8.decode(state)

    return {
      key: null,
      name: (flags & 1) !== 0 ? c.string.decode(state) : null,
      description: (flags & 2) !== 0 ? c.string.decode(state) : null,
      avatar: (flags & 4) !== 0 ? c.string.decode(state) : null,
      publicBeeKey: (flags & 8) !== 0 ? c.string.decode(state) : null,
      commentsDbKey: (flags & 16) !== 0 ? c.string.decode(state) : null,
      createdAt: (flags & 32) !== 0 ? c.uint64.decode(state) : 0,
      createdBy: (flags & 64) !== 0 ? c.string.decode(state) : null,
      updatedAt: (flags & 128) !== 0 ? c.uint64.decode(state) : 0
    }
  }
}

// @peartubePublic/video/hyperdb#1
const encoding4 = {
  preencode(state, m) {
    state.end += 3 // flags are fixed size

    if (m.title) c.string.preencode(state, m.title)
    if (m.description) c.string.preencode(state, m.description)
    if (m.path) c.string.preencode(state, m.path)
    if (m.duration) c.uint64.preencode(state, m.duration)
    if (m.thumbnail) c.string.preencode(state, m.thumbnail)
    if (m.thumbnailBlobId) c.string.preencode(state, m.thumbnailBlobId)
    if (m.thumbnailBlobsCoreKey) c.string.preencode(state, m.thumbnailBlobsCoreKey)
    if (m.thumbnailMimeType) c.string.preencode(state, m.thumbnailMimeType)
    if (m.blobId) c.string.preencode(state, m.blobId)
    if (m.blobsCoreKey) c.string.preencode(state, m.blobsCoreKey)
    if (m.blobDriveKey) c.string.preencode(state, m.blobDriveKey)
    if (m.mimeType) c.string.preencode(state, m.mimeType)
    if (m.size) c.uint64.preencode(state, m.size)
    if (m.category) c.string.preencode(state, m.category)
    if (m.views) c.uint64.preencode(state, m.views)
    if (m.uploadedAt) c.uint64.preencode(state, m.uploadedAt)
    if (m.uploadedBy) c.string.preencode(state, m.uploadedBy)
    if (m.updatedAt) c.uint64.preencode(state, m.updatedAt)
    if (m.updatedBy) c.string.preencode(state, m.updatedBy)
    if (m.syncedAt) c.uint64.preencode(state, m.syncedAt)
  },
  encode(state, m) {
    const flags =
      (m.title ? 1 : 0) |
      (m.description ? 2 : 0) |
      (m.path ? 4 : 0) |
      (m.duration ? 8 : 0) |
      (m.thumbnail ? 16 : 0) |
      (m.thumbnailBlobId ? 32 : 0) |
      (m.thumbnailBlobsCoreKey ? 64 : 0) |
      (m.thumbnailMimeType ? 128 : 0) |
      (m.blobId ? 256 : 0) |
      (m.blobsCoreKey ? 512 : 0) |
      (m.blobDriveKey ? 1024 : 0) |
      (m.mimeType ? 2048 : 0) |
      (m.size ? 4096 : 0) |
      (m.category ? 8192 : 0) |
      (m.views ? 16384 : 0) |
      (m.uploadedAt ? 32768 : 0) |
      (m.uploadedBy ? 65536 : 0) |
      (m.updatedAt ? 131072 : 0) |
      (m.updatedBy ? 262144 : 0) |
      (m.syncedAt ? 524288 : 0)

    c.uint24.encode(state, flags)

    if (m.title) c.string.encode(state, m.title)
    if (m.description) c.string.encode(state, m.description)
    if (m.path) c.string.encode(state, m.path)
    if (m.duration) c.uint64.encode(state, m.duration)
    if (m.thumbnail) c.string.encode(state, m.thumbnail)
    if (m.thumbnailBlobId) c.string.encode(state, m.thumbnailBlobId)
    if (m.thumbnailBlobsCoreKey) c.string.encode(state, m.thumbnailBlobsCoreKey)
    if (m.thumbnailMimeType) c.string.encode(state, m.thumbnailMimeType)
    if (m.blobId) c.string.encode(state, m.blobId)
    if (m.blobsCoreKey) c.string.encode(state, m.blobsCoreKey)
    if (m.blobDriveKey) c.string.encode(state, m.blobDriveKey)
    if (m.mimeType) c.string.encode(state, m.mimeType)
    if (m.size) c.uint64.encode(state, m.size)
    if (m.category) c.string.encode(state, m.category)
    if (m.views) c.uint64.encode(state, m.views)
    if (m.uploadedAt) c.uint64.encode(state, m.uploadedAt)
    if (m.uploadedBy) c.string.encode(state, m.uploadedBy)
    if (m.updatedAt) c.uint64.encode(state, m.updatedAt)
    if (m.updatedBy) c.string.encode(state, m.updatedBy)
    if (m.syncedAt) c.uint64.encode(state, m.syncedAt)
  },
  decode(state) {
    const flags = c.uint24.decode(state)

    return {
      id: null,
      title: (flags & 1) !== 0 ? c.string.decode(state) : null,
      description: (flags & 2) !== 0 ? c.string.decode(state) : null,
      path: (flags & 4) !== 0 ? c.string.decode(state) : null,
      duration: (flags & 8) !== 0 ? c.uint64.decode(state) : 0,
      thumbnail: (flags & 16) !== 0 ? c.string.decode(state) : null,
      thumbnailBlobId: (flags & 32) !== 0 ? c.string.decode(state) : null,
      thumbnailBlobsCoreKey: (flags & 64) !== 0 ? c.string.decode(state) : null,
      thumbnailMimeType: (flags & 128) !== 0 ? c.string.decode(state) : null,
      blobId: (flags & 256) !== 0 ? c.string.decode(state) : null,
      blobsCoreKey: (flags & 512) !== 0 ? c.string.decode(state) : null,
      blobDriveKey: (flags & 1024) !== 0 ? c.string.decode(state) : null,
      mimeType: (flags & 2048) !== 0 ? c.string.decode(state) : null,
      size: (flags & 4096) !== 0 ? c.uint64.decode(state) : 0,
      category: (flags & 8192) !== 0 ? c.string.decode(state) : null,
      views: (flags & 16384) !== 0 ? c.uint64.decode(state) : 0,
      uploadedAt: (flags & 32768) !== 0 ? c.uint64.decode(state) : 0,
      uploadedBy: (flags & 65536) !== 0 ? c.string.decode(state) : null,
      updatedAt: (flags & 131072) !== 0 ? c.uint64.decode(state) : 0,
      updatedBy: (flags & 262144) !== 0 ? c.string.decode(state) : null,
      syncedAt: (flags & 524288) !== 0 ? c.uint64.decode(state) : 0
    }
  }
}

// @peartubePublic/videoSourceMetadata/hyperdb#3
const encoding5 = {
  preencode(state, m) {
    state.end += 2 // flags are fixed size

    if (version >= 2 && m.sourcePlatform) c.string.preencode(state, m.sourcePlatform)
    if (version >= 2 && m.sourcePlatformLabel) c.string.preencode(state, m.sourcePlatformLabel)
    if (version >= 2 && m.sourceUrl) c.string.preencode(state, m.sourceUrl)
    if (version >= 2 && m.sourceId) c.string.preencode(state, m.sourceId)
    if (version >= 2 && m.sourceCreatorName) c.string.preencode(state, m.sourceCreatorName)
    if (version >= 2 && m.sourceCreatorHandle) c.string.preencode(state, m.sourceCreatorHandle)
    if (version >= 2 && m.sourceCreatorUrl) c.string.preencode(state, m.sourceCreatorUrl)
    if (version >= 2 && m.sourcePublishedAt) c.uint64.preencode(state, m.sourcePublishedAt)
    if (version >= 2 && m.sourceViewCount) c.uint64.preencode(state, m.sourceViewCount)
    if (version >= 2 && m.sourceLikeCount) c.uint64.preencode(state, m.sourceLikeCount)
    if (version >= 2 && m.sourceCommentCount) c.uint64.preencode(state, m.sourceCommentCount)
    if (version >= 2 && m.sourceArchivedAt) c.uint64.preencode(state, m.sourceArchivedAt)
    if (version >= 2 && m.sourceRelayId) c.string.preencode(state, m.sourceRelayId)
    if (version >= 2 && m.sourceMetadataJson) c.string.preencode(state, m.sourceMetadataJson)
  },
  encode(state, m) {
    const flags =
      ((version >= 2 && m.sourcePlatform) ? 1 : 0) |
      ((version >= 2 && m.sourcePlatformLabel) ? 2 : 0) |
      ((version >= 2 && m.sourceUrl) ? 4 : 0) |
      ((version >= 2 && m.sourceId) ? 8 : 0) |
      ((version >= 2 && m.sourceCreatorName) ? 16 : 0) |
      ((version >= 2 && m.sourceCreatorHandle) ? 32 : 0) |
      ((version >= 2 && m.sourceCreatorUrl) ? 64 : 0) |
      ((version >= 2 && m.sourcePublishedAt) ? 128 : 0) |
      ((version >= 2 && m.sourceViewCount) ? 256 : 0) |
      ((version >= 2 && m.sourceLikeCount) ? 512 : 0) |
      ((version >= 2 && m.sourceCommentCount) ? 1024 : 0) |
      ((version >= 2 && m.sourceArchivedAt) ? 2048 : 0) |
      ((version >= 2 && m.sourceRelayId) ? 4096 : 0) |
      ((version >= 2 && m.sourceMetadataJson) ? 8192 : 0)

    c.uint16.encode(state, flags)

    if (version >= 2 && m.sourcePlatform) c.string.encode(state, m.sourcePlatform)
    if (version >= 2 && m.sourcePlatformLabel) c.string.encode(state, m.sourcePlatformLabel)
    if (version >= 2 && m.sourceUrl) c.string.encode(state, m.sourceUrl)
    if (version >= 2 && m.sourceId) c.string.encode(state, m.sourceId)
    if (version >= 2 && m.sourceCreatorName) c.string.encode(state, m.sourceCreatorName)
    if (version >= 2 && m.sourceCreatorHandle) c.string.encode(state, m.sourceCreatorHandle)
    if (version >= 2 && m.sourceCreatorUrl) c.string.encode(state, m.sourceCreatorUrl)
    if (version >= 2 && m.sourcePublishedAt) c.uint64.encode(state, m.sourcePublishedAt)
    if (version >= 2 && m.sourceViewCount) c.uint64.encode(state, m.sourceViewCount)
    if (version >= 2 && m.sourceLikeCount) c.uint64.encode(state, m.sourceLikeCount)
    if (version >= 2 && m.sourceCommentCount) c.uint64.encode(state, m.sourceCommentCount)
    if (version >= 2 && m.sourceArchivedAt) c.uint64.encode(state, m.sourceArchivedAt)
    if (version >= 2 && m.sourceRelayId) c.string.encode(state, m.sourceRelayId)
    if (version >= 2 && m.sourceMetadataJson) c.string.encode(state, m.sourceMetadataJson)
  },
  decode(state) {
    const flags = c.uint16.decode(state)

    return {
      videoId: null,
      sourcePlatform: (version >= 2 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      sourcePlatformLabel: (version >= 2 && (flags & 2) !== 0) ? c.string.decode(state) : null,
      sourceUrl: (version >= 2 && (flags & 4) !== 0) ? c.string.decode(state) : null,
      sourceId: (version >= 2 && (flags & 8) !== 0) ? c.string.decode(state) : null,
      sourceCreatorName: (version >= 2 && (flags & 16) !== 0) ? c.string.decode(state) : null,
      sourceCreatorHandle: (version >= 2 && (flags & 32) !== 0) ? c.string.decode(state) : null,
      sourceCreatorUrl: (version >= 2 && (flags & 64) !== 0) ? c.string.decode(state) : null,
      sourcePublishedAt: (version >= 2 && (flags & 128) !== 0) ? c.uint64.decode(state) : 0,
      sourceViewCount: (version >= 2 && (flags & 256) !== 0) ? c.uint64.decode(state) : 0,
      sourceLikeCount: (version >= 2 && (flags & 512) !== 0) ? c.uint64.decode(state) : 0,
      sourceCommentCount: (version >= 2 && (flags & 1024) !== 0) ? c.uint64.decode(state) : 0,
      sourceArchivedAt: (version >= 2 && (flags & 2048) !== 0) ? c.uint64.decode(state) : 0,
      sourceRelayId: (version >= 2 && (flags & 4096) !== 0) ? c.string.decode(state) : null,
      sourceMetadataJson: (version >= 2 && (flags & 8192) !== 0) ? c.string.decode(state) : null
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@peartubePublic/metadata':
      return encoding0
    case '@peartubePublic/video':
      return encoding1
    case '@peartubePublic/videoSourceMetadata':
      return encoding2
    case '@peartubePublic/metadata/hyperdb#0':
      return encoding3
    case '@peartubePublic/video/hyperdb#1':
      return encoding4
    case '@peartubePublic/videoSourceMetadata/hyperdb#3':
      return encoding5
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

export { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
