// This file is autogenerated by the hyperschema compiler
// Schema Version: 3
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

import { c } from 'hyperschema/runtime'

const VERSION = 3

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @peartubePublic/metadata
const encoding0 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    state.end++ // flags are fixed size

    if (m.name) c.string.preencode(state, m.name)
    if (m.description) c.string.preencode(state, m.description)
    if (m.avatar) c.string.preencode(state, m.avatar)
    if (m.publicBeeKey) c.string.preencode(state, m.publicBeeKey)
    if (m.commentsDbKey) c.string.preencode(state, m.commentsDbKey)
    if (m.createdAt) c.uint64.preencode(state, m.createdAt)
    if (m.createdBy) c.string.preencode(state, m.createdBy)
    if (m.updatedAt) c.uint64.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags =
      (m.name ? 1 : 0) |
      (m.description ? 2 : 0) |
      (m.avatar ? 4 : 0) |
      (m.publicBeeKey ? 8 : 0) |
      (m.commentsDbKey ? 16 : 0) |
      (m.createdAt ? 32 : 0) |
      (m.createdBy ? 64 : 0) |
      (m.updatedAt ? 128 : 0)

    c.string.encode(state, m.key)
    c.uint8.encode(state, flags)

    if (m.name) c.string.encode(state, m.name)
    if (m.description) c.string.encode(state, m.description)
    if (m.avatar) c.string.encode(state, m.avatar)
    if (m.publicBeeKey) c.string.encode(state, m.publicBeeKey)
    if (m.commentsDbKey) c.string.encode(state, m.commentsDbKey)
    if (m.createdAt) c.uint64.encode(state, m.createdAt)
    if (m.createdBy) c.string.encode(state, m.createdBy)
    if (m.updatedAt) c.uint64.encode(state, m.updatedAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint8.decode(state)

    return {
      key: r0,
      name: (flags & 1) !== 0 ? c.string.decode(state) : null,
      description: (flags & 2) !== 0 ? c.string.decode(state) : null,
      avatar: (flags & 4) !== 0 ? c.string.decode(state) : null,
      publicBeeKey: (flags & 8) !== 0 ? c.string.decode(state) : null,
      commentsDbKey: (flags & 16) !== 0 ? c.string.decode(state) : null,
      createdAt: (flags & 32) !== 0 ? c.uint64.decode(state) : 0,
      createdBy: (flags & 64) !== 0 ? c.string.decode(state) : null,
      updatedAt: (flags & 128) !== 0 ? c.uint64.decode(state) : 0
    }
  }
}

// @peartubePublic/video
const encoding1 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    state.end += 3 // flags are fixed size

    if (m.title) c.string.preencode(state, m.title)
    if (m.description) c.string.preencode(state, m.description)
    if (m.path) c.string.preencode(state, m.path)
    if (m.duration) c.uint64.preencode(state, m.duration)
    if (m.thumbnail) c.string.preencode(state, m.thumbnail)
    if (m.thumbnailBlobId) c.string.preencode(state, m.thumbnailBlobId)
    if (m.thumbnailBlobsCoreKey) c.string.preencode(state, m.thumbnailBlobsCoreKey)
    if (m.thumbnailMimeType) c.string.preencode(state, m.thumbnailMimeType)
    if (m.blobId) c.string.preencode(state, m.blobId)
    if (m.blobsCoreKey) c.string.preencode(state, m.blobsCoreKey)
    if (m.blobDriveKey) c.string.preencode(state, m.blobDriveKey)
    if (m.mimeType) c.string.preencode(state, m.mimeType)
    if (m.size) c.uint64.preencode(state, m.size)
    if (m.category) c.string.preencode(state, m.category)
    if (m.views) c.uint64.preencode(state, m.views)
    if (m.uploadedAt) c.uint64.preencode(state, m.uploadedAt)
    if (m.uploadedBy) c.string.preencode(state, m.uploadedBy)
    if (m.updatedAt) c.uint64.preencode(state, m.updatedAt)
    if (m.updatedBy) c.string.preencode(state, m.updatedBy)
    if (m.syncedAt) c.uint64.preencode(state, m.syncedAt)
  },
  encode(state, m) {
    const flags =
      (m.title ? 1 : 0) |
      (m.description ? 2 : 0) |
      (m.path ? 4 : 0) |
      (m.duration ? 8 : 0) |
      (m.thumbnail ? 16 : 0) |
      (m.thumbnailBlobId ? 32 : 0) |
      (m.thumbnailBlobsCoreKey ? 64 : 0) |
      (m.thumbnailMimeType ? 128 : 0) |
      (m.blobId ? 256 : 0) |
      (m.blobsCoreKey ? 512 : 0) |
      (m.blobDriveKey ? 1024 : 0) |
      (m.mimeType ? 2048 : 0) |
      (m.size ? 4096 : 0) |
      (m.category ? 8192 : 0) |
      (m.views ? 16384 : 0) |
      (m.uploadedAt ? 32768 : 0) |
      (m.uploadedBy ? 65536 : 0) |
      (m.updatedAt ? 131072 : 0) |
      (m.updatedBy ? 262144 : 0) |
      (m.syncedAt ? 524288 : 0)

    c.string.encode(state, m.id)
    c.uint24.encode(state, flags)

    if (m.title) c.string.encode(state, m.title)
    if (m.description) c.string.encode(state, m.description)
    if (m.path) c.string.encode(state, m.path)
    if (m.duration) c.uint64.encode(state, m.duration)
    if (m.thumbnail) c.string.encode(state, m.thumbnail)
    if (m.thumbnailBlobId) c.string.encode(state, m.thumbnailBlobId)
    if (m.thumbnailBlobsCoreKey) c.string.encode(state, m.thumbnailBlobsCoreKey)
    if (m.thumbnailMimeType) c.string.encode(state, m.thumbnailMimeType)
    if (m.blobId) c.string.encode(state, m.blobId)
    if (m.blobsCoreKey) c.string.encode(state, m.blobsCoreKey)
    if (m.blobDriveKey) c.string.encode(state, m.blobDriveKey)
    if (m.mimeType) c.string.encode(state, m.mimeType)
    if (m.size) c.uint64.encode(state, m.size)
    if (m.category) c.string.encode(state, m.category)
    if (m.views) c.uint64.encode(state, m.views)
    if (m.uploadedAt) c.uint64.encode(state, m.uploadedAt)
    if (m.uploadedBy) c.string.encode(state, m.uploadedBy)
    if (m.updatedAt) c.uint64.encode(state, m.updatedAt)
    if (m.updatedBy) c.string.encode(state, m.updatedBy)
    if (m.syncedAt) c.uint64.encode(state, m.syncedAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint24.decode(state)

    return {
      id: r0,
      title: (flags & 1) !== 0 ? c.string.decode(state) : null,
      description: (flags & 2) !== 0 ? c.string.decode(state) : null,
      path: (flags & 4) !== 0 ? c.string.decode(state) : null,
      duration: (flags & 8) !== 0 ? c.uint64.decode(state) : 0,
      thumbnail: (flags & 16) !== 0 ? c.string.decode(state) : null,
      thumbnailBlobId: (flags & 32) !== 0 ? c.string.decode(state) : null,
      thumbnailBlobsCoreKey: (flags & 64) !== 0 ? c.string.decode(state) : null,
      thumbnailMimeType: (flags & 128) !== 0 ? c.string.decode(state) : null,
      blobId: (flags & 256) !== 0 ? c.string.decode(state) : null,
      blobsCoreKey: (flags & 512) !== 0 ? c.string.decode(state) : null,
      blobDriveKey: (flags & 1024) !== 0 ? c.string.decode(state) : null,
      mimeType: (flags & 2048) !== 0 ? c.string.decode(state) : null,
      size: (flags & 4096) !== 0 ? c.uint64.decode(state) : 0,
      category: (flags & 8192) !== 0 ? c.string.decode(state) : null,
      views: (flags & 16384) !== 0 ? c.uint64.decode(state) : 0,
      uploadedAt: (flags & 32768) !== 0 ? c.uint64.decode(state) : 0,
      uploadedBy: (flags & 65536) !== 0 ? c.string.decode(state) : null,
      updatedAt: (flags & 131072) !== 0 ? c.uint64.decode(state) : 0,
      updatedBy: (flags & 262144) !== 0 ? c.string.decode(state) : null,
      syncedAt: (flags & 524288) !== 0 ? c.uint64.decode(state) : 0
    }
  }
}

// @peartubePublic/channelProfile
const encoding2 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    state.end++ // max flag is 64 so always one byte

    if (version >= 2 && m.profileKind) c.string.preencode(state, m.profileKind)
    if (version >= 2 && m.mediaProvider) c.string.preencode(state, m.mediaProvider)
    if (version >= 2 && m.mediaId) c.string.preencode(state, m.mediaId)
    if (version >= 2 && m.originalLanguage) c.string.preencode(state, m.originalLanguage)
    if (version >= 2 && m.releaseDate) c.uint64.preencode(state, m.releaseDate)
    if (version >= 2 && m.releaseYear) c.uint64.preencode(state, m.releaseYear)
    if (version >= 2 && m.canonicalRevision) c.string.preencode(state, m.canonicalRevision)
  },
  encode(state, m) {
    const flags =
      ((version >= 2 && m.profileKind) ? 1 : 0) |
      ((version >= 2 && m.mediaProvider) ? 2 : 0) |
      ((version >= 2 && m.mediaId) ? 4 : 0) |
      ((version >= 2 && m.originalLanguage) ? 8 : 0) |
      ((version >= 2 && m.releaseDate) ? 16 : 0) |
      ((version >= 2 && m.releaseYear) ? 32 : 0) |
      ((version >= 2 && m.canonicalRevision) ? 64 : 0)

    c.string.encode(state, m.id)
    c.uint.encode(state, flags)

    if (version >= 2 && m.profileKind) c.string.encode(state, m.profileKind)
    if (version >= 2 && m.mediaProvider) c.string.encode(state, m.mediaProvider)
    if (version >= 2 && m.mediaId) c.string.encode(state, m.mediaId)
    if (version >= 2 && m.originalLanguage) c.string.encode(state, m.originalLanguage)
    if (version >= 2 && m.releaseDate) c.uint64.encode(state, m.releaseDate)
    if (version >= 2 && m.releaseYear) c.uint64.encode(state, m.releaseYear)
    if (version >= 2 && m.canonicalRevision) c.string.encode(state, m.canonicalRevision)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      profileKind: (version >= 2 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      mediaProvider: (version >= 2 && (flags & 2) !== 0) ? c.string.decode(state) : null,
      mediaId: (version >= 2 && (flags & 4) !== 0) ? c.string.decode(state) : null,
      originalLanguage: (version >= 2 && (flags & 8) !== 0) ? c.string.decode(state) : null,
      releaseDate: (version >= 2 && (flags & 16) !== 0) ? c.uint64.decode(state) : 0,
      releaseYear: (version >= 2 && (flags & 32) !== 0) ? c.uint64.decode(state) : 0,
      canonicalRevision: (version >= 2 && (flags & 64) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @peartubePublic/contentDetails
const encoding3 = {
  preencode(state, m) {
    const flags =
      ((version >= 2 && m.contentKind) ? 1 : 0) |
      ((version >= 2 && m.sourceProvider) ? 2 : 0) |
      ((version >= 2 && m.sourceVideoId) ? 4 : 0) |
      ((version >= 2 && m.identityUrl) ? 8 : 0) |
      ((version >= 2 && m.sourceCreatorId) ? 16 : 0) |
      ((version >= 2 && m.sourceCreatorUrl) ? 32 : 0) |
      ((version >= 2 && m.sourcePublishedAt) ? 64 : 0) |
      ((version >= 2 && m.mediaProvider) ? 128 : 0) |
      ((version >= 2 && m.mediaId) ? 256 : 0) |
      ((version >= 2 && m.seasonNumber) ? 512 : 0) |
      ((version >= 2 && m.episodeNumber) ? 1024 : 0) |
      ((version >= 2 && m.originalAirDate) ? 2048 : 0) |
      ((version >= 2 && m.thumbnailUrl) ? 4096 : 0) |
      ((version >= 2 && m.provenanceVersion) ? 8192 : 0) |
      ((version >= 2 && m.publicationState) ? 16384 : 0) |
      ((version >= 2 && m.contentFingerprint) ? 32768 : 0) |
      ((version >= 2 && m.importIdentityKey) ? 65536 : 0) |
      ((version >= 2 && m.importClaimantId) ? 131072 : 0) |
      ((version >= 2 && m.canonicalVisibility) ? 262144 : 0) |
      ((version >= 2 && m.duplicateOfClaimantId) ? 524288 : 0) |
      ((version >= 3 && m.artwork) ? 1048576 : 0)

    c.string.preencode(state, m.id)
    c.uint.preencode(state, flags)

    if (version >= 2 && m.contentKind) c.string.preencode(state, m.contentKind)
    if (version >= 2 && m.sourceProvider) c.string.preencode(state, m.sourceProvider)
    if (version >= 2 && m.sourceVideoId) c.string.preencode(state, m.sourceVideoId)
    if (version >= 2 && m.identityUrl) c.string.preencode(state, m.identityUrl)
    if (version >= 2 && m.sourceCreatorId) c.string.preencode(state, m.sourceCreatorId)
    if (version >= 2 && m.sourceCreatorUrl) c.string.preencode(state, m.sourceCreatorUrl)
    if (version >= 2 && m.sourcePublishedAt) c.uint64.preencode(state, m.sourcePublishedAt)
    if (version >= 2 && m.mediaProvider) c.string.preencode(state, m.mediaProvider)
    if (version >= 2 && m.mediaId) c.string.preencode(state, m.mediaId)
    if (version >= 2 && m.seasonNumber) c.uint64.preencode(state, m.seasonNumber)
    if (version >= 2 && m.episodeNumber) c.uint64.preencode(state, m.episodeNumber)
    if (version >= 2 && m.originalAirDate) c.uint64.preencode(state, m.originalAirDate)
    if (version >= 2 && m.thumbnailUrl) c.string.preencode(state, m.thumbnailUrl)
    if (version >= 2 && m.provenanceVersion) c.string.preencode(state, m.provenanceVersion)
    if (version >= 2 && m.publicationState) c.string.preencode(state, m.publicationState)
    if (version >= 2 && m.contentFingerprint) c.string.preencode(state, m.contentFingerprint)
    if (version >= 2 && m.importIdentityKey) c.string.preencode(state, m.importIdentityKey)
    if (version >= 2 && m.importClaimantId) c.string.preencode(state, m.importClaimantId)
    if (version >= 2 && m.canonicalVisibility) c.string.preencode(state, m.canonicalVisibility)
    if (version >= 2 && m.duplicateOfClaimantId) c.string.preencode(state, m.duplicateOfClaimantId)
    if (version >= 3 && m.artwork) encoding3_21.preencode(state, m.artwork)
  },
  encode(state, m) {
    const flags =
      ((version >= 2 && m.contentKind) ? 1 : 0) |
      ((version >= 2 && m.sourceProvider) ? 2 : 0) |
      ((version >= 2 && m.sourceVideoId) ? 4 : 0) |
      ((version >= 2 && m.identityUrl) ? 8 : 0) |
      ((version >= 2 && m.sourceCreatorId) ? 16 : 0) |
      ((version >= 2 && m.sourceCreatorUrl) ? 32 : 0) |
      ((version >= 2 && m.sourcePublishedAt) ? 64 : 0) |
      ((version >= 2 && m.mediaProvider) ? 128 : 0) |
      ((version >= 2 && m.mediaId) ? 256 : 0) |
      ((version >= 2 && m.seasonNumber) ? 512 : 0) |
      ((version >= 2 && m.episodeNumber) ? 1024 : 0) |
      ((version >= 2 && m.originalAirDate) ? 2048 : 0) |
      ((version >= 2 && m.thumbnailUrl) ? 4096 : 0) |
      ((version >= 2 && m.provenanceVersion) ? 8192 : 0) |
      ((version >= 2 && m.publicationState) ? 16384 : 0) |
      ((version >= 2 && m.contentFingerprint) ? 32768 : 0) |
      ((version >= 2 && m.importIdentityKey) ? 65536 : 0) |
      ((version >= 2 && m.importClaimantId) ? 131072 : 0) |
      ((version >= 2 && m.canonicalVisibility) ? 262144 : 0) |
      ((version >= 2 && m.duplicateOfClaimantId) ? 524288 : 0) |
      ((version >= 3 && m.artwork) ? 1048576 : 0)

    c.string.encode(state, m.id)
    c.uint.encode(state, flags)

    if (version >= 2 && m.contentKind) c.string.encode(state, m.contentKind)
    if (version >= 2 && m.sourceProvider) c.string.encode(state, m.sourceProvider)
    if (version >= 2 && m.sourceVideoId) c.string.encode(state, m.sourceVideoId)
    if (version >= 2 && m.identityUrl) c.string.encode(state, m.identityUrl)
    if (version >= 2 && m.sourceCreatorId) c.string.encode(state, m.sourceCreatorId)
    if (version >= 2 && m.sourceCreatorUrl) c.string.encode(state, m.sourceCreatorUrl)
    if (version >= 2 && m.sourcePublishedAt) c.uint64.encode(state, m.sourcePublishedAt)
    if (version >= 2 && m.mediaProvider) c.string.encode(state, m.mediaProvider)
    if (version >= 2 && m.mediaId) c.string.encode(state, m.mediaId)
    if (version >= 2 && m.seasonNumber) c.uint64.encode(state, m.seasonNumber)
    if (version >= 2 && m.episodeNumber) c.uint64.encode(state, m.episodeNumber)
    if (version >= 2 && m.originalAirDate) c.uint64.encode(state, m.originalAirDate)
    if (version >= 2 && m.thumbnailUrl) c.string.encode(state, m.thumbnailUrl)
    if (version >= 2 && m.provenanceVersion) c.string.encode(state, m.provenanceVersion)
    if (version >= 2 && m.publicationState) c.string.encode(state, m.publicationState)
    if (version >= 2 && m.contentFingerprint) c.string.encode(state, m.contentFingerprint)
    if (version >= 2 && m.importIdentityKey) c.string.encode(state, m.importIdentityKey)
    if (version >= 2 && m.importClaimantId) c.string.encode(state, m.importClaimantId)
    if (version >= 2 && m.canonicalVisibility) c.string.encode(state, m.canonicalVisibility)
    if (version >= 2 && m.duplicateOfClaimantId) c.string.encode(state, m.duplicateOfClaimantId)
    if (version >= 3 && m.artwork) encoding3_21.encode(state, m.artwork)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      contentKind: (version >= 2 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      sourceProvider: (version >= 2 && (flags & 2) !== 0) ? c.string.decode(state) : null,
      sourceVideoId: (version >= 2 && (flags & 4) !== 0) ? c.string.decode(state) : null,
      identityUrl: (version >= 2 && (flags & 8) !== 0) ? c.string.decode(state) : null,
      sourceCreatorId: (version >= 2 && (flags & 16) !== 0) ? c.string.decode(state) : null,
      sourceCreatorUrl: (version >= 2 && (flags & 32) !== 0) ? c.string.decode(state) : null,
      sourcePublishedAt: (version >= 2 && (flags & 64) !== 0) ? c.uint64.decode(state) : 0,
      mediaProvider: (version >= 2 && (flags & 128) !== 0) ? c.string.decode(state) : null,
      mediaId: (version >= 2 && (flags & 256) !== 0) ? c.string.decode(state) : null,
      seasonNumber: (version >= 2 && (flags & 512) !== 0) ? c.uint64.decode(state) : 0,
      episodeNumber: (version >= 2 && (flags & 1024) !== 0) ? c.uint64.decode(state) : 0,
      originalAirDate: (version >= 2 && (flags & 2048) !== 0) ? c.uint64.decode(state) : 0,
      thumbnailUrl: (version >= 2 && (flags & 4096) !== 0) ? c.string.decode(state) : null,
      provenanceVersion: (version >= 2 && (flags & 8192) !== 0) ? c.string.decode(state) : null,
      publicationState: (version >= 2 && (flags & 16384) !== 0) ? c.string.decode(state) : null,
      contentFingerprint: (version >= 2 && (flags & 32768) !== 0) ? c.string.decode(state) : null,
      importIdentityKey: (version >= 2 && (flags & 65536) !== 0) ? c.string.decode(state) : null,
      importClaimantId: (version >= 2 && (flags & 131072) !== 0) ? c.string.decode(state) : null,
      canonicalVisibility: (version >= 2 && (flags & 262144) !== 0) ? c.string.decode(state) : null,
      duplicateOfClaimantId: (version >= 2 && (flags & 524288) !== 0) ? c.string.decode(state) : null,
      artwork: (version >= 3 && (flags & 1048576) !== 0) ? encoding3_21.decode(state) : null
    }
  }
}

// @peartubePublic/channelSource
const encoding4 = {
  preencode(state, m) {
    c.string.preencode(state, m.provider)
    c.string.preencode(state, m.identityKey)
    state.end++ // flags are fixed size

    if (version >= 2 && m.sourceId) c.string.preencode(state, m.sourceId)
    if (version >= 2 && m.identityUrl) c.string.preencode(state, m.identityUrl)
    if (version >= 2 && m.handle) c.string.preencode(state, m.handle)
    if (version >= 2 && m.displayName) c.string.preencode(state, m.displayName)
    if (version >= 2 && m.createdAt) c.uint64.preencode(state, m.createdAt)
    if (version >= 2 && m.updatedAt) c.uint64.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags =
      ((version >= 2 && m.sourceId) ? 1 : 0) |
      ((version >= 2 && m.identityUrl) ? 2 : 0) |
      ((version >= 2 && m.handle) ? 4 : 0) |
      ((version >= 2 && m.displayName) ? 8 : 0) |
      ((version >= 2 && m.createdAt) ? 16 : 0) |
      ((version >= 2 && m.updatedAt) ? 32 : 0)

    c.string.encode(state, m.provider)
    c.string.encode(state, m.identityKey)
    c.uint8.encode(state, flags)

    if (version >= 2 && m.sourceId) c.string.encode(state, m.sourceId)
    if (version >= 2 && m.identityUrl) c.string.encode(state, m.identityUrl)
    if (version >= 2 && m.handle) c.string.encode(state, m.handle)
    if (version >= 2 && m.displayName) c.string.encode(state, m.displayName)
    if (version >= 2 && m.createdAt) c.uint64.encode(state, m.createdAt)
    if (version >= 2 && m.updatedAt) c.uint64.encode(state, m.updatedAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint8.decode(state)

    return {
      provider: r0,
      identityKey: r1,
      sourceId: (version >= 2 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      identityUrl: (version >= 2 && (flags & 2) !== 0) ? c.string.decode(state) : null,
      handle: (version >= 2 && (flags & 4) !== 0) ? c.string.decode(state) : null,
      displayName: (version >= 2 && (flags & 8) !== 0) ? c.string.decode(state) : null,
      createdAt: (version >= 2 && (flags & 16) !== 0) ? c.uint64.decode(state) : 0,
      updatedAt: (version >= 2 && (flags & 32) !== 0) ? c.uint64.decode(state) : 0
    }
  }
}

// @peartubePublic/channelArtwork
const encoding5 = {
  preencode(state, m) {
    c.string.preencode(state, m.role)
    state.end++ // flags are fixed size

    if (version >= 2 && m.blobId) c.string.preencode(state, m.blobId)
    if (version >= 2 && m.blobsCoreKey) c.string.preencode(state, m.blobsCoreKey)
    if (version >= 2 && m.mimeType) c.string.preencode(state, m.mimeType)
    if (version >= 2 && m.remoteUrl) c.string.preencode(state, m.remoteUrl)
    if (version >= 2 && m.updatedAt) c.uint64.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags =
      ((version >= 2 && m.blobId) ? 1 : 0) |
      ((version >= 2 && m.blobsCoreKey) ? 2 : 0) |
      ((version >= 2 && m.mimeType) ? 4 : 0) |
      ((version >= 2 && m.remoteUrl) ? 8 : 0) |
      ((version >= 2 && m.updatedAt) ? 16 : 0)

    c.string.encode(state, m.role)
    c.uint8.encode(state, flags)

    if (version >= 2 && m.blobId) c.string.encode(state, m.blobId)
    if (version >= 2 && m.blobsCoreKey) c.string.encode(state, m.blobsCoreKey)
    if (version >= 2 && m.mimeType) c.string.encode(state, m.mimeType)
    if (version >= 2 && m.remoteUrl) c.string.encode(state, m.remoteUrl)
    if (version >= 2 && m.updatedAt) c.uint64.encode(state, m.updatedAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint8.decode(state)

    return {
      role: r0,
      blobId: (version >= 2 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      blobsCoreKey: (version >= 2 && (flags & 2) !== 0) ? c.string.decode(state) : null,
      mimeType: (version >= 2 && (flags & 4) !== 0) ? c.string.decode(state) : null,
      remoteUrl: (version >= 2 && (flags & 8) !== 0) ? c.string.decode(state) : null,
      updatedAt: (version >= 2 && (flags & 16) !== 0) ? c.uint64.decode(state) : 0
    }
  }
}

// @peartubePublic/contentArtwork
const encoding6 = {
  preencode(state, m) {
    c.string.preencode(state, m.role)
    state.end++ // flags are fixed size

    if (version >= 3 && m.blobId) c.string.preencode(state, m.blobId)
    if (version >= 3 && m.blobsCoreKey) c.string.preencode(state, m.blobsCoreKey)
    if (version >= 3 && m.mimeType) c.string.preencode(state, m.mimeType)
    if (version >= 3 && m.remoteUrl) c.string.preencode(state, m.remoteUrl)
  },
  encode(state, m) {
    const flags =
      ((version >= 3 && m.blobId) ? 1 : 0) |
      ((version >= 3 && m.blobsCoreKey) ? 2 : 0) |
      ((version >= 3 && m.mimeType) ? 4 : 0) |
      ((version >= 3 && m.remoteUrl) ? 8 : 0)

    c.string.encode(state, m.role)
    c.uint8.encode(state, flags)

    if (version >= 3 && m.blobId) c.string.encode(state, m.blobId)
    if (version >= 3 && m.blobsCoreKey) c.string.encode(state, m.blobsCoreKey)
    if (version >= 3 && m.mimeType) c.string.encode(state, m.mimeType)
    if (version >= 3 && m.remoteUrl) c.string.encode(state, m.remoteUrl)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint8.decode(state)

    return {
      role: r0,
      blobId: (version >= 3 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      blobsCoreKey: (version >= 3 && (flags & 2) !== 0) ? c.string.decode(state) : null,
      mimeType: (version >= 3 && (flags & 4) !== 0) ? c.string.decode(state) : null,
      remoteUrl: (version >= 3 && (flags & 8) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @peartubePublic/metadata/hyperdb#0
const encoding7 = {
  preencode(state, m) {
    state.end++ // flags are fixed size

    if (m.name) c.string.preencode(state, m.name)
    if (m.description) c.string.preencode(state, m.description)
    if (m.avatar) c.string.preencode(state, m.avatar)
    if (m.publicBeeKey) c.string.preencode(state, m.publicBeeKey)
    if (m.commentsDbKey) c.string.preencode(state, m.commentsDbKey)
    if (m.createdAt) c.uint64.preencode(state, m.createdAt)
    if (m.createdBy) c.string.preencode(state, m.createdBy)
    if (m.updatedAt) c.uint64.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags =
      (m.name ? 1 : 0) |
      (m.description ? 2 : 0) |
      (m.avatar ? 4 : 0) |
      (m.publicBeeKey ? 8 : 0) |
      (m.commentsDbKey ? 16 : 0) |
      (m.createdAt ? 32 : 0) |
      (m.createdBy ? 64 : 0) |
      (m.updatedAt ? 128 : 0)

    c.uint8.encode(state, flags)

    if (m.name) c.string.encode(state, m.name)
    if (m.description) c.string.encode(state, m.description)
    if (m.avatar) c.string.encode(state, m.avatar)
    if (m.publicBeeKey) c.string.encode(state, m.publicBeeKey)
    if (m.commentsDbKey) c.string.encode(state, m.commentsDbKey)
    if (m.createdAt) c.uint64.encode(state, m.createdAt)
    if (m.createdBy) c.string.encode(state, m.createdBy)
    if (m.updatedAt) c.uint64.encode(state, m.updatedAt)
  },
  decode(state) {
    const flags = c.uint8.decode(state)

    return {
      key: null,
      name: (flags & 1) !== 0 ? c.string.decode(state) : null,
      description: (flags & 2) !== 0 ? c.string.decode(state) : null,
      avatar: (flags & 4) !== 0 ? c.string.decode(state) : null,
      publicBeeKey: (flags & 8) !== 0 ? c.string.decode(state) : null,
      commentsDbKey: (flags & 16) !== 0 ? c.string.decode(state) : null,
      createdAt: (flags & 32) !== 0 ? c.uint64.decode(state) : 0,
      createdBy: (flags & 64) !== 0 ? c.string.decode(state) : null,
      updatedAt: (flags & 128) !== 0 ? c.uint64.decode(state) : 0
    }
  }
}

// @peartubePublic/video/hyperdb#1
const encoding8 = {
  preencode(state, m) {
    state.end += 3 // flags are fixed size

    if (m.title) c.string.preencode(state, m.title)
    if (m.description) c.string.preencode(state, m.description)
    if (m.path) c.string.preencode(state, m.path)
    if (m.duration) c.uint64.preencode(state, m.duration)
    if (m.thumbnail) c.string.preencode(state, m.thumbnail)
    if (m.thumbnailBlobId) c.string.preencode(state, m.thumbnailBlobId)
    if (m.thumbnailBlobsCoreKey) c.string.preencode(state, m.thumbnailBlobsCoreKey)
    if (m.thumbnailMimeType) c.string.preencode(state, m.thumbnailMimeType)
    if (m.blobId) c.string.preencode(state, m.blobId)
    if (m.blobsCoreKey) c.string.preencode(state, m.blobsCoreKey)
    if (m.blobDriveKey) c.string.preencode(state, m.blobDriveKey)
    if (m.mimeType) c.string.preencode(state, m.mimeType)
    if (m.size) c.uint64.preencode(state, m.size)
    if (m.category) c.string.preencode(state, m.category)
    if (m.views) c.uint64.preencode(state, m.views)
    if (m.uploadedAt) c.uint64.preencode(state, m.uploadedAt)
    if (m.uploadedBy) c.string.preencode(state, m.uploadedBy)
    if (m.updatedAt) c.uint64.preencode(state, m.updatedAt)
    if (m.updatedBy) c.string.preencode(state, m.updatedBy)
    if (m.syncedAt) c.uint64.preencode(state, m.syncedAt)
  },
  encode(state, m) {
    const flags =
      (m.title ? 1 : 0) |
      (m.description ? 2 : 0) |
      (m.path ? 4 : 0) |
      (m.duration ? 8 : 0) |
      (m.thumbnail ? 16 : 0) |
      (m.thumbnailBlobId ? 32 : 0) |
      (m.thumbnailBlobsCoreKey ? 64 : 0) |
      (m.thumbnailMimeType ? 128 : 0) |
      (m.blobId ? 256 : 0) |
      (m.blobsCoreKey ? 512 : 0) |
      (m.blobDriveKey ? 1024 : 0) |
      (m.mimeType ? 2048 : 0) |
      (m.size ? 4096 : 0) |
      (m.category ? 8192 : 0) |
      (m.views ? 16384 : 0) |
      (m.uploadedAt ? 32768 : 0) |
      (m.uploadedBy ? 65536 : 0) |
      (m.updatedAt ? 131072 : 0) |
      (m.updatedBy ? 262144 : 0) |
      (m.syncedAt ? 524288 : 0)

    c.uint24.encode(state, flags)

    if (m.title) c.string.encode(state, m.title)
    if (m.description) c.string.encode(state, m.description)
    if (m.path) c.string.encode(state, m.path)
    if (m.duration) c.uint64.encode(state, m.duration)
    if (m.thumbnail) c.string.encode(state, m.thumbnail)
    if (m.thumbnailBlobId) c.string.encode(state, m.thumbnailBlobId)
    if (m.thumbnailBlobsCoreKey) c.string.encode(state, m.thumbnailBlobsCoreKey)
    if (m.thumbnailMimeType) c.string.encode(state, m.thumbnailMimeType)
    if (m.blobId) c.string.encode(state, m.blobId)
    if (m.blobsCoreKey) c.string.encode(state, m.blobsCoreKey)
    if (m.blobDriveKey) c.string.encode(state, m.blobDriveKey)
    if (m.mimeType) c.string.encode(state, m.mimeType)
    if (m.size) c.uint64.encode(state, m.size)
    if (m.category) c.string.encode(state, m.category)
    if (m.views) c.uint64.encode(state, m.views)
    if (m.uploadedAt) c.uint64.encode(state, m.uploadedAt)
    if (m.uploadedBy) c.string.encode(state, m.uploadedBy)
    if (m.updatedAt) c.uint64.encode(state, m.updatedAt)
    if (m.updatedBy) c.string.encode(state, m.updatedBy)
    if (m.syncedAt) c.uint64.encode(state, m.syncedAt)
  },
  decode(state) {
    const flags = c.uint24.decode(state)

    return {
      id: null,
      title: (flags & 1) !== 0 ? c.string.decode(state) : null,
      description: (flags & 2) !== 0 ? c.string.decode(state) : null,
      path: (flags & 4) !== 0 ? c.string.decode(state) : null,
      duration: (flags & 8) !== 0 ? c.uint64.decode(state) : 0,
      thumbnail: (flags & 16) !== 0 ? c.string.decode(state) : null,
      thumbnailBlobId: (flags & 32) !== 0 ? c.string.decode(state) : null,
      thumbnailBlobsCoreKey: (flags & 64) !== 0 ? c.string.decode(state) : null,
      thumbnailMimeType: (flags & 128) !== 0 ? c.string.decode(state) : null,
      blobId: (flags & 256) !== 0 ? c.string.decode(state) : null,
      blobsCoreKey: (flags & 512) !== 0 ? c.string.decode(state) : null,
      blobDriveKey: (flags & 1024) !== 0 ? c.string.decode(state) : null,
      mimeType: (flags & 2048) !== 0 ? c.string.decode(state) : null,
      size: (flags & 4096) !== 0 ? c.uint64.decode(state) : 0,
      category: (flags & 8192) !== 0 ? c.string.decode(state) : null,
      views: (flags & 16384) !== 0 ? c.uint64.decode(state) : 0,
      uploadedAt: (flags & 32768) !== 0 ? c.uint64.decode(state) : 0,
      uploadedBy: (flags & 65536) !== 0 ? c.string.decode(state) : null,
      updatedAt: (flags & 131072) !== 0 ? c.uint64.decode(state) : 0,
      updatedBy: (flags & 262144) !== 0 ? c.string.decode(state) : null,
      syncedAt: (flags & 524288) !== 0 ? c.uint64.decode(state) : 0
    }
  }
}

// @peartubePublic/channelProfile/hyperdb#3
const encoding9 = {
  preencode(state, m) {
    state.end++ // max flag is 64 so always one byte

    if (version >= 2 && m.profileKind) c.string.preencode(state, m.profileKind)
    if (version >= 2 && m.mediaProvider) c.string.preencode(state, m.mediaProvider)
    if (version >= 2 && m.mediaId) c.string.preencode(state, m.mediaId)
    if (version >= 2 && m.originalLanguage) c.string.preencode(state, m.originalLanguage)
    if (version >= 2 && m.releaseDate) c.uint64.preencode(state, m.releaseDate)
    if (version >= 2 && m.releaseYear) c.uint64.preencode(state, m.releaseYear)
    if (version >= 2 && m.canonicalRevision) c.string.preencode(state, m.canonicalRevision)
  },
  encode(state, m) {
    const flags =
      ((version >= 2 && m.profileKind) ? 1 : 0) |
      ((version >= 2 && m.mediaProvider) ? 2 : 0) |
      ((version >= 2 && m.mediaId) ? 4 : 0) |
      ((version >= 2 && m.originalLanguage) ? 8 : 0) |
      ((version >= 2 && m.releaseDate) ? 16 : 0) |
      ((version >= 2 && m.releaseYear) ? 32 : 0) |
      ((version >= 2 && m.canonicalRevision) ? 64 : 0)

    c.uint.encode(state, flags)

    if (version >= 2 && m.profileKind) c.string.encode(state, m.profileKind)
    if (version >= 2 && m.mediaProvider) c.string.encode(state, m.mediaProvider)
    if (version >= 2 && m.mediaId) c.string.encode(state, m.mediaId)
    if (version >= 2 && m.originalLanguage) c.string.encode(state, m.originalLanguage)
    if (version >= 2 && m.releaseDate) c.uint64.encode(state, m.releaseDate)
    if (version >= 2 && m.releaseYear) c.uint64.encode(state, m.releaseYear)
    if (version >= 2 && m.canonicalRevision) c.string.encode(state, m.canonicalRevision)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      id: null,
      profileKind: (version >= 2 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      mediaProvider: (version >= 2 && (flags & 2) !== 0) ? c.string.decode(state) : null,
      mediaId: (version >= 2 && (flags & 4) !== 0) ? c.string.decode(state) : null,
      originalLanguage: (version >= 2 && (flags & 8) !== 0) ? c.string.decode(state) : null,
      releaseDate: (version >= 2 && (flags & 16) !== 0) ? c.uint64.decode(state) : 0,
      releaseYear: (version >= 2 && (flags & 32) !== 0) ? c.uint64.decode(state) : 0,
      canonicalRevision: (version >= 2 && (flags & 64) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @peartubePublic/contentDetails/hyperdb#4
const encoding10 = {
  preencode(state, m) {
    const flags =
      ((version >= 2 && m.contentKind) ? 1 : 0) |
      ((version >= 2 && m.sourceProvider) ? 2 : 0) |
      ((version >= 2 && m.sourceVideoId) ? 4 : 0) |
      ((version >= 2 && m.identityUrl) ? 8 : 0) |
      ((version >= 2 && m.sourceCreatorId) ? 16 : 0) |
      ((version >= 2 && m.sourceCreatorUrl) ? 32 : 0) |
      ((version >= 2 && m.sourcePublishedAt) ? 64 : 0) |
      ((version >= 2 && m.mediaProvider) ? 128 : 0) |
      ((version >= 2 && m.mediaId) ? 256 : 0) |
      ((version >= 2 && m.seasonNumber) ? 512 : 0) |
      ((version >= 2 && m.episodeNumber) ? 1024 : 0) |
      ((version >= 2 && m.originalAirDate) ? 2048 : 0) |
      ((version >= 2 && m.thumbnailUrl) ? 4096 : 0) |
      ((version >= 2 && m.provenanceVersion) ? 8192 : 0) |
      ((version >= 2 && m.publicationState) ? 16384 : 0) |
      ((version >= 2 && m.contentFingerprint) ? 32768 : 0) |
      ((version >= 2 && m.importIdentityKey) ? 65536 : 0) |
      ((version >= 2 && m.importClaimantId) ? 131072 : 0) |
      ((version >= 2 && m.canonicalVisibility) ? 262144 : 0) |
      ((version >= 2 && m.duplicateOfClaimantId) ? 524288 : 0) |
      ((version >= 3 && m.artwork) ? 1048576 : 0)

    c.uint.preencode(state, flags)

    if (version >= 2 && m.contentKind) c.string.preencode(state, m.contentKind)
    if (version >= 2 && m.sourceProvider) c.string.preencode(state, m.sourceProvider)
    if (version >= 2 && m.sourceVideoId) c.string.preencode(state, m.sourceVideoId)
    if (version >= 2 && m.identityUrl) c.string.preencode(state, m.identityUrl)
    if (version >= 2 && m.sourceCreatorId) c.string.preencode(state, m.sourceCreatorId)
    if (version >= 2 && m.sourceCreatorUrl) c.string.preencode(state, m.sourceCreatorUrl)
    if (version >= 2 && m.sourcePublishedAt) c.uint64.preencode(state, m.sourcePublishedAt)
    if (version >= 2 && m.mediaProvider) c.string.preencode(state, m.mediaProvider)
    if (version >= 2 && m.mediaId) c.string.preencode(state, m.mediaId)
    if (version >= 2 && m.seasonNumber) c.uint64.preencode(state, m.seasonNumber)
    if (version >= 2 && m.episodeNumber) c.uint64.preencode(state, m.episodeNumber)
    if (version >= 2 && m.originalAirDate) c.uint64.preencode(state, m.originalAirDate)
    if (version >= 2 && m.thumbnailUrl) c.string.preencode(state, m.thumbnailUrl)
    if (version >= 2 && m.provenanceVersion) c.string.preencode(state, m.provenanceVersion)
    if (version >= 2 && m.publicationState) c.string.preencode(state, m.publicationState)
    if (version >= 2 && m.contentFingerprint) c.string.preencode(state, m.contentFingerprint)
    if (version >= 2 && m.importIdentityKey) c.string.preencode(state, m.importIdentityKey)
    if (version >= 2 && m.importClaimantId) c.string.preencode(state, m.importClaimantId)
    if (version >= 2 && m.canonicalVisibility) c.string.preencode(state, m.canonicalVisibility)
    if (version >= 2 && m.duplicateOfClaimantId) c.string.preencode(state, m.duplicateOfClaimantId)
    if (version >= 3 && m.artwork) encoding10_21.preencode(state, m.artwork)
  },
  encode(state, m) {
    const flags =
      ((version >= 2 && m.contentKind) ? 1 : 0) |
      ((version >= 2 && m.sourceProvider) ? 2 : 0) |
      ((version >= 2 && m.sourceVideoId) ? 4 : 0) |
      ((version >= 2 && m.identityUrl) ? 8 : 0) |
      ((version >= 2 && m.sourceCreatorId) ? 16 : 0) |
      ((version >= 2 && m.sourceCreatorUrl) ? 32 : 0) |
      ((version >= 2 && m.sourcePublishedAt) ? 64 : 0) |
      ((version >= 2 && m.mediaProvider) ? 128 : 0) |
      ((version >= 2 && m.mediaId) ? 256 : 0) |
      ((version >= 2 && m.seasonNumber) ? 512 : 0) |
      ((version >= 2 && m.episodeNumber) ? 1024 : 0) |
      ((version >= 2 && m.originalAirDate) ? 2048 : 0) |
      ((version >= 2 && m.thumbnailUrl) ? 4096 : 0) |
      ((version >= 2 && m.provenanceVersion) ? 8192 : 0) |
      ((version >= 2 && m.publicationState) ? 16384 : 0) |
      ((version >= 2 && m.contentFingerprint) ? 32768 : 0) |
      ((version >= 2 && m.importIdentityKey) ? 65536 : 0) |
      ((version >= 2 && m.importClaimantId) ? 131072 : 0) |
      ((version >= 2 && m.canonicalVisibility) ? 262144 : 0) |
      ((version >= 2 && m.duplicateOfClaimantId) ? 524288 : 0) |
      ((version >= 3 && m.artwork) ? 1048576 : 0)

    c.uint.encode(state, flags)

    if (version >= 2 && m.contentKind) c.string.encode(state, m.contentKind)
    if (version >= 2 && m.sourceProvider) c.string.encode(state, m.sourceProvider)
    if (version >= 2 && m.sourceVideoId) c.string.encode(state, m.sourceVideoId)
    if (version >= 2 && m.identityUrl) c.string.encode(state, m.identityUrl)
    if (version >= 2 && m.sourceCreatorId) c.string.encode(state, m.sourceCreatorId)
    if (version >= 2 && m.sourceCreatorUrl) c.string.encode(state, m.sourceCreatorUrl)
    if (version >= 2 && m.sourcePublishedAt) c.uint64.encode(state, m.sourcePublishedAt)
    if (version >= 2 && m.mediaProvider) c.string.encode(state, m.mediaProvider)
    if (version >= 2 && m.mediaId) c.string.encode(state, m.mediaId)
    if (version >= 2 && m.seasonNumber) c.uint64.encode(state, m.seasonNumber)
    if (version >= 2 && m.episodeNumber) c.uint64.encode(state, m.episodeNumber)
    if (version >= 2 && m.originalAirDate) c.uint64.encode(state, m.originalAirDate)
    if (version >= 2 && m.thumbnailUrl) c.string.encode(state, m.thumbnailUrl)
    if (version >= 2 && m.provenanceVersion) c.string.encode(state, m.provenanceVersion)
    if (version >= 2 && m.publicationState) c.string.encode(state, m.publicationState)
    if (version >= 2 && m.contentFingerprint) c.string.encode(state, m.contentFingerprint)
    if (version >= 2 && m.importIdentityKey) c.string.encode(state, m.importIdentityKey)
    if (version >= 2 && m.importClaimantId) c.string.encode(state, m.importClaimantId)
    if (version >= 2 && m.canonicalVisibility) c.string.encode(state, m.canonicalVisibility)
    if (version >= 2 && m.duplicateOfClaimantId) c.string.encode(state, m.duplicateOfClaimantId)
    if (version >= 3 && m.artwork) encoding10_21.encode(state, m.artwork)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      id: null,
      contentKind: (version >= 2 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      sourceProvider: (version >= 2 && (flags & 2) !== 0) ? c.string.decode(state) : null,
      sourceVideoId: (version >= 2 && (flags & 4) !== 0) ? c.string.decode(state) : null,
      identityUrl: (version >= 2 && (flags & 8) !== 0) ? c.string.decode(state) : null,
      sourceCreatorId: (version >= 2 && (flags & 16) !== 0) ? c.string.decode(state) : null,
      sourceCreatorUrl: (version >= 2 && (flags & 32) !== 0) ? c.string.decode(state) : null,
      sourcePublishedAt: (version >= 2 && (flags & 64) !== 0) ? c.uint64.decode(state) : 0,
      mediaProvider: (version >= 2 && (flags & 128) !== 0) ? c.string.decode(state) : null,
      mediaId: (version >= 2 && (flags & 256) !== 0) ? c.string.decode(state) : null,
      seasonNumber: (version >= 2 && (flags & 512) !== 0) ? c.uint64.decode(state) : 0,
      episodeNumber: (version >= 2 && (flags & 1024) !== 0) ? c.uint64.decode(state) : 0,
      originalAirDate: (version >= 2 && (flags & 2048) !== 0) ? c.uint64.decode(state) : 0,
      thumbnailUrl: (version >= 2 && (flags & 4096) !== 0) ? c.string.decode(state) : null,
      provenanceVersion: (version >= 2 && (flags & 8192) !== 0) ? c.string.decode(state) : null,
      publicationState: (version >= 2 && (flags & 16384) !== 0) ? c.string.decode(state) : null,
      contentFingerprint: (version >= 2 && (flags & 32768) !== 0) ? c.string.decode(state) : null,
      importIdentityKey: (version >= 2 && (flags & 65536) !== 0) ? c.string.decode(state) : null,
      importClaimantId: (version >= 2 && (flags & 131072) !== 0) ? c.string.decode(state) : null,
      canonicalVisibility: (version >= 2 && (flags & 262144) !== 0) ? c.string.decode(state) : null,
      duplicateOfClaimantId: (version >= 2 && (flags & 524288) !== 0) ? c.string.decode(state) : null,
      artwork: (version >= 3 && (flags & 1048576) !== 0) ? encoding10_21.decode(state) : null
    }
  }
}

// @peartubePublic/channelSource/hyperdb#5
const encoding11 = {
  preencode(state, m) {
    state.end++ // flags are fixed size

    if (version >= 2 && m.sourceId) c.string.preencode(state, m.sourceId)
    if (version >= 2 && m.identityUrl) c.string.preencode(state, m.identityUrl)
    if (version >= 2 && m.handle) c.string.preencode(state, m.handle)
    if (version >= 2 && m.displayName) c.string.preencode(state, m.displayName)
    if (version >= 2 && m.createdAt) c.uint64.preencode(state, m.createdAt)
    if (version >= 2 && m.updatedAt) c.uint64.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags =
      ((version >= 2 && m.sourceId) ? 1 : 0) |
      ((version >= 2 && m.identityUrl) ? 2 : 0) |
      ((version >= 2 && m.handle) ? 4 : 0) |
      ((version >= 2 && m.displayName) ? 8 : 0) |
      ((version >= 2 && m.createdAt) ? 16 : 0) |
      ((version >= 2 && m.updatedAt) ? 32 : 0)

    c.uint8.encode(state, flags)

    if (version >= 2 && m.sourceId) c.string.encode(state, m.sourceId)
    if (version >= 2 && m.identityUrl) c.string.encode(state, m.identityUrl)
    if (version >= 2 && m.handle) c.string.encode(state, m.handle)
    if (version >= 2 && m.displayName) c.string.encode(state, m.displayName)
    if (version >= 2 && m.createdAt) c.uint64.encode(state, m.createdAt)
    if (version >= 2 && m.updatedAt) c.uint64.encode(state, m.updatedAt)
  },
  decode(state) {
    const flags = c.uint8.decode(state)

    return {
      provider: null,
      identityKey: null,
      sourceId: (version >= 2 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      identityUrl: (version >= 2 && (flags & 2) !== 0) ? c.string.decode(state) : null,
      handle: (version >= 2 && (flags & 4) !== 0) ? c.string.decode(state) : null,
      displayName: (version >= 2 && (flags & 8) !== 0) ? c.string.decode(state) : null,
      createdAt: (version >= 2 && (flags & 16) !== 0) ? c.uint64.decode(state) : 0,
      updatedAt: (version >= 2 && (flags & 32) !== 0) ? c.uint64.decode(state) : 0
    }
  }
}

// @peartubePublic/channelArtwork/hyperdb#6
const encoding12 = {
  preencode(state, m) {
    state.end++ // flags are fixed size

    if (version >= 2 && m.blobId) c.string.preencode(state, m.blobId)
    if (version >= 2 && m.blobsCoreKey) c.string.preencode(state, m.blobsCoreKey)
    if (version >= 2 && m.mimeType) c.string.preencode(state, m.mimeType)
    if (version >= 2 && m.remoteUrl) c.string.preencode(state, m.remoteUrl)
    if (version >= 2 && m.updatedAt) c.uint64.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags =
      ((version >= 2 && m.blobId) ? 1 : 0) |
      ((version >= 2 && m.blobsCoreKey) ? 2 : 0) |
      ((version >= 2 && m.mimeType) ? 4 : 0) |
      ((version >= 2 && m.remoteUrl) ? 8 : 0) |
      ((version >= 2 && m.updatedAt) ? 16 : 0)

    c.uint8.encode(state, flags)

    if (version >= 2 && m.blobId) c.string.encode(state, m.blobId)
    if (version >= 2 && m.blobsCoreKey) c.string.encode(state, m.blobsCoreKey)
    if (version >= 2 && m.mimeType) c.string.encode(state, m.mimeType)
    if (version >= 2 && m.remoteUrl) c.string.encode(state, m.remoteUrl)
    if (version >= 2 && m.updatedAt) c.uint64.encode(state, m.updatedAt)
  },
  decode(state) {
    const flags = c.uint8.decode(state)

    return {
      role: null,
      blobId: (version >= 2 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      blobsCoreKey: (version >= 2 && (flags & 2) !== 0) ? c.string.decode(state) : null,
      mimeType: (version >= 2 && (flags & 4) !== 0) ? c.string.decode(state) : null,
      remoteUrl: (version >= 2 && (flags & 8) !== 0) ? c.string.decode(state) : null,
      updatedAt: (version >= 2 && (flags & 16) !== 0) ? c.uint64.decode(state) : 0
    }
  }
}

// @peartubePublic/contentDetails.artwork, deferred due to recusive use
const encoding3_21 = c.array(encoding6)
// @peartubePublic/contentDetails/hyperdb#4.artwork, deferred due to recusive use
const encoding10_21 = encoding3_21

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@peartubePublic/metadata':
      return encoding0
    case '@peartubePublic/video':
      return encoding1
    case '@peartubePublic/channelProfile':
      return encoding2
    case '@peartubePublic/contentDetails':
      return encoding3
    case '@peartubePublic/channelSource':
      return encoding4
    case '@peartubePublic/channelArtwork':
      return encoding5
    case '@peartubePublic/contentArtwork':
      return encoding6
    case '@peartubePublic/metadata/hyperdb#0':
      return encoding7
    case '@peartubePublic/video/hyperdb#1':
      return encoding8
    case '@peartubePublic/channelProfile/hyperdb#3':
      return encoding9
    case '@peartubePublic/contentDetails/hyperdb#4':
      return encoding10
    case '@peartubePublic/channelSource/hyperdb#5':
      return encoding11
    case '@peartubePublic/channelArtwork/hyperdb#6':
      return encoding12
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

export { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
