// This file is autogenerated by the hyperschema compiler
// Schema Version: 3
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 3

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @peartubeChannel/metadata
const encoding0 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    state.end += 2 // flags are fixed size

    if (m.name) c.string.preencode(state, m.name)
    if (m.description) c.string.preencode(state, m.description)
    if (m.avatar) c.string.preencode(state, m.avatar)
    if (m.publicBeeKey) c.string.preencode(state, m.publicBeeKey)
    if (m.commentsDbKey) c.string.preencode(state, m.commentsDbKey)
    if (m.commentsAdminKey) c.string.preencode(state, m.commentsAdminKey)
    if (m.createdAt) c.uint64.preencode(state, m.createdAt)
    if (m.createdBy) c.string.preencode(state, m.createdBy)
    if (m.updatedAt) c.uint64.preencode(state, m.updatedAt)
    if (m.updatedBy) c.string.preencode(state, m.updatedBy)
    if (m.schemaVersion) c.uint64.preencode(state, m.schemaVersion)
    if (m.logicalClock) c.uint64.preencode(state, m.logicalClock)
  },
  encode(state, m) {
    const flags =
      (m.name ? 1 : 0) |
      (m.description ? 2 : 0) |
      (m.avatar ? 4 : 0) |
      (m.publicBeeKey ? 8 : 0) |
      (m.commentsDbKey ? 16 : 0) |
      (m.commentsAdminKey ? 32 : 0) |
      (m.createdAt ? 64 : 0) |
      (m.createdBy ? 128 : 0) |
      (m.updatedAt ? 256 : 0) |
      (m.updatedBy ? 512 : 0) |
      (m.schemaVersion ? 1024 : 0) |
      (m.logicalClock ? 2048 : 0)

    c.string.encode(state, m.key)
    c.uint16.encode(state, flags)

    if (m.name) c.string.encode(state, m.name)
    if (m.description) c.string.encode(state, m.description)
    if (m.avatar) c.string.encode(state, m.avatar)
    if (m.publicBeeKey) c.string.encode(state, m.publicBeeKey)
    if (m.commentsDbKey) c.string.encode(state, m.commentsDbKey)
    if (m.commentsAdminKey) c.string.encode(state, m.commentsAdminKey)
    if (m.createdAt) c.uint64.encode(state, m.createdAt)
    if (m.createdBy) c.string.encode(state, m.createdBy)
    if (m.updatedAt) c.uint64.encode(state, m.updatedAt)
    if (m.updatedBy) c.string.encode(state, m.updatedBy)
    if (m.schemaVersion) c.uint64.encode(state, m.schemaVersion)
    if (m.logicalClock) c.uint64.encode(state, m.logicalClock)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint16.decode(state)

    return {
      key: r0,
      name: (flags & 1) !== 0 ? c.string.decode(state) : null,
      description: (flags & 2) !== 0 ? c.string.decode(state) : null,
      avatar: (flags & 4) !== 0 ? c.string.decode(state) : null,
      publicBeeKey: (flags & 8) !== 0 ? c.string.decode(state) : null,
      commentsDbKey: (flags & 16) !== 0 ? c.string.decode(state) : null,
      commentsAdminKey: (flags & 32) !== 0 ? c.string.decode(state) : null,
      createdAt: (flags & 64) !== 0 ? c.uint64.decode(state) : 0,
      createdBy: (flags & 128) !== 0 ? c.string.decode(state) : null,
      updatedAt: (flags & 256) !== 0 ? c.uint64.decode(state) : 0,
      updatedBy: (flags & 512) !== 0 ? c.string.decode(state) : null,
      schemaVersion: (flags & 1024) !== 0 ? c.uint64.decode(state) : 0,
      logicalClock: (flags & 2048) !== 0 ? c.uint64.decode(state) : 0
    }
  }
}

// @peartubeChannel/writer
const encoding1 = {
  preencode(state, m) {
    c.string.preencode(state, m.keyHex)
    state.end++ // flags are fixed size

    if (m.role) c.string.preencode(state, m.role)
    if (m.deviceName) c.string.preencode(state, m.deviceName)
    if (m.blobDriveKey) c.string.preencode(state, m.blobDriveKey)
    if (m.addedAt) c.uint64.preencode(state, m.addedAt)
    if (m.updatedAt) c.uint64.preencode(state, m.updatedAt)
    if (m.removedAt) c.uint64.preencode(state, m.removedAt)
    if (m.swarmKeyHex) c.string.preencode(state, m.swarmKeyHex)
  },
  encode(state, m) {
    const flags =
      (m.role ? 1 : 0) |
      (m.deviceName ? 2 : 0) |
      (m.blobDriveKey ? 4 : 0) |
      (m.addedAt ? 8 : 0) |
      (m.updatedAt ? 16 : 0) |
      (m.removedAt ? 32 : 0) |
      (m.banned ? 64 : 0) |
      (m.swarmKeyHex ? 128 : 0)

    c.string.encode(state, m.keyHex)
    c.uint8.encode(state, flags)

    if (m.role) c.string.encode(state, m.role)
    if (m.deviceName) c.string.encode(state, m.deviceName)
    if (m.blobDriveKey) c.string.encode(state, m.blobDriveKey)
    if (m.addedAt) c.uint64.encode(state, m.addedAt)
    if (m.updatedAt) c.uint64.encode(state, m.updatedAt)
    if (m.removedAt) c.uint64.encode(state, m.removedAt)
    if (m.swarmKeyHex) c.string.encode(state, m.swarmKeyHex)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint8.decode(state)

    return {
      keyHex: r0,
      role: (flags & 1) !== 0 ? c.string.decode(state) : null,
      deviceName: (flags & 2) !== 0 ? c.string.decode(state) : null,
      blobDriveKey: (flags & 4) !== 0 ? c.string.decode(state) : null,
      addedAt: (flags & 8) !== 0 ? c.uint64.decode(state) : 0,
      updatedAt: (flags & 16) !== 0 ? c.uint64.decode(state) : 0,
      removedAt: (flags & 32) !== 0 ? c.uint64.decode(state) : 0,
      banned: (flags & 64) !== 0,
      swarmKeyHex: (flags & 128) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @peartubeChannel/video
const encoding2 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    state.end += 3 // flags are fixed size

    if (m.title) c.string.preencode(state, m.title)
    if (m.description) c.string.preencode(state, m.description)
    if (m.path) c.string.preencode(state, m.path)
    if (m.duration) c.uint64.preencode(state, m.duration)
    if (m.thumbnail) c.string.preencode(state, m.thumbnail)
    if (m.thumbnailBlobId) c.string.preencode(state, m.thumbnailBlobId)
    if (m.thumbnailBlobsCoreKey) c.string.preencode(state, m.thumbnailBlobsCoreKey)
    if (m.thumbnailMimeType) c.string.preencode(state, m.thumbnailMimeType)
    if (m.blobId) c.string.preencode(state, m.blobId)
    if (m.blobsCoreKey) c.string.preencode(state, m.blobsCoreKey)
    if (m.blobDriveKey) c.string.preencode(state, m.blobDriveKey)
    if (m.mimeType) c.string.preencode(state, m.mimeType)
    if (m.size) c.uint64.preencode(state, m.size)
    if (m.category) c.string.preencode(state, m.category)
    if (m.views) c.uint64.preencode(state, m.views)
    if (m.uploadedAt) c.uint64.preencode(state, m.uploadedAt)
    if (m.uploadedBy) c.string.preencode(state, m.uploadedBy)
    if (m.updatedAt) c.uint64.preencode(state, m.updatedAt)
    if (m.updatedBy) c.string.preencode(state, m.updatedBy)
    if (m.schemaVersion) c.uint64.preencode(state, m.schemaVersion)
    if (m.logicalClock) c.uint64.preencode(state, m.logicalClock)
  },
  encode(state, m) {
    const flags =
      (m.title ? 1 : 0) |
      (m.description ? 2 : 0) |
      (m.path ? 4 : 0) |
      (m.duration ? 8 : 0) |
      (m.thumbnail ? 16 : 0) |
      (m.thumbnailBlobId ? 32 : 0) |
      (m.thumbnailBlobsCoreKey ? 64 : 0) |
      (m.thumbnailMimeType ? 128 : 0) |
      (m.blobId ? 256 : 0) |
      (m.blobsCoreKey ? 512 : 0) |
      (m.blobDriveKey ? 1024 : 0) |
      (m.mimeType ? 2048 : 0) |
      (m.size ? 4096 : 0) |
      (m.category ? 8192 : 0) |
      (m.views ? 16384 : 0) |
      (m.uploadedAt ? 32768 : 0) |
      (m.uploadedBy ? 65536 : 0) |
      (m.updatedAt ? 131072 : 0) |
      (m.updatedBy ? 262144 : 0) |
      (m.schemaVersion ? 524288 : 0) |
      (m.logicalClock ? 1048576 : 0)

    c.string.encode(state, m.id)
    c.uint24.encode(state, flags)

    if (m.title) c.string.encode(state, m.title)
    if (m.description) c.string.encode(state, m.description)
    if (m.path) c.string.encode(state, m.path)
    if (m.duration) c.uint64.encode(state, m.duration)
    if (m.thumbnail) c.string.encode(state, m.thumbnail)
    if (m.thumbnailBlobId) c.string.encode(state, m.thumbnailBlobId)
    if (m.thumbnailBlobsCoreKey) c.string.encode(state, m.thumbnailBlobsCoreKey)
    if (m.thumbnailMimeType) c.string.encode(state, m.thumbnailMimeType)
    if (m.blobId) c.string.encode(state, m.blobId)
    if (m.blobsCoreKey) c.string.encode(state, m.blobsCoreKey)
    if (m.blobDriveKey) c.string.encode(state, m.blobDriveKey)
    if (m.mimeType) c.string.encode(state, m.mimeType)
    if (m.size) c.uint64.encode(state, m.size)
    if (m.category) c.string.encode(state, m.category)
    if (m.views) c.uint64.encode(state, m.views)
    if (m.uploadedAt) c.uint64.encode(state, m.uploadedAt)
    if (m.uploadedBy) c.string.encode(state, m.uploadedBy)
    if (m.updatedAt) c.uint64.encode(state, m.updatedAt)
    if (m.updatedBy) c.string.encode(state, m.updatedBy)
    if (m.schemaVersion) c.uint64.encode(state, m.schemaVersion)
    if (m.logicalClock) c.uint64.encode(state, m.logicalClock)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint24.decode(state)

    return {
      id: r0,
      title: (flags & 1) !== 0 ? c.string.decode(state) : null,
      description: (flags & 2) !== 0 ? c.string.decode(state) : null,
      path: (flags & 4) !== 0 ? c.string.decode(state) : null,
      duration: (flags & 8) !== 0 ? c.uint64.decode(state) : 0,
      thumbnail: (flags & 16) !== 0 ? c.string.decode(state) : null,
      thumbnailBlobId: (flags & 32) !== 0 ? c.string.decode(state) : null,
      thumbnailBlobsCoreKey: (flags & 64) !== 0 ? c.string.decode(state) : null,
      thumbnailMimeType: (flags & 128) !== 0 ? c.string.decode(state) : null,
      blobId: (flags & 256) !== 0 ? c.string.decode(state) : null,
      blobsCoreKey: (flags & 512) !== 0 ? c.string.decode(state) : null,
      blobDriveKey: (flags & 1024) !== 0 ? c.string.decode(state) : null,
      mimeType: (flags & 2048) !== 0 ? c.string.decode(state) : null,
      size: (flags & 4096) !== 0 ? c.uint64.decode(state) : 0,
      category: (flags & 8192) !== 0 ? c.string.decode(state) : null,
      views: (flags & 16384) !== 0 ? c.uint64.decode(state) : 0,
      uploadedAt: (flags & 32768) !== 0 ? c.uint64.decode(state) : 0,
      uploadedBy: (flags & 65536) !== 0 ? c.string.decode(state) : null,
      updatedAt: (flags & 131072) !== 0 ? c.uint64.decode(state) : 0,
      updatedBy: (flags & 262144) !== 0 ? c.string.decode(state) : null,
      schemaVersion: (flags & 524288) !== 0 ? c.uint64.decode(state) : 0,
      logicalClock: (flags & 1048576) !== 0 ? c.uint64.decode(state) : 0
    }
  }
}

// @peartubeChannel/comment
const encoding3 = {
  preencode(state, m) {
    c.string.preencode(state, m.videoId)
    c.string.preencode(state, m.commentId)
    state.end += 2 // flags are fixed size

    if (m.text) c.string.preencode(state, m.text)
    if (m.authorKeyHex) c.string.preencode(state, m.authorKeyHex)
    if (m.timestamp) c.uint64.preencode(state, m.timestamp)
    if (m.parentId) c.string.preencode(state, m.parentId)
    if (m.hiddenBy) c.string.preencode(state, m.hiddenBy)
    if (m.hiddenAt) c.uint64.preencode(state, m.hiddenAt)
    if (m.removedBy) c.string.preencode(state, m.removedBy)
    if (m.removedAt) c.uint64.preencode(state, m.removedAt)
  },
  encode(state, m) {
    const flags =
      (m.text ? 1 : 0) |
      (m.authorKeyHex ? 2 : 0) |
      (m.timestamp ? 4 : 0) |
      (m.parentId ? 8 : 0) |
      (m.hidden ? 16 : 0) |
      (m.hiddenBy ? 32 : 0) |
      (m.hiddenAt ? 64 : 0) |
      (m.removed ? 128 : 0) |
      (m.removedBy ? 256 : 0) |
      (m.removedAt ? 512 : 0)

    c.string.encode(state, m.videoId)
    c.string.encode(state, m.commentId)
    c.uint16.encode(state, flags)

    if (m.text) c.string.encode(state, m.text)
    if (m.authorKeyHex) c.string.encode(state, m.authorKeyHex)
    if (m.timestamp) c.uint64.encode(state, m.timestamp)
    if (m.parentId) c.string.encode(state, m.parentId)
    if (m.hiddenBy) c.string.encode(state, m.hiddenBy)
    if (m.hiddenAt) c.uint64.encode(state, m.hiddenAt)
    if (m.removedBy) c.string.encode(state, m.removedBy)
    if (m.removedAt) c.uint64.encode(state, m.removedAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint16.decode(state)

    return {
      videoId: r0,
      commentId: r1,
      text: (flags & 1) !== 0 ? c.string.decode(state) : null,
      authorKeyHex: (flags & 2) !== 0 ? c.string.decode(state) : null,
      timestamp: (flags & 4) !== 0 ? c.uint64.decode(state) : 0,
      parentId: (flags & 8) !== 0 ? c.string.decode(state) : null,
      hidden: (flags & 16) !== 0,
      hiddenBy: (flags & 32) !== 0 ? c.string.decode(state) : null,
      hiddenAt: (flags & 64) !== 0 ? c.uint64.decode(state) : 0,
      removed: (flags & 128) !== 0,
      removedBy: (flags & 256) !== 0 ? c.string.decode(state) : null,
      removedAt: (flags & 512) !== 0 ? c.uint64.decode(state) : 0
    }
  }
}

// @peartubeChannel/reaction
const encoding4 = {
  preencode(state, m) {
    c.string.preencode(state, m.videoId)
    c.string.preencode(state, m.authorKeyHex)
    state.end++ // flags are fixed size

    if (m.reactionType) c.string.preencode(state, m.reactionType)
    if (m.timestamp) c.uint64.preencode(state, m.timestamp)
  },
  encode(state, m) {
    const flags = (m.reactionType ? 1 : 0) | (m.timestamp ? 2 : 0)

    c.string.encode(state, m.videoId)
    c.string.encode(state, m.authorKeyHex)
    c.uint8.encode(state, flags)

    if (m.reactionType) c.string.encode(state, m.reactionType)
    if (m.timestamp) c.uint64.encode(state, m.timestamp)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint8.decode(state)

    return {
      videoId: r0,
      authorKeyHex: r1,
      reactionType: (flags & 1) !== 0 ? c.string.decode(state) : null,
      timestamp: (flags & 2) !== 0 ? c.uint64.decode(state) : 0
    }
  }
}

// @peartubeChannel/invite
const encoding5 = {
  preencode(state, m) {
    c.string.preencode(state, m.idHex)
    state.end++ // flags are fixed size

    if (m.inviteZ32) c.string.preencode(state, m.inviteZ32)
    if (m.publicKeyHex) c.string.preencode(state, m.publicKeyHex)
    if (m.expires) c.uint64.preencode(state, m.expires)
    if (m.createdAt) c.uint64.preencode(state, m.createdAt)
  },
  encode(state, m) {
    const flags =
      (m.inviteZ32 ? 1 : 0) |
      (m.publicKeyHex ? 2 : 0) |
      (m.expires ? 4 : 0) |
      (m.createdAt ? 8 : 0) |
      (m.current ? 16 : 0)

    c.string.encode(state, m.idHex)
    c.uint8.encode(state, flags)

    if (m.inviteZ32) c.string.encode(state, m.inviteZ32)
    if (m.publicKeyHex) c.string.encode(state, m.publicKeyHex)
    if (m.expires) c.uint64.encode(state, m.expires)
    if (m.createdAt) c.uint64.encode(state, m.createdAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint8.decode(state)

    return {
      idHex: r0,
      inviteZ32: (flags & 1) !== 0 ? c.string.decode(state) : null,
      publicKeyHex: (flags & 2) !== 0 ? c.string.decode(state) : null,
      expires: (flags & 4) !== 0 ? c.uint64.decode(state) : 0,
      createdAt: (flags & 8) !== 0 ? c.uint64.decode(state) : 0,
      current: (flags & 16) !== 0
    }
  }
}

// @peartubeChannel/watchEvent
const encoding6 = {
  preencode(state, m) {
    c.string.preencode(state, m.videoId)
    c.string.preencode(state, m.eventId)
    state.end++ // flags are fixed size

    if (m.channelKey) c.string.preencode(state, m.channelKey)
    if (m.watcherKeyHex) c.string.preencode(state, m.watcherKeyHex)
    if (m.duration) c.uint64.preencode(state, m.duration)
    if (m.timestamp) c.uint64.preencode(state, m.timestamp)
  },
  encode(state, m) {
    const flags =
      (m.channelKey ? 1 : 0) |
      (m.watcherKeyHex ? 2 : 0) |
      (m.duration ? 4 : 0) |
      (m.completed ? 8 : 0) |
      (m.timestamp ? 16 : 0)

    c.string.encode(state, m.videoId)
    c.string.encode(state, m.eventId)
    c.uint8.encode(state, flags)

    if (m.channelKey) c.string.encode(state, m.channelKey)
    if (m.watcherKeyHex) c.string.encode(state, m.watcherKeyHex)
    if (m.duration) c.uint64.encode(state, m.duration)
    if (m.timestamp) c.uint64.encode(state, m.timestamp)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint8.decode(state)

    return {
      videoId: r0,
      eventId: r1,
      channelKey: (flags & 1) !== 0 ? c.string.decode(state) : null,
      watcherKeyHex: (flags & 2) !== 0 ? c.string.decode(state) : null,
      duration: (flags & 4) !== 0 ? c.uint64.decode(state) : 0,
      completed: (flags & 8) !== 0,
      timestamp: (flags & 16) !== 0 ? c.uint64.decode(state) : 0
    }
  }
}

// @peartubeChannel/vectorIndex
const encoding7 = {
  preencode(state, m) {
    c.string.preencode(state, m.videoId)
    state.end++ // flags are fixed size

    if (m.vector) c.string.preencode(state, m.vector)
    if (m.text) c.string.preencode(state, m.text)
    if (m.metadata) c.string.preencode(state, m.metadata)
    if (m.indexedAt) c.uint64.preencode(state, m.indexedAt)
  },
  encode(state, m) {
    const flags =
      (m.vector ? 1 : 0) | (m.text ? 2 : 0) | (m.metadata ? 4 : 0) | (m.indexedAt ? 8 : 0)

    c.string.encode(state, m.videoId)
    c.uint8.encode(state, flags)

    if (m.vector) c.string.encode(state, m.vector)
    if (m.text) c.string.encode(state, m.text)
    if (m.metadata) c.string.encode(state, m.metadata)
    if (m.indexedAt) c.uint64.encode(state, m.indexedAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint8.decode(state)

    return {
      videoId: r0,
      vector: (flags & 1) !== 0 ? c.string.decode(state) : null,
      text: (flags & 2) !== 0 ? c.string.decode(state) : null,
      metadata: (flags & 4) !== 0 ? c.string.decode(state) : null,
      indexedAt: (flags & 8) !== 0 ? c.uint64.decode(state) : 0
    }
  }
}

// @peartubeChannel/channelProfile
const encoding8 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    state.end++ // max flag is 32 so always one byte

    if (version >= 2 && m.profileKind) c.string.preencode(state, m.profileKind)
    if (version >= 2 && m.mediaProvider) c.string.preencode(state, m.mediaProvider)
    if (version >= 2 && m.mediaId) c.string.preencode(state, m.mediaId)
    if (version >= 2 && m.originalLanguage) c.string.preencode(state, m.originalLanguage)
    if (version >= 2 && m.releaseDate) c.uint64.preencode(state, m.releaseDate)
    if (version >= 2 && m.releaseYear) c.uint64.preencode(state, m.releaseYear)
  },
  encode(state, m) {
    const flags =
      ((version >= 2 && m.profileKind) ? 1 : 0) |
      ((version >= 2 && m.mediaProvider) ? 2 : 0) |
      ((version >= 2 && m.mediaId) ? 4 : 0) |
      ((version >= 2 && m.originalLanguage) ? 8 : 0) |
      ((version >= 2 && m.releaseDate) ? 16 : 0) |
      ((version >= 2 && m.releaseYear) ? 32 : 0)

    c.string.encode(state, m.id)
    c.uint.encode(state, flags)

    if (version >= 2 && m.profileKind) c.string.encode(state, m.profileKind)
    if (version >= 2 && m.mediaProvider) c.string.encode(state, m.mediaProvider)
    if (version >= 2 && m.mediaId) c.string.encode(state, m.mediaId)
    if (version >= 2 && m.originalLanguage) c.string.encode(state, m.originalLanguage)
    if (version >= 2 && m.releaseDate) c.uint64.encode(state, m.releaseDate)
    if (version >= 2 && m.releaseYear) c.uint64.encode(state, m.releaseYear)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      profileKind: (version >= 2 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      mediaProvider: (version >= 2 && (flags & 2) !== 0) ? c.string.decode(state) : null,
      mediaId: (version >= 2 && (flags & 4) !== 0) ? c.string.decode(state) : null,
      originalLanguage: (version >= 2 && (flags & 8) !== 0) ? c.string.decode(state) : null,
      releaseDate: (version >= 2 && (flags & 16) !== 0) ? c.uint64.decode(state) : 0,
      releaseYear: (version >= 2 && (flags & 32) !== 0) ? c.uint64.decode(state) : 0
    }
  }
}

// @peartubeChannel/contentDetails
const encoding9 = {
  preencode(state, m) {
    const flags =
      ((version >= 2 && m.contentKind) ? 1 : 0) |
      ((version >= 2 && m.sourceProvider) ? 2 : 0) |
      ((version >= 2 && m.sourceVideoId) ? 4 : 0) |
      ((version >= 2 && m.identityUrl) ? 8 : 0) |
      ((version >= 2 && m.sourceCreatorId) ? 16 : 0) |
      ((version >= 2 && m.sourceCreatorUrl) ? 32 : 0) |
      ((version >= 2 && m.sourcePublishedAt) ? 64 : 0) |
      ((version >= 2 && m.mediaProvider) ? 128 : 0) |
      ((version >= 2 && m.mediaId) ? 256 : 0) |
      ((version >= 2 && m.seasonNumber) ? 512 : 0) |
      ((version >= 2 && m.episodeNumber) ? 1024 : 0) |
      ((version >= 2 && m.originalAirDate) ? 2048 : 0) |
      ((version >= 2 && m.thumbnailUrl) ? 4096 : 0) |
      ((version >= 2 && m.provenanceVersion) ? 8192 : 0) |
      ((version >= 2 && m.publicationState) ? 16384 : 0) |
      ((version >= 2 && m.contentFingerprint) ? 32768 : 0) |
      ((version >= 2 && m.importIdentityKey) ? 65536 : 0) |
      ((version >= 2 && m.importClaimantId) ? 131072 : 0) |
      ((version >= 3 && m.artwork) ? 262144 : 0) |
      ((version >= 3 && m.publication) ? 524288 : 0)

    c.string.preencode(state, m.id)
    c.uint.preencode(state, flags)

    if (version >= 2 && m.contentKind) c.string.preencode(state, m.contentKind)
    if (version >= 2 && m.sourceProvider) c.string.preencode(state, m.sourceProvider)
    if (version >= 2 && m.sourceVideoId) c.string.preencode(state, m.sourceVideoId)
    if (version >= 2 && m.identityUrl) c.string.preencode(state, m.identityUrl)
    if (version >= 2 && m.sourceCreatorId) c.string.preencode(state, m.sourceCreatorId)
    if (version >= 2 && m.sourceCreatorUrl) c.string.preencode(state, m.sourceCreatorUrl)
    if (version >= 2 && m.sourcePublishedAt) c.uint64.preencode(state, m.sourcePublishedAt)
    if (version >= 2 && m.mediaProvider) c.string.preencode(state, m.mediaProvider)
    if (version >= 2 && m.mediaId) c.string.preencode(state, m.mediaId)
    if (version >= 2 && m.seasonNumber) c.uint64.preencode(state, m.seasonNumber)
    if (version >= 2 && m.episodeNumber) c.uint64.preencode(state, m.episodeNumber)
    if (version >= 2 && m.originalAirDate) c.uint64.preencode(state, m.originalAirDate)
    if (version >= 2 && m.thumbnailUrl) c.string.preencode(state, m.thumbnailUrl)
    if (version >= 2 && m.provenanceVersion) c.string.preencode(state, m.provenanceVersion)
    if (version >= 2 && m.publicationState) c.string.preencode(state, m.publicationState)
    if (version >= 2 && m.contentFingerprint) c.string.preencode(state, m.contentFingerprint)
    if (version >= 2 && m.importIdentityKey) c.string.preencode(state, m.importIdentityKey)
    if (version >= 2 && m.importClaimantId) c.string.preencode(state, m.importClaimantId)
    if (version >= 3 && m.artwork) encoding9_19.preencode(state, m.artwork)
    if (version >= 3 && m.publication) encoding9_20.preencode(state, m.publication)
  },
  encode(state, m) {
    const flags =
      ((version >= 2 && m.contentKind) ? 1 : 0) |
      ((version >= 2 && m.sourceProvider) ? 2 : 0) |
      ((version >= 2 && m.sourceVideoId) ? 4 : 0) |
      ((version >= 2 && m.identityUrl) ? 8 : 0) |
      ((version >= 2 && m.sourceCreatorId) ? 16 : 0) |
      ((version >= 2 && m.sourceCreatorUrl) ? 32 : 0) |
      ((version >= 2 && m.sourcePublishedAt) ? 64 : 0) |
      ((version >= 2 && m.mediaProvider) ? 128 : 0) |
      ((version >= 2 && m.mediaId) ? 256 : 0) |
      ((version >= 2 && m.seasonNumber) ? 512 : 0) |
      ((version >= 2 && m.episodeNumber) ? 1024 : 0) |
      ((version >= 2 && m.originalAirDate) ? 2048 : 0) |
      ((version >= 2 && m.thumbnailUrl) ? 4096 : 0) |
      ((version >= 2 && m.provenanceVersion) ? 8192 : 0) |
      ((version >= 2 && m.publicationState) ? 16384 : 0) |
      ((version >= 2 && m.contentFingerprint) ? 32768 : 0) |
      ((version >= 2 && m.importIdentityKey) ? 65536 : 0) |
      ((version >= 2 && m.importClaimantId) ? 131072 : 0) |
      ((version >= 3 && m.artwork) ? 262144 : 0) |
      ((version >= 3 && m.publication) ? 524288 : 0)

    c.string.encode(state, m.id)
    c.uint.encode(state, flags)

    if (version >= 2 && m.contentKind) c.string.encode(state, m.contentKind)
    if (version >= 2 && m.sourceProvider) c.string.encode(state, m.sourceProvider)
    if (version >= 2 && m.sourceVideoId) c.string.encode(state, m.sourceVideoId)
    if (version >= 2 && m.identityUrl) c.string.encode(state, m.identityUrl)
    if (version >= 2 && m.sourceCreatorId) c.string.encode(state, m.sourceCreatorId)
    if (version >= 2 && m.sourceCreatorUrl) c.string.encode(state, m.sourceCreatorUrl)
    if (version >= 2 && m.sourcePublishedAt) c.uint64.encode(state, m.sourcePublishedAt)
    if (version >= 2 && m.mediaProvider) c.string.encode(state, m.mediaProvider)
    if (version >= 2 && m.mediaId) c.string.encode(state, m.mediaId)
    if (version >= 2 && m.seasonNumber) c.uint64.encode(state, m.seasonNumber)
    if (version >= 2 && m.episodeNumber) c.uint64.encode(state, m.episodeNumber)
    if (version >= 2 && m.originalAirDate) c.uint64.encode(state, m.originalAirDate)
    if (version >= 2 && m.thumbnailUrl) c.string.encode(state, m.thumbnailUrl)
    if (version >= 2 && m.provenanceVersion) c.string.encode(state, m.provenanceVersion)
    if (version >= 2 && m.publicationState) c.string.encode(state, m.publicationState)
    if (version >= 2 && m.contentFingerprint) c.string.encode(state, m.contentFingerprint)
    if (version >= 2 && m.importIdentityKey) c.string.encode(state, m.importIdentityKey)
    if (version >= 2 && m.importClaimantId) c.string.encode(state, m.importClaimantId)
    if (version >= 3 && m.artwork) encoding9_19.encode(state, m.artwork)
    if (version >= 3 && m.publication) encoding9_20.encode(state, m.publication)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      contentKind: (version >= 2 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      sourceProvider: (version >= 2 && (flags & 2) !== 0) ? c.string.decode(state) : null,
      sourceVideoId: (version >= 2 && (flags & 4) !== 0) ? c.string.decode(state) : null,
      identityUrl: (version >= 2 && (flags & 8) !== 0) ? c.string.decode(state) : null,
      sourceCreatorId: (version >= 2 && (flags & 16) !== 0) ? c.string.decode(state) : null,
      sourceCreatorUrl: (version >= 2 && (flags & 32) !== 0) ? c.string.decode(state) : null,
      sourcePublishedAt: (version >= 2 && (flags & 64) !== 0) ? c.uint64.decode(state) : 0,
      mediaProvider: (version >= 2 && (flags & 128) !== 0) ? c.string.decode(state) : null,
      mediaId: (version >= 2 && (flags & 256) !== 0) ? c.string.decode(state) : null,
      seasonNumber: (version >= 2 && (flags & 512) !== 0) ? c.uint64.decode(state) : 0,
      episodeNumber: (version >= 2 && (flags & 1024) !== 0) ? c.uint64.decode(state) : 0,
      originalAirDate: (version >= 2 && (flags & 2048) !== 0) ? c.uint64.decode(state) : 0,
      thumbnailUrl: (version >= 2 && (flags & 4096) !== 0) ? c.string.decode(state) : null,
      provenanceVersion: (version >= 2 && (flags & 8192) !== 0) ? c.string.decode(state) : null,
      publicationState: (version >= 2 && (flags & 16384) !== 0) ? c.string.decode(state) : null,
      contentFingerprint: (version >= 2 && (flags & 32768) !== 0) ? c.string.decode(state) : null,
      importIdentityKey: (version >= 2 && (flags & 65536) !== 0) ? c.string.decode(state) : null,
      importClaimantId: (version >= 2 && (flags & 131072) !== 0) ? c.string.decode(state) : null,
      artwork: (version >= 3 && (flags & 262144) !== 0) ? encoding9_19.decode(state) : null,
      publication: (version >= 3 && (flags & 524288) !== 0) ? encoding9_20.decode(state) : null
    }
  }
}

// @peartubeChannel/channelSource
const encoding10 = {
  preencode(state, m) {
    c.string.preencode(state, m.provider)
    c.string.preencode(state, m.identityKey)
    state.end++ // flags are fixed size

    if (version >= 2 && m.sourceId) c.string.preencode(state, m.sourceId)
    if (version >= 2 && m.identityUrl) c.string.preencode(state, m.identityUrl)
    if (version >= 2 && m.handle) c.string.preencode(state, m.handle)
    if (version >= 2 && m.displayName) c.string.preencode(state, m.displayName)
    if (version >= 2 && m.createdAt) c.uint64.preencode(state, m.createdAt)
    if (version >= 2 && m.updatedAt) c.uint64.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags =
      ((version >= 2 && m.sourceId) ? 1 : 0) |
      ((version >= 2 && m.identityUrl) ? 2 : 0) |
      ((version >= 2 && m.handle) ? 4 : 0) |
      ((version >= 2 && m.displayName) ? 8 : 0) |
      ((version >= 2 && m.createdAt) ? 16 : 0) |
      ((version >= 2 && m.updatedAt) ? 32 : 0)

    c.string.encode(state, m.provider)
    c.string.encode(state, m.identityKey)
    c.uint8.encode(state, flags)

    if (version >= 2 && m.sourceId) c.string.encode(state, m.sourceId)
    if (version >= 2 && m.identityUrl) c.string.encode(state, m.identityUrl)
    if (version >= 2 && m.handle) c.string.encode(state, m.handle)
    if (version >= 2 && m.displayName) c.string.encode(state, m.displayName)
    if (version >= 2 && m.createdAt) c.uint64.encode(state, m.createdAt)
    if (version >= 2 && m.updatedAt) c.uint64.encode(state, m.updatedAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint8.decode(state)

    return {
      provider: r0,
      identityKey: r1,
      sourceId: (version >= 2 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      identityUrl: (version >= 2 && (flags & 2) !== 0) ? c.string.decode(state) : null,
      handle: (version >= 2 && (flags & 4) !== 0) ? c.string.decode(state) : null,
      displayName: (version >= 2 && (flags & 8) !== 0) ? c.string.decode(state) : null,
      createdAt: (version >= 2 && (flags & 16) !== 0) ? c.uint64.decode(state) : 0,
      updatedAt: (version >= 2 && (flags & 32) !== 0) ? c.uint64.decode(state) : 0
    }
  }
}

// @peartubeChannel/channelArtwork
const encoding11 = {
  preencode(state, m) {
    c.string.preencode(state, m.role)
    state.end++ // flags are fixed size

    if (version >= 2 && m.blobId) c.string.preencode(state, m.blobId)
    if (version >= 2 && m.blobsCoreKey) c.string.preencode(state, m.blobsCoreKey)
    if (version >= 2 && m.mimeType) c.string.preencode(state, m.mimeType)
    if (version >= 2 && m.remoteUrl) c.string.preencode(state, m.remoteUrl)
    if (version >= 2 && m.updatedAt) c.uint64.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags =
      ((version >= 2 && m.blobId) ? 1 : 0) |
      ((version >= 2 && m.blobsCoreKey) ? 2 : 0) |
      ((version >= 2 && m.mimeType) ? 4 : 0) |
      ((version >= 2 && m.remoteUrl) ? 8 : 0) |
      ((version >= 2 && m.updatedAt) ? 16 : 0)

    c.string.encode(state, m.role)
    c.uint8.encode(state, flags)

    if (version >= 2 && m.blobId) c.string.encode(state, m.blobId)
    if (version >= 2 && m.blobsCoreKey) c.string.encode(state, m.blobsCoreKey)
    if (version >= 2 && m.mimeType) c.string.encode(state, m.mimeType)
    if (version >= 2 && m.remoteUrl) c.string.encode(state, m.remoteUrl)
    if (version >= 2 && m.updatedAt) c.uint64.encode(state, m.updatedAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint8.decode(state)

    return {
      role: r0,
      blobId: (version >= 2 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      blobsCoreKey: (version >= 2 && (flags & 2) !== 0) ? c.string.decode(state) : null,
      mimeType: (version >= 2 && (flags & 4) !== 0) ? c.string.decode(state) : null,
      remoteUrl: (version >= 2 && (flags & 8) !== 0) ? c.string.decode(state) : null,
      updatedAt: (version >= 2 && (flags & 16) !== 0) ? c.uint64.decode(state) : 0
    }
  }
}

// @peartubeChannel/importClaim
const encoding12 = {
  preencode(state, m) {
    c.string.preencode(state, m.identityKey)
    c.string.preencode(state, m.claimantId)
    state.end++ // flags are fixed size

    if (version >= 2 && m.jobId) c.string.preencode(state, m.jobId)
    if (version >= 2 && m.writerKey) c.string.preencode(state, m.writerKey)
    if (version >= 2 && m.videoId) c.string.preencode(state, m.videoId)
    if (version >= 2 && m.state) c.string.preencode(state, m.state)
    if (version >= 2 && m.createdAt) c.uint64.preencode(state, m.createdAt)
    if (version >= 2 && m.updatedAt) c.uint64.preencode(state, m.updatedAt)
    if (version >= 2 && m.releasedAt) c.uint64.preencode(state, m.releasedAt)
  },
  encode(state, m) {
    const flags =
      ((version >= 2 && m.jobId) ? 1 : 0) |
      ((version >= 2 && m.writerKey) ? 2 : 0) |
      ((version >= 2 && m.videoId) ? 4 : 0) |
      ((version >= 2 && m.state) ? 8 : 0) |
      ((version >= 2 && m.createdAt) ? 16 : 0) |
      ((version >= 2 && m.updatedAt) ? 32 : 0) |
      ((version >= 2 && m.releasedAt) ? 64 : 0)

    c.string.encode(state, m.identityKey)
    c.string.encode(state, m.claimantId)
    c.uint8.encode(state, flags)

    if (version >= 2 && m.jobId) c.string.encode(state, m.jobId)
    if (version >= 2 && m.writerKey) c.string.encode(state, m.writerKey)
    if (version >= 2 && m.videoId) c.string.encode(state, m.videoId)
    if (version >= 2 && m.state) c.string.encode(state, m.state)
    if (version >= 2 && m.createdAt) c.uint64.encode(state, m.createdAt)
    if (version >= 2 && m.updatedAt) c.uint64.encode(state, m.updatedAt)
    if (version >= 2 && m.releasedAt) c.uint64.encode(state, m.releasedAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint8.decode(state)

    return {
      identityKey: r0,
      claimantId: r1,
      jobId: (version >= 2 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      writerKey: (version >= 2 && (flags & 2) !== 0) ? c.string.decode(state) : null,
      videoId: (version >= 2 && (flags & 4) !== 0) ? c.string.decode(state) : null,
      state: (version >= 2 && (flags & 8) !== 0) ? c.string.decode(state) : null,
      createdAt: (version >= 2 && (flags & 16) !== 0) ? c.uint64.decode(state) : 0,
      updatedAt: (version >= 2 && (flags & 32) !== 0) ? c.uint64.decode(state) : 0,
      releasedAt: (version >= 2 && (flags & 64) !== 0) ? c.uint64.decode(state) : 0
    }
  }
}

// @peartubeChannel/contentArtwork
const encoding13 = {
  preencode(state, m) {
    c.string.preencode(state, m.role)
    state.end++ // flags are fixed size

    if (version >= 3 && m.blobId) c.string.preencode(state, m.blobId)
    if (version >= 3 && m.blobsCoreKey) c.string.preencode(state, m.blobsCoreKey)
    if (version >= 3 && m.mimeType) c.string.preencode(state, m.mimeType)
    if (version >= 3 && m.remoteUrl) c.string.preencode(state, m.remoteUrl)
  },
  encode(state, m) {
    const flags =
      ((version >= 3 && m.blobId) ? 1 : 0) |
      ((version >= 3 && m.blobsCoreKey) ? 2 : 0) |
      ((version >= 3 && m.mimeType) ? 4 : 0) |
      ((version >= 3 && m.remoteUrl) ? 8 : 0)

    c.string.encode(state, m.role)
    c.uint8.encode(state, flags)

    if (version >= 3 && m.blobId) c.string.encode(state, m.blobId)
    if (version >= 3 && m.blobsCoreKey) c.string.encode(state, m.blobsCoreKey)
    if (version >= 3 && m.mimeType) c.string.encode(state, m.mimeType)
    if (version >= 3 && m.remoteUrl) c.string.encode(state, m.remoteUrl)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint8.decode(state)

    return {
      role: r0,
      blobId: (version >= 3 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      blobsCoreKey: (version >= 3 && (flags & 2) !== 0) ? c.string.decode(state) : null,
      mimeType: (version >= 3 && (flags & 4) !== 0) ? c.string.decode(state) : null,
      remoteUrl: (version >= 3 && (flags & 8) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @peartubeChannel/immutablePublication
const encoding14 = {
  preencode(state, m) {
    const flags =
      ((version >= 3 && m.publicationId) ? 1 : 0) |
      ((version >= 3 && m.manifestId) ? 2 : 0) |
      ((version >= 3 && m.renditionId) ? 4 : 0) |
      ((version >= 3 && m.assetId) ? 8 : 0) |
      ((version >= 3 && m.coreKey) ? 16 : 0) |
      ((version >= 3 && m.publisherId) ? 32 : 0) |
      ((version >= 3 && m.sequence) ? 64 : 0) |
      ((version >= 3 && m.metadataClaimId) ? 128 : 0) |
      ((version >= 3 && m.availabilityClaimId) ? 256 : 0) |
      ((version >= 3 && m.publicationOperationId) ? 512 : 0) |
      ((version >= 3 && m.metadataClaimOperationId) ? 1024 : 0) |
      ((version >= 3 && m.availabilityClaimOperationId) ? 2048 : 0) |
      ((version >= 3 && m.manifestHex) ? 4096 : 0)

    c.uint.preencode(state, flags)

    if (version >= 3 && m.publicationId) c.string.preencode(state, m.publicationId)
    if (version >= 3 && m.manifestId) c.string.preencode(state, m.manifestId)
    if (version >= 3 && m.renditionId) c.string.preencode(state, m.renditionId)
    if (version >= 3 && m.assetId) c.string.preencode(state, m.assetId)
    if (version >= 3 && m.coreKey) c.string.preencode(state, m.coreKey)
    if (version >= 3 && m.publisherId) c.string.preencode(state, m.publisherId)
    if (version >= 3 && m.sequence) c.uint64.preencode(state, m.sequence)
    if (version >= 3 && m.metadataClaimId) c.string.preencode(state, m.metadataClaimId)
    if (version >= 3 && m.availabilityClaimId) c.string.preencode(state, m.availabilityClaimId)
    if (version >= 3 && m.publicationOperationId) c.string.preencode(state, m.publicationOperationId)
    if (version >= 3 && m.metadataClaimOperationId) c.string.preencode(state, m.metadataClaimOperationId)
    if (version >= 3 && m.availabilityClaimOperationId) c.string.preencode(state, m.availabilityClaimOperationId)
    if (version >= 3 && m.manifestHex) c.string.preencode(state, m.manifestHex)
  },
  encode(state, m) {
    const flags =
      ((version >= 3 && m.publicationId) ? 1 : 0) |
      ((version >= 3 && m.manifestId) ? 2 : 0) |
      ((version >= 3 && m.renditionId) ? 4 : 0) |
      ((version >= 3 && m.assetId) ? 8 : 0) |
      ((version >= 3 && m.coreKey) ? 16 : 0) |
      ((version >= 3 && m.publisherId) ? 32 : 0) |
      ((version >= 3 && m.sequence) ? 64 : 0) |
      ((version >= 3 && m.metadataClaimId) ? 128 : 0) |
      ((version >= 3 && m.availabilityClaimId) ? 256 : 0) |
      ((version >= 3 && m.publicationOperationId) ? 512 : 0) |
      ((version >= 3 && m.metadataClaimOperationId) ? 1024 : 0) |
      ((version >= 3 && m.availabilityClaimOperationId) ? 2048 : 0) |
      ((version >= 3 && m.manifestHex) ? 4096 : 0)

    c.uint.encode(state, flags)

    if (version >= 3 && m.publicationId) c.string.encode(state, m.publicationId)
    if (version >= 3 && m.manifestId) c.string.encode(state, m.manifestId)
    if (version >= 3 && m.renditionId) c.string.encode(state, m.renditionId)
    if (version >= 3 && m.assetId) c.string.encode(state, m.assetId)
    if (version >= 3 && m.coreKey) c.string.encode(state, m.coreKey)
    if (version >= 3 && m.publisherId) c.string.encode(state, m.publisherId)
    if (version >= 3 && m.sequence) c.uint64.encode(state, m.sequence)
    if (version >= 3 && m.metadataClaimId) c.string.encode(state, m.metadataClaimId)
    if (version >= 3 && m.availabilityClaimId) c.string.encode(state, m.availabilityClaimId)
    if (version >= 3 && m.publicationOperationId) c.string.encode(state, m.publicationOperationId)
    if (version >= 3 && m.metadataClaimOperationId) c.string.encode(state, m.metadataClaimOperationId)
    if (version >= 3 && m.availabilityClaimOperationId) c.string.encode(state, m.availabilityClaimOperationId)
    if (version >= 3 && m.manifestHex) c.string.encode(state, m.manifestHex)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      publicationId: (version >= 3 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      manifestId: (version >= 3 && (flags & 2) !== 0) ? c.string.decode(state) : null,
      renditionId: (version >= 3 && (flags & 4) !== 0) ? c.string.decode(state) : null,
      assetId: (version >= 3 && (flags & 8) !== 0) ? c.string.decode(state) : null,
      coreKey: (version >= 3 && (flags & 16) !== 0) ? c.string.decode(state) : null,
      publisherId: (version >= 3 && (flags & 32) !== 0) ? c.string.decode(state) : null,
      sequence: (version >= 3 && (flags & 64) !== 0) ? c.uint64.decode(state) : 0,
      metadataClaimId: (version >= 3 && (flags & 128) !== 0) ? c.string.decode(state) : null,
      availabilityClaimId: (version >= 3 && (flags & 256) !== 0) ? c.string.decode(state) : null,
      publicationOperationId: (version >= 3 && (flags & 512) !== 0) ? c.string.decode(state) : null,
      metadataClaimOperationId: (version >= 3 && (flags & 1024) !== 0) ? c.string.decode(state) : null,
      availabilityClaimOperationId: (version >= 3 && (flags & 2048) !== 0) ? c.string.decode(state) : null,
      manifestHex: (version >= 3 && (flags & 4096) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @peartubeChannel/publicationOperationFrames
const encoding15 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.publicationOperationFramesHex)
  },
  encode(state, m) {
    c.string.encode(state, m.id)
    c.string.encode(state, m.publicationOperationFramesHex)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)

    return {
      id: r0,
      publicationOperationFramesHex: r1
    }
  }
}

// @peartubeChannel/contentDetails.artwork, deferred due to recusive use
const encoding9_19 = c.array(encoding13)
// @peartubeChannel/contentDetails.publication, deferred due to recusive use
const encoding9_20 = c.frame(encoding14)

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@peartubeChannel/metadata':
      return encoding0
    case '@peartubeChannel/writer':
      return encoding1
    case '@peartubeChannel/video':
      return encoding2
    case '@peartubeChannel/comment':
      return encoding3
    case '@peartubeChannel/reaction':
      return encoding4
    case '@peartubeChannel/invite':
      return encoding5
    case '@peartubeChannel/watchEvent':
      return encoding6
    case '@peartubeChannel/vectorIndex':
      return encoding7
    case '@peartubeChannel/channelProfile':
      return encoding8
    case '@peartubeChannel/contentDetails':
      return encoding9
    case '@peartubeChannel/channelSource':
      return encoding10
    case '@peartubeChannel/channelArtwork':
      return encoding11
    case '@peartubeChannel/importClaim':
      return encoding12
    case '@peartubeChannel/contentArtwork':
      return encoding13
    case '@peartubeChannel/immutablePublication':
      return encoding14
    case '@peartubeChannel/publicationOperationFrames':
      return encoding15
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
