// This file is autogenerated by the hyperdb compiler
/* eslint-disable camelcase */

import { IndexEncoder, c, b4a } from 'hyperdb/runtime'
import { version, getEncoding, setVersion } from './messages.js'

const versions = { schema: version, db: 2 }

// '@peartubeIndex/sourceRecords' collection key
const collection0_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.UINT,
  IndexEncoder.STRING
], { prefix: 0 })

function collection0_indexify (record) {
  const arr = []

  const a0 = record.publisherId
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.catalogEpoch
  if (a1 === undefined) return arr
  arr.push(a1)

  const a2 = record.recordId
  if (a2 === undefined) return arr
  arr.push(a2)

  return arr
}

// '@peartubeIndex/sourceRecords' value encoding
const collection0_enc = getEncoding('@peartubeIndex/sourceRecord/hyperdb#0')

// '@peartubeIndex/sourceRecords' reconstruction function
function collection0_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection0_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection0.decodedVersion = c.uint.decode(state)
  const record = collection0_enc.decode(state)
  record.publisherId = key[0]
  record.catalogEpoch = key[1]
  record.recordId = key[2]
  return record
}
// '@peartubeIndex/sourceRecords' key reconstruction function
function collection0_reconstruct_key (keyBuf) {
  const key = collection0_key.decode(keyBuf)
  return {
    publisherId: key[0],
    catalogEpoch: key[1],
    recordId: key[2]
  }
}

// '@peartubeIndex/sourceRecords'
const collection0 = {
  name: '@peartubeIndex/sourceRecords',
  id: 0,
  version: 1,
  encodeKey (record) {
    const key = [record.publisherId, record.catalogEpoch, record.recordId]
    return collection0_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection0_key.encodeRange({
      gt: gt ? collection0_indexify(gt) : null,
      lt: lt ? collection0_indexify(lt) : null,
      gte: gte ? collection0_indexify(gte) : null,
      lte: lte ? collection0_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection0_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection0_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection0_reconstruct,
  reconstructKey: collection0_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@peartubeIndex/sourceCursors' collection key
const collection1_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.UINT
], { prefix: 1 })

function collection1_indexify (record) {
  const arr = []

  const a0 = record.publisherId
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.catalogEpoch
  if (a1 === undefined) return arr
  arr.push(a1)

  return arr
}

// '@peartubeIndex/sourceCursors' value encoding
const collection1_enc = getEncoding('@peartubeIndex/sourceCursor/hyperdb#1')

// '@peartubeIndex/sourceCursors' reconstruction function
function collection1_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection1_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection1.decodedVersion = c.uint.decode(state)
  const record = collection1_enc.decode(state)
  record.publisherId = key[0]
  record.catalogEpoch = key[1]
  return record
}
// '@peartubeIndex/sourceCursors' key reconstruction function
function collection1_reconstruct_key (keyBuf) {
  const key = collection1_key.decode(keyBuf)
  return {
    publisherId: key[0],
    catalogEpoch: key[1]
  }
}

// '@peartubeIndex/sourceCursors'
const collection1 = {
  name: '@peartubeIndex/sourceCursors',
  id: 1,
  version: 1,
  encodeKey (record) {
    const key = [record.publisherId, record.catalogEpoch]
    return collection1_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection1_key.encodeRange({
      gt: gt ? collection1_indexify(gt) : null,
      lt: lt ? collection1_indexify(lt) : null,
      gte: gte ? collection1_indexify(gte) : null,
      lte: lte ? collection1_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection1_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection1_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection1_reconstruct,
  reconstructKey: collection1_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@peartubeIndex/externalReferenceProjections' collection key
const collection2_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING
], { prefix: 2 })

function collection2_indexify (record) {
  const arr = []

  const a0 = record.publisherId
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.sourceRecordRef
  if (a1 === undefined) return arr
  arr.push(a1)

  const a2 = record.namespace
  if (a2 === undefined) return arr
  arr.push(a2)

  const a3 = record.normalizedIdentifier
  if (a3 === undefined) return arr
  arr.push(a3)

  const a4 = record.entityKind
  if (a4 === undefined) return arr
  arr.push(a4)

  const a5 = record.entityId
  if (a5 === undefined) return arr
  arr.push(a5)

  return arr
}

// '@peartubeIndex/externalReferenceProjections' value encoding
const collection2_enc = getEncoding('@peartubeIndex/externalReferenceProjection/hyperdb#2')

// '@peartubeIndex/externalReferenceProjections' reconstruction function
function collection2_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection2_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection2.decodedVersion = c.uint.decode(state)
  const record = collection2_enc.decode(state)
  record.publisherId = key[0]
  record.sourceRecordRef = key[1]
  record.namespace = key[2]
  record.normalizedIdentifier = key[3]
  record.entityKind = key[4]
  record.entityId = key[5]
  return record
}
// '@peartubeIndex/externalReferenceProjections' key reconstruction function
function collection2_reconstruct_key (keyBuf) {
  const key = collection2_key.decode(keyBuf)
  return {
    publisherId: key[0],
    sourceRecordRef: key[1],
    namespace: key[2],
    normalizedIdentifier: key[3],
    entityKind: key[4],
    entityId: key[5]
  }
}

// '@peartubeIndex/externalReferenceProjections'
const collection2 = {
  name: '@peartubeIndex/externalReferenceProjections',
  id: 2,
  version: 1,
  encodeKey (record) {
    const key = [record.publisherId, record.sourceRecordRef, record.namespace, record.normalizedIdentifier, record.entityKind, record.entityId]
    return collection2_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection2_key.encodeRange({
      gt: gt ? collection2_indexify(gt) : null,
      lt: lt ? collection2_indexify(lt) : null,
      gte: gte ? collection2_indexify(gte) : null,
      lte: lte ? collection2_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection2_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection2_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection2_reconstruct,
  reconstructKey: collection2_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@peartubeIndex/publicationProjections' collection key
const collection3_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING
], { prefix: 3 })

function collection3_indexify (record) {
  const arr = []

  const a0 = record.publisherId
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.sourceRecordRef
  if (a1 === undefined) return arr
  arr.push(a1)

  const a2 = record.publicationId
  if (a2 === undefined) return arr
  arr.push(a2)

  return arr
}

// '@peartubeIndex/publicationProjections' value encoding
const collection3_enc = getEncoding('@peartubeIndex/publicationProjection/hyperdb#3')

// '@peartubeIndex/publicationProjections' reconstruction function
function collection3_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection3_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection3.decodedVersion = c.uint.decode(state)
  const record = collection3_enc.decode(state)
  record.publisherId = key[0]
  record.sourceRecordRef = key[1]
  record.publicationId = key[2]
  return record
}
// '@peartubeIndex/publicationProjections' key reconstruction function
function collection3_reconstruct_key (keyBuf) {
  const key = collection3_key.decode(keyBuf)
  return {
    publisherId: key[0],
    sourceRecordRef: key[1],
    publicationId: key[2]
  }
}

// '@peartubeIndex/publicationProjections'
const collection3 = {
  name: '@peartubeIndex/publicationProjections',
  id: 3,
  version: 1,
  encodeKey (record) {
    const key = [record.publisherId, record.sourceRecordRef, record.publicationId]
    return collection3_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection3_key.encodeRange({
      gt: gt ? collection3_indexify(gt) : null,
      lt: lt ? collection3_indexify(lt) : null,
      gte: gte ? collection3_indexify(gte) : null,
      lte: lte ? collection3_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection3_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection3_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection3_reconstruct,
  reconstructKey: collection3_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@peartubeIndex/renditionProjections' collection key
const collection4_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING
], { prefix: 4 })

function collection4_indexify (record) {
  const arr = []

  const a0 = record.publisherId
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.sourceRecordRef
  if (a1 === undefined) return arr
  arr.push(a1)

  const a2 = record.renditionId
  if (a2 === undefined) return arr
  arr.push(a2)

  return arr
}

// '@peartubeIndex/renditionProjections' value encoding
const collection4_enc = getEncoding('@peartubeIndex/renditionProjection/hyperdb#4')

// '@peartubeIndex/renditionProjections' reconstruction function
function collection4_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection4_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection4.decodedVersion = c.uint.decode(state)
  const record = collection4_enc.decode(state)
  record.publisherId = key[0]
  record.sourceRecordRef = key[1]
  record.renditionId = key[2]
  return record
}
// '@peartubeIndex/renditionProjections' key reconstruction function
function collection4_reconstruct_key (keyBuf) {
  const key = collection4_key.decode(keyBuf)
  return {
    publisherId: key[0],
    sourceRecordRef: key[1],
    renditionId: key[2]
  }
}

// '@peartubeIndex/renditionProjections'
const collection4 = {
  name: '@peartubeIndex/renditionProjections',
  id: 4,
  version: 1,
  encodeKey (record) {
    const key = [record.publisherId, record.sourceRecordRef, record.renditionId]
    return collection4_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection4_key.encodeRange({
      gt: gt ? collection4_indexify(gt) : null,
      lt: lt ? collection4_indexify(lt) : null,
      gte: gte ? collection4_indexify(gte) : null,
      lte: lte ? collection4_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection4_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection4_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection4_reconstruct,
  reconstructKey: collection4_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@peartubeIndex/availabilityProjections' collection key
const collection5_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.UINT
], { prefix: 5 })

function collection5_indexify (record) {
  const arr = []

  const a0 = record.publisherId
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.sourceRecordRef
  if (a1 === undefined) return arr
  arr.push(a1)

  const a2 = record.assetId
  if (a2 === undefined) return arr
  arr.push(a2)

  const a3 = record.observerId
  if (a3 === undefined) return arr
  arr.push(a3)

  const a4 = record.observedAt
  if (a4 === undefined) return arr
  arr.push(a4)

  return arr
}

// '@peartubeIndex/availabilityProjections' value encoding
const collection5_enc = getEncoding('@peartubeIndex/availabilityProjection/hyperdb#5')

// '@peartubeIndex/availabilityProjections' reconstruction function
function collection5_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection5_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection5.decodedVersion = c.uint.decode(state)
  const record = collection5_enc.decode(state)
  record.publisherId = key[0]
  record.sourceRecordRef = key[1]
  record.assetId = key[2]
  record.observerId = key[3]
  record.observedAt = key[4]
  return record
}
// '@peartubeIndex/availabilityProjections' key reconstruction function
function collection5_reconstruct_key (keyBuf) {
  const key = collection5_key.decode(keyBuf)
  return {
    publisherId: key[0],
    sourceRecordRef: key[1],
    assetId: key[2],
    observerId: key[3],
    observedAt: key[4]
  }
}

// '@peartubeIndex/availabilityProjections'
const collection5 = {
  name: '@peartubeIndex/availabilityProjections',
  id: 5,
  version: 1,
  encodeKey (record) {
    const key = [record.publisherId, record.sourceRecordRef, record.assetId, record.observerId, record.observedAt]
    return collection5_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection5_key.encodeRange({
      gt: gt ? collection5_indexify(gt) : null,
      lt: lt ? collection5_indexify(lt) : null,
      gte: gte ? collection5_indexify(gte) : null,
      lte: lte ? collection5_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection5_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection5_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection5_reconstruct,
  reconstructKey: collection5_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@peartubeIndex/relationshipEdges' collection key
const collection6_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING
], { prefix: 6 })

function collection6_indexify (record) {
  const arr = []

  const a0 = record.publisherId
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.sourceRecordRef
  if (a1 === undefined) return arr
  arr.push(a1)

  const a2 = record.relationType
  if (a2 === undefined) return arr
  arr.push(a2)

  const a3 = record.fromId
  if (a3 === undefined) return arr
  arr.push(a3)

  const a4 = record.toId
  if (a4 === undefined) return arr
  arr.push(a4)

  return arr
}

// '@peartubeIndex/relationshipEdges' value encoding
const collection6_enc = getEncoding('@peartubeIndex/relationshipEdge/hyperdb#6')

// '@peartubeIndex/relationshipEdges' reconstruction function
function collection6_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection6_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection6.decodedVersion = c.uint.decode(state)
  const record = collection6_enc.decode(state)
  record.publisherId = key[0]
  record.sourceRecordRef = key[1]
  record.relationType = key[2]
  record.fromId = key[3]
  record.toId = key[4]
  return record
}
// '@peartubeIndex/relationshipEdges' key reconstruction function
function collection6_reconstruct_key (keyBuf) {
  const key = collection6_key.decode(keyBuf)
  return {
    publisherId: key[0],
    sourceRecordRef: key[1],
    relationType: key[2],
    fromId: key[3],
    toId: key[4]
  }
}

// '@peartubeIndex/relationshipEdges'
const collection6 = {
  name: '@peartubeIndex/relationshipEdges',
  id: 6,
  version: 1,
  encodeKey (record) {
    const key = [record.publisherId, record.sourceRecordRef, record.relationType, record.fromId, record.toId]
    return collection6_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection6_key.encodeRange({
      gt: gt ? collection6_indexify(gt) : null,
      lt: lt ? collection6_indexify(lt) : null,
      gte: gte ? collection6_indexify(gte) : null,
      lte: lte ? collection6_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection6_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection6_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection6_reconstruct,
  reconstructKey: collection6_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@peartubeIndex/source-records-by-publisher' collection key
const index7_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.UINT,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.UINT,
  IndexEncoder.STRING
], { prefix: 7 })

function index7_indexify (record) {
  const arr = []

  const a0 = record.publisherId
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.catalogEpoch
  if (a1 === undefined) return arr
  arr.push(a1)

  const a2 = record.recordId
  if (a2 === undefined) return arr
  arr.push(a2)

  const a3 = record.publisherId
  if (a3 === undefined) return arr
  arr.push(a3)

  const a4 = record.catalogEpoch
  if (a4 === undefined) return arr
  arr.push(a4)

  const a5 = record.recordId
  if (a5 === undefined) return arr
  arr.push(a5)

  return arr
}

// '@peartubeIndex/source-records-by-publisher'
const index7 = {
  name: '@peartubeIndex/source-records-by-publisher',
  version: 1,
  id: 7,
  encodeKey (record) {
    return index7_key.encode(index7_indexify(record))
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return index7_key.encodeRange({
      gt: gt ? index7_indexify(gt) : null,
      lt: lt ? index7_indexify(lt) : null,
      gte: gte ? index7_indexify(gte) : null,
      lte: lte ? index7_indexify(lte) : null
    })
  },
  encodeValue: (record) => index7.collection.encodeKey(record),
  encodeIndexKeys (record, context) {
    return [index7_key.encode([record.publisherId, record.catalogEpoch, record.recordId, record.publisherId, record.catalogEpoch, record.recordId])]
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection0.indexes.length,
  collection: collection0
}
collection0.indexes.push(index7)

// '@peartubeIndex/source-cursors-by-publisher' collection key
const index8_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.UINT,
  IndexEncoder.STRING,
  IndexEncoder.UINT
], { prefix: 8 })

function index8_indexify (record) {
  const arr = []

  const a0 = record.publisherId
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.catalogEpoch
  if (a1 === undefined) return arr
  arr.push(a1)

  const a2 = record.publisherId
  if (a2 === undefined) return arr
  arr.push(a2)

  const a3 = record.catalogEpoch
  if (a3 === undefined) return arr
  arr.push(a3)

  return arr
}

// '@peartubeIndex/source-cursors-by-publisher'
const index8 = {
  name: '@peartubeIndex/source-cursors-by-publisher',
  version: 1,
  id: 8,
  encodeKey (record) {
    return index8_key.encode(index8_indexify(record))
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return index8_key.encodeRange({
      gt: gt ? index8_indexify(gt) : null,
      lt: lt ? index8_indexify(lt) : null,
      gte: gte ? index8_indexify(gte) : null,
      lte: lte ? index8_indexify(lte) : null
    })
  },
  encodeValue: (record) => index8.collection.encodeKey(record),
  encodeIndexKeys (record, context) {
    return [index8_key.encode([record.publisherId, record.catalogEpoch, record.publisherId, record.catalogEpoch])]
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection1.indexes.length,
  collection: collection1
}
collection1.indexes.push(index8)

// '@peartubeIndex/external-references-by-publisher' collection key
const index9_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING
], { prefix: 9 })

function index9_indexify (record) {
  const arr = []

  const a0 = record.publisherId
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.sourceRecordRef
  if (a1 === undefined) return arr
  arr.push(a1)

  const a2 = record.namespace
  if (a2 === undefined) return arr
  arr.push(a2)

  const a3 = record.normalizedIdentifier
  if (a3 === undefined) return arr
  arr.push(a3)

  const a4 = record.entityKind
  if (a4 === undefined) return arr
  arr.push(a4)

  const a5 = record.entityId
  if (a5 === undefined) return arr
  arr.push(a5)

  const a6 = record.publisherId
  if (a6 === undefined) return arr
  arr.push(a6)

  const a7 = record.sourceRecordRef
  if (a7 === undefined) return arr
  arr.push(a7)

  const a8 = record.namespace
  if (a8 === undefined) return arr
  arr.push(a8)

  const a9 = record.normalizedIdentifier
  if (a9 === undefined) return arr
  arr.push(a9)

  const a10 = record.entityKind
  if (a10 === undefined) return arr
  arr.push(a10)

  const a11 = record.entityId
  if (a11 === undefined) return arr
  arr.push(a11)

  return arr
}

// '@peartubeIndex/external-references-by-publisher'
const index9 = {
  name: '@peartubeIndex/external-references-by-publisher',
  version: 1,
  id: 9,
  encodeKey (record) {
    return index9_key.encode(index9_indexify(record))
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return index9_key.encodeRange({
      gt: gt ? index9_indexify(gt) : null,
      lt: lt ? index9_indexify(lt) : null,
      gte: gte ? index9_indexify(gte) : null,
      lte: lte ? index9_indexify(lte) : null
    })
  },
  encodeValue: (record) => index9.collection.encodeKey(record),
  encodeIndexKeys (record, context) {
    return [index9_key.encode([record.publisherId, record.sourceRecordRef, record.namespace, record.normalizedIdentifier, record.entityKind, record.entityId, record.publisherId, record.sourceRecordRef, record.namespace, record.normalizedIdentifier, record.entityKind, record.entityId])]
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection2.indexes.length,
  collection: collection2
}
collection2.indexes.push(index9)

// '@peartubeIndex/publications-by-publisher' collection key
const index10_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING
], { prefix: 10 })

function index10_indexify (record) {
  const arr = []

  const a0 = record.publisherId
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.sourceRecordRef
  if (a1 === undefined) return arr
  arr.push(a1)

  const a2 = record.publicationId
  if (a2 === undefined) return arr
  arr.push(a2)

  const a3 = record.publisherId
  if (a3 === undefined) return arr
  arr.push(a3)

  const a4 = record.sourceRecordRef
  if (a4 === undefined) return arr
  arr.push(a4)

  const a5 = record.publicationId
  if (a5 === undefined) return arr
  arr.push(a5)

  return arr
}

// '@peartubeIndex/publications-by-publisher'
const index10 = {
  name: '@peartubeIndex/publications-by-publisher',
  version: 1,
  id: 10,
  encodeKey (record) {
    return index10_key.encode(index10_indexify(record))
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return index10_key.encodeRange({
      gt: gt ? index10_indexify(gt) : null,
      lt: lt ? index10_indexify(lt) : null,
      gte: gte ? index10_indexify(gte) : null,
      lte: lte ? index10_indexify(lte) : null
    })
  },
  encodeValue: (record) => index10.collection.encodeKey(record),
  encodeIndexKeys (record, context) {
    return [index10_key.encode([record.publisherId, record.sourceRecordRef, record.publicationId, record.publisherId, record.sourceRecordRef, record.publicationId])]
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection3.indexes.length,
  collection: collection3
}
collection3.indexes.push(index10)

// '@peartubeIndex/renditions-by-publisher' collection key
const index11_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING
], { prefix: 11 })

function index11_indexify (record) {
  const arr = []

  const a0 = record.publisherId
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.sourceRecordRef
  if (a1 === undefined) return arr
  arr.push(a1)

  const a2 = record.renditionId
  if (a2 === undefined) return arr
  arr.push(a2)

  const a3 = record.publisherId
  if (a3 === undefined) return arr
  arr.push(a3)

  const a4 = record.sourceRecordRef
  if (a4 === undefined) return arr
  arr.push(a4)

  const a5 = record.renditionId
  if (a5 === undefined) return arr
  arr.push(a5)

  return arr
}

// '@peartubeIndex/renditions-by-publisher'
const index11 = {
  name: '@peartubeIndex/renditions-by-publisher',
  version: 1,
  id: 11,
  encodeKey (record) {
    return index11_key.encode(index11_indexify(record))
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return index11_key.encodeRange({
      gt: gt ? index11_indexify(gt) : null,
      lt: lt ? index11_indexify(lt) : null,
      gte: gte ? index11_indexify(gte) : null,
      lte: lte ? index11_indexify(lte) : null
    })
  },
  encodeValue: (record) => index11.collection.encodeKey(record),
  encodeIndexKeys (record, context) {
    return [index11_key.encode([record.publisherId, record.sourceRecordRef, record.renditionId, record.publisherId, record.sourceRecordRef, record.renditionId])]
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection4.indexes.length,
  collection: collection4
}
collection4.indexes.push(index11)

// '@peartubeIndex/availability-by-publisher' collection key
const index12_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.UINT,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.UINT
], { prefix: 12 })

function index12_indexify (record) {
  const arr = []

  const a0 = record.publisherId
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.sourceRecordRef
  if (a1 === undefined) return arr
  arr.push(a1)

  const a2 = record.assetId
  if (a2 === undefined) return arr
  arr.push(a2)

  const a3 = record.observerId
  if (a3 === undefined) return arr
  arr.push(a3)

  const a4 = record.observedAt
  if (a4 === undefined) return arr
  arr.push(a4)

  const a5 = record.publisherId
  if (a5 === undefined) return arr
  arr.push(a5)

  const a6 = record.sourceRecordRef
  if (a6 === undefined) return arr
  arr.push(a6)

  const a7 = record.assetId
  if (a7 === undefined) return arr
  arr.push(a7)

  const a8 = record.observerId
  if (a8 === undefined) return arr
  arr.push(a8)

  const a9 = record.observedAt
  if (a9 === undefined) return arr
  arr.push(a9)

  return arr
}

// '@peartubeIndex/availability-by-publisher'
const index12 = {
  name: '@peartubeIndex/availability-by-publisher',
  version: 1,
  id: 12,
  encodeKey (record) {
    return index12_key.encode(index12_indexify(record))
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return index12_key.encodeRange({
      gt: gt ? index12_indexify(gt) : null,
      lt: lt ? index12_indexify(lt) : null,
      gte: gte ? index12_indexify(gte) : null,
      lte: lte ? index12_indexify(lte) : null
    })
  },
  encodeValue: (record) => index12.collection.encodeKey(record),
  encodeIndexKeys (record, context) {
    return [index12_key.encode([record.publisherId, record.sourceRecordRef, record.assetId, record.observerId, record.observedAt, record.publisherId, record.sourceRecordRef, record.assetId, record.observerId, record.observedAt])]
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection5.indexes.length,
  collection: collection5
}
collection5.indexes.push(index12)

// '@peartubeIndex/relationships-by-publisher' collection key
const index13_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING
], { prefix: 13 })

function index13_indexify (record) {
  const arr = []

  const a0 = record.publisherId
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.sourceRecordRef
  if (a1 === undefined) return arr
  arr.push(a1)

  const a2 = record.relationType
  if (a2 === undefined) return arr
  arr.push(a2)

  const a3 = record.fromId
  if (a3 === undefined) return arr
  arr.push(a3)

  const a4 = record.toId
  if (a4 === undefined) return arr
  arr.push(a4)

  const a5 = record.publisherId
  if (a5 === undefined) return arr
  arr.push(a5)

  const a6 = record.sourceRecordRef
  if (a6 === undefined) return arr
  arr.push(a6)

  const a7 = record.relationType
  if (a7 === undefined) return arr
  arr.push(a7)

  const a8 = record.fromId
  if (a8 === undefined) return arr
  arr.push(a8)

  const a9 = record.toId
  if (a9 === undefined) return arr
  arr.push(a9)

  return arr
}

// '@peartubeIndex/relationships-by-publisher'
const index13 = {
  name: '@peartubeIndex/relationships-by-publisher',
  version: 1,
  id: 13,
  encodeKey (record) {
    return index13_key.encode(index13_indexify(record))
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return index13_key.encodeRange({
      gt: gt ? index13_indexify(gt) : null,
      lt: lt ? index13_indexify(lt) : null,
      gte: gte ? index13_indexify(gte) : null,
      lte: lte ? index13_indexify(lte) : null
    })
  },
  encodeValue: (record) => index13.collection.encodeKey(record),
  encodeIndexKeys (record, context) {
    return [index13_key.encode([record.publisherId, record.sourceRecordRef, record.relationType, record.fromId, record.toId, record.publisherId, record.sourceRecordRef, record.relationType, record.fromId, record.toId])]
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection6.indexes.length,
  collection: collection6
}
collection6.indexes.push(index13)

// '@peartubeIndex/external-reference-exact' collection key
const index14_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING
], { prefix: 14 })

function index14_indexify (record) {
  const arr = []

  const a0 = record.namespace
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.normalizedIdentifier
  if (a1 === undefined) return arr
  arr.push(a1)

  const a2 = record.publisherId
  if (a2 === undefined) return arr
  arr.push(a2)

  const a3 = record.sourceRecordRef
  if (a3 === undefined) return arr
  arr.push(a3)

  const a4 = record.entityKind
  if (a4 === undefined) return arr
  arr.push(a4)

  const a5 = record.entityId
  if (a5 === undefined) return arr
  arr.push(a5)

  const a6 = record.publisherId
  if (a6 === undefined) return arr
  arr.push(a6)

  const a7 = record.sourceRecordRef
  if (a7 === undefined) return arr
  arr.push(a7)

  const a8 = record.namespace
  if (a8 === undefined) return arr
  arr.push(a8)

  const a9 = record.normalizedIdentifier
  if (a9 === undefined) return arr
  arr.push(a9)

  const a10 = record.entityKind
  if (a10 === undefined) return arr
  arr.push(a10)

  const a11 = record.entityId
  if (a11 === undefined) return arr
  arr.push(a11)

  return arr
}

// '@peartubeIndex/external-reference-exact'
const index14 = {
  name: '@peartubeIndex/external-reference-exact',
  version: 1,
  id: 14,
  encodeKey (record) {
    return index14_key.encode(index14_indexify(record))
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return index14_key.encodeRange({
      gt: gt ? index14_indexify(gt) : null,
      lt: lt ? index14_indexify(lt) : null,
      gte: gte ? index14_indexify(gte) : null,
      lte: lte ? index14_indexify(lte) : null
    })
  },
  encodeValue: (record) => index14.collection.encodeKey(record),
  encodeIndexKeys (record, context) {
    return [index14_key.encode([record.namespace, record.normalizedIdentifier, record.publisherId, record.sourceRecordRef, record.entityKind, record.entityId, record.publisherId, record.sourceRecordRef, record.namespace, record.normalizedIdentifier, record.entityKind, record.entityId])]
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection2.indexes.length,
  collection: collection2
}
collection2.indexes.push(index14)

// '@peartubeIndex/entity-exact' collection key
const index15_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING
], { prefix: 15 })

function index15_indexify (record) {
  const arr = []

  const a0 = record.entityKind
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.entityId
  if (a1 === undefined) return arr
  arr.push(a1)

  const a2 = record.publisherId
  if (a2 === undefined) return arr
  arr.push(a2)

  const a3 = record.sourceRecordRef
  if (a3 === undefined) return arr
  arr.push(a3)

  const a4 = record.namespace
  if (a4 === undefined) return arr
  arr.push(a4)

  const a5 = record.normalizedIdentifier
  if (a5 === undefined) return arr
  arr.push(a5)

  const a6 = record.publisherId
  if (a6 === undefined) return arr
  arr.push(a6)

  const a7 = record.sourceRecordRef
  if (a7 === undefined) return arr
  arr.push(a7)

  const a8 = record.namespace
  if (a8 === undefined) return arr
  arr.push(a8)

  const a9 = record.normalizedIdentifier
  if (a9 === undefined) return arr
  arr.push(a9)

  const a10 = record.entityKind
  if (a10 === undefined) return arr
  arr.push(a10)

  const a11 = record.entityId
  if (a11 === undefined) return arr
  arr.push(a11)

  return arr
}

// '@peartubeIndex/entity-exact'
const index15 = {
  name: '@peartubeIndex/entity-exact',
  version: 1,
  id: 15,
  encodeKey (record) {
    return index15_key.encode(index15_indexify(record))
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return index15_key.encodeRange({
      gt: gt ? index15_indexify(gt) : null,
      lt: lt ? index15_indexify(lt) : null,
      gte: gte ? index15_indexify(gte) : null,
      lte: lte ? index15_indexify(lte) : null
    })
  },
  encodeValue: (record) => index15.collection.encodeKey(record),
  encodeIndexKeys (record, context) {
    return [index15_key.encode([record.entityKind, record.entityId, record.publisherId, record.sourceRecordRef, record.namespace, record.normalizedIdentifier, record.publisherId, record.sourceRecordRef, record.namespace, record.normalizedIdentifier, record.entityKind, record.entityId])]
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection2.indexes.length,
  collection: collection2
}
collection2.indexes.push(index15)

// '@peartubeIndex/publication-exact' collection key
const index16_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING
], { prefix: 16 })

function index16_indexify (record) {
  const arr = []

  const a0 = record.publicationId
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.publisherId
  if (a1 === undefined) return arr
  arr.push(a1)

  const a2 = record.sourceRecordRef
  if (a2 === undefined) return arr
  arr.push(a2)

  const a3 = record.publisherId
  if (a3 === undefined) return arr
  arr.push(a3)

  const a4 = record.sourceRecordRef
  if (a4 === undefined) return arr
  arr.push(a4)

  const a5 = record.publicationId
  if (a5 === undefined) return arr
  arr.push(a5)

  return arr
}

// '@peartubeIndex/publication-exact'
const index16 = {
  name: '@peartubeIndex/publication-exact',
  version: 1,
  id: 16,
  encodeKey (record) {
    return index16_key.encode(index16_indexify(record))
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return index16_key.encodeRange({
      gt: gt ? index16_indexify(gt) : null,
      lt: lt ? index16_indexify(lt) : null,
      gte: gte ? index16_indexify(gte) : null,
      lte: lte ? index16_indexify(lte) : null
    })
  },
  encodeValue: (record) => index16.collection.encodeKey(record),
  encodeIndexKeys (record, context) {
    return [index16_key.encode([record.publicationId, record.publisherId, record.sourceRecordRef, record.publisherId, record.sourceRecordRef, record.publicationId])]
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection3.indexes.length,
  collection: collection3
}
collection3.indexes.push(index16)

// '@peartubeIndex/publication-by-work' collection key
const index17_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING
], { prefix: 17 })

function index17_indexify (record) {
  const arr = []

  const a0 = record.workEntityId
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.publisherId
  if (a1 === undefined) return arr
  arr.push(a1)

  const a2 = record.sourceRecordRef
  if (a2 === undefined) return arr
  arr.push(a2)

  const a3 = record.publicationId
  if (a3 === undefined) return arr
  arr.push(a3)

  const a4 = record.publisherId
  if (a4 === undefined) return arr
  arr.push(a4)

  const a5 = record.sourceRecordRef
  if (a5 === undefined) return arr
  arr.push(a5)

  const a6 = record.publicationId
  if (a6 === undefined) return arr
  arr.push(a6)

  return arr
}

// '@peartubeIndex/publication-by-work'
const index17 = {
  name: '@peartubeIndex/publication-by-work',
  version: 1,
  id: 17,
  encodeKey (record) {
    return index17_key.encode(index17_indexify(record))
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return index17_key.encodeRange({
      gt: gt ? index17_indexify(gt) : null,
      lt: lt ? index17_indexify(lt) : null,
      gte: gte ? index17_indexify(gte) : null,
      lte: lte ? index17_indexify(lte) : null
    })
  },
  encodeValue: (record) => index17.collection.encodeKey(record),
  encodeIndexKeys (record, context) {
    return [index17_key.encode([record.workEntityId, record.publisherId, record.sourceRecordRef, record.publicationId, record.publisherId, record.sourceRecordRef, record.publicationId])]
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection3.indexes.length,
  collection: collection3
}
collection3.indexes.push(index17)

// '@peartubeIndex/normalized-title' collection key
const index18_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING
], { prefix: 18 })

function index18_indexify (record) {
  const arr = []

  const a0 = record.normalizedTitle
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.publisherId
  if (a1 === undefined) return arr
  arr.push(a1)

  const a2 = record.sourceRecordRef
  if (a2 === undefined) return arr
  arr.push(a2)

  const a3 = record.publicationId
  if (a3 === undefined) return arr
  arr.push(a3)

  const a4 = record.publisherId
  if (a4 === undefined) return arr
  arr.push(a4)

  const a5 = record.sourceRecordRef
  if (a5 === undefined) return arr
  arr.push(a5)

  const a6 = record.publicationId
  if (a6 === undefined) return arr
  arr.push(a6)

  return arr
}

// '@peartubeIndex/normalized-title'
const index18 = {
  name: '@peartubeIndex/normalized-title',
  version: 1,
  id: 18,
  encodeKey (record) {
    return index18_key.encode(index18_indexify(record))
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return index18_key.encodeRange({
      gt: gt ? index18_indexify(gt) : null,
      lt: lt ? index18_indexify(lt) : null,
      gte: gte ? index18_indexify(gte) : null,
      lte: lte ? index18_indexify(lte) : null
    })
  },
  encodeValue: (record) => index18.collection.encodeKey(record),
  encodeIndexKeys (record, context) {
    return [index18_key.encode([record.normalizedTitle, record.publisherId, record.sourceRecordRef, record.publicationId, record.publisherId, record.sourceRecordRef, record.publicationId])]
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection3.indexes.length,
  collection: collection3
}
collection3.indexes.push(index18)

// '@peartubeIndex/asset-exact' collection key
const index19_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING
], { prefix: 19 })

function index19_indexify (record) {
  const arr = []

  const a0 = record.assetId
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.publisherId
  if (a1 === undefined) return arr
  arr.push(a1)

  const a2 = record.sourceRecordRef
  if (a2 === undefined) return arr
  arr.push(a2)

  const a3 = record.renditionId
  if (a3 === undefined) return arr
  arr.push(a3)

  const a4 = record.publisherId
  if (a4 === undefined) return arr
  arr.push(a4)

  const a5 = record.sourceRecordRef
  if (a5 === undefined) return arr
  arr.push(a5)

  const a6 = record.renditionId
  if (a6 === undefined) return arr
  arr.push(a6)

  return arr
}

// '@peartubeIndex/asset-exact'
const index19 = {
  name: '@peartubeIndex/asset-exact',
  version: 1,
  id: 19,
  encodeKey (record) {
    return index19_key.encode(index19_indexify(record))
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return index19_key.encodeRange({
      gt: gt ? index19_indexify(gt) : null,
      lt: lt ? index19_indexify(lt) : null,
      gte: gte ? index19_indexify(gte) : null,
      lte: lte ? index19_indexify(lte) : null
    })
  },
  encodeValue: (record) => index19.collection.encodeKey(record),
  encodeIndexKeys (record, context) {
    return [index19_key.encode([record.assetId, record.publisherId, record.sourceRecordRef, record.renditionId, record.publisherId, record.sourceRecordRef, record.renditionId])]
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection4.indexes.length,
  collection: collection4
}
collection4.indexes.push(index19)

// '@peartubeIndex/rendition-exact' collection key
const index20_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING
], { prefix: 20 })

function index20_indexify (record) {
  const arr = []

  const a0 = record.renditionId
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.publisherId
  if (a1 === undefined) return arr
  arr.push(a1)

  const a2 = record.sourceRecordRef
  if (a2 === undefined) return arr
  arr.push(a2)

  const a3 = record.publisherId
  if (a3 === undefined) return arr
  arr.push(a3)

  const a4 = record.sourceRecordRef
  if (a4 === undefined) return arr
  arr.push(a4)

  const a5 = record.renditionId
  if (a5 === undefined) return arr
  arr.push(a5)

  return arr
}

// '@peartubeIndex/rendition-exact'
const index20 = {
  name: '@peartubeIndex/rendition-exact',
  version: 1,
  id: 20,
  encodeKey (record) {
    return index20_key.encode(index20_indexify(record))
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return index20_key.encodeRange({
      gt: gt ? index20_indexify(gt) : null,
      lt: lt ? index20_indexify(lt) : null,
      gte: gte ? index20_indexify(gte) : null,
      lte: lte ? index20_indexify(lte) : null
    })
  },
  encodeValue: (record) => index20.collection.encodeKey(record),
  encodeIndexKeys (record, context) {
    return [index20_key.encode([record.renditionId, record.publisherId, record.sourceRecordRef, record.publisherId, record.sourceRecordRef, record.renditionId])]
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection4.indexes.length,
  collection: collection4
}
collection4.indexes.push(index20)

// '@peartubeIndex/availability-by-asset' collection key
const index21_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.UINT,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.UINT
], { prefix: 21 })

function index21_indexify (record) {
  const arr = []

  const a0 = record.assetId
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.publisherId
  if (a1 === undefined) return arr
  arr.push(a1)

  const a2 = record.sourceRecordRef
  if (a2 === undefined) return arr
  arr.push(a2)

  const a3 = record.observerId
  if (a3 === undefined) return arr
  arr.push(a3)

  const a4 = record.observedAt
  if (a4 === undefined) return arr
  arr.push(a4)

  const a5 = record.publisherId
  if (a5 === undefined) return arr
  arr.push(a5)

  const a6 = record.sourceRecordRef
  if (a6 === undefined) return arr
  arr.push(a6)

  const a7 = record.assetId
  if (a7 === undefined) return arr
  arr.push(a7)

  const a8 = record.observerId
  if (a8 === undefined) return arr
  arr.push(a8)

  const a9 = record.observedAt
  if (a9 === undefined) return arr
  arr.push(a9)

  return arr
}

// '@peartubeIndex/availability-by-asset'
const index21 = {
  name: '@peartubeIndex/availability-by-asset',
  version: 1,
  id: 21,
  encodeKey (record) {
    return index21_key.encode(index21_indexify(record))
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return index21_key.encodeRange({
      gt: gt ? index21_indexify(gt) : null,
      lt: lt ? index21_indexify(lt) : null,
      gte: gte ? index21_indexify(gte) : null,
      lte: lte ? index21_indexify(lte) : null
    })
  },
  encodeValue: (record) => index21.collection.encodeKey(record),
  encodeIndexKeys (record, context) {
    return [index21_key.encode([record.assetId, record.publisherId, record.sourceRecordRef, record.observerId, record.observedAt, record.publisherId, record.sourceRecordRef, record.assetId, record.observerId, record.observedAt])]
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection5.indexes.length,
  collection: collection5
}
collection5.indexes.push(index21)

// '@peartubeIndex/relationship-by-type' collection key
const index22_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING
], { prefix: 22 })

function index22_indexify (record) {
  const arr = []

  const a0 = record.relationType
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.publisherId
  if (a1 === undefined) return arr
  arr.push(a1)

  const a2 = record.sourceRecordRef
  if (a2 === undefined) return arr
  arr.push(a2)

  const a3 = record.fromId
  if (a3 === undefined) return arr
  arr.push(a3)

  const a4 = record.toId
  if (a4 === undefined) return arr
  arr.push(a4)

  const a5 = record.publisherId
  if (a5 === undefined) return arr
  arr.push(a5)

  const a6 = record.sourceRecordRef
  if (a6 === undefined) return arr
  arr.push(a6)

  const a7 = record.relationType
  if (a7 === undefined) return arr
  arr.push(a7)

  const a8 = record.fromId
  if (a8 === undefined) return arr
  arr.push(a8)

  const a9 = record.toId
  if (a9 === undefined) return arr
  arr.push(a9)

  return arr
}

// '@peartubeIndex/relationship-by-type'
const index22 = {
  name: '@peartubeIndex/relationship-by-type',
  version: 1,
  id: 22,
  encodeKey (record) {
    return index22_key.encode(index22_indexify(record))
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return index22_key.encodeRange({
      gt: gt ? index22_indexify(gt) : null,
      lt: lt ? index22_indexify(lt) : null,
      gte: gte ? index22_indexify(gte) : null,
      lte: lte ? index22_indexify(lte) : null
    })
  },
  encodeValue: (record) => index22.collection.encodeKey(record),
  encodeIndexKeys (record, context) {
    return [index22_key.encode([record.relationType, record.publisherId, record.sourceRecordRef, record.fromId, record.toId, record.publisherId, record.sourceRecordRef, record.relationType, record.fromId, record.toId])]
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection6.indexes.length,
  collection: collection6
}
collection6.indexes.push(index22)

// '@peartubeIndex/relationship-by-from' collection key
const index23_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING
], { prefix: 23 })

function index23_indexify (record) {
  const arr = []

  const a0 = record.relationType
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.fromId
  if (a1 === undefined) return arr
  arr.push(a1)

  const a2 = record.publisherId
  if (a2 === undefined) return arr
  arr.push(a2)

  const a3 = record.sourceRecordRef
  if (a3 === undefined) return arr
  arr.push(a3)

  const a4 = record.toId
  if (a4 === undefined) return arr
  arr.push(a4)

  const a5 = record.publisherId
  if (a5 === undefined) return arr
  arr.push(a5)

  const a6 = record.sourceRecordRef
  if (a6 === undefined) return arr
  arr.push(a6)

  const a7 = record.relationType
  if (a7 === undefined) return arr
  arr.push(a7)

  const a8 = record.fromId
  if (a8 === undefined) return arr
  arr.push(a8)

  const a9 = record.toId
  if (a9 === undefined) return arr
  arr.push(a9)

  return arr
}

// '@peartubeIndex/relationship-by-from'
const index23 = {
  name: '@peartubeIndex/relationship-by-from',
  version: 1,
  id: 23,
  encodeKey (record) {
    return index23_key.encode(index23_indexify(record))
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return index23_key.encodeRange({
      gt: gt ? index23_indexify(gt) : null,
      lt: lt ? index23_indexify(lt) : null,
      gte: gte ? index23_indexify(gte) : null,
      lte: lte ? index23_indexify(lte) : null
    })
  },
  encodeValue: (record) => index23.collection.encodeKey(record),
  encodeIndexKeys (record, context) {
    return [index23_key.encode([record.relationType, record.fromId, record.publisherId, record.sourceRecordRef, record.toId, record.publisherId, record.sourceRecordRef, record.relationType, record.fromId, record.toId])]
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection6.indexes.length,
  collection: collection6
}
collection6.indexes.push(index23)

// '@peartubeIndex/relationship-by-to' collection key
const index24_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING
], { prefix: 24 })

function index24_indexify (record) {
  const arr = []

  const a0 = record.relationType
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.toId
  if (a1 === undefined) return arr
  arr.push(a1)

  const a2 = record.publisherId
  if (a2 === undefined) return arr
  arr.push(a2)

  const a3 = record.sourceRecordRef
  if (a3 === undefined) return arr
  arr.push(a3)

  const a4 = record.fromId
  if (a4 === undefined) return arr
  arr.push(a4)

  const a5 = record.publisherId
  if (a5 === undefined) return arr
  arr.push(a5)

  const a6 = record.sourceRecordRef
  if (a6 === undefined) return arr
  arr.push(a6)

  const a7 = record.relationType
  if (a7 === undefined) return arr
  arr.push(a7)

  const a8 = record.fromId
  if (a8 === undefined) return arr
  arr.push(a8)

  const a9 = record.toId
  if (a9 === undefined) return arr
  arr.push(a9)

  return arr
}

// '@peartubeIndex/relationship-by-to'
const index24 = {
  name: '@peartubeIndex/relationship-by-to',
  version: 1,
  id: 24,
  encodeKey (record) {
    return index24_key.encode(index24_indexify(record))
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return index24_key.encodeRange({
      gt: gt ? index24_indexify(gt) : null,
      lt: lt ? index24_indexify(lt) : null,
      gte: gte ? index24_indexify(gte) : null,
      lte: lte ? index24_indexify(lte) : null
    })
  },
  encodeValue: (record) => index24.collection.encodeKey(record),
  encodeIndexKeys (record, context) {
    return [index24_key.encode([record.relationType, record.toId, record.publisherId, record.sourceRecordRef, record.fromId, record.publisherId, record.sourceRecordRef, record.relationType, record.fromId, record.toId])]
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection6.indexes.length,
  collection: collection6
}
collection6.indexes.push(index24)

// '@peartubeIndex/token-prefix' collection key
const index25_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING
], { prefix: 25 })

function index25_indexify (record) {
  const arr = []

  const a0 = record.relationType
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.fromId
  if (a1 === undefined) return arr
  arr.push(a1)

  const a2 = record.publisherId
  if (a2 === undefined) return arr
  arr.push(a2)

  const a3 = record.sourceRecordRef
  if (a3 === undefined) return arr
  arr.push(a3)

  const a4 = record.toId
  if (a4 === undefined) return arr
  arr.push(a4)

  const a5 = record.publisherId
  if (a5 === undefined) return arr
  arr.push(a5)

  const a6 = record.sourceRecordRef
  if (a6 === undefined) return arr
  arr.push(a6)

  const a7 = record.relationType
  if (a7 === undefined) return arr
  arr.push(a7)

  const a8 = record.fromId
  if (a8 === undefined) return arr
  arr.push(a8)

  const a9 = record.toId
  if (a9 === undefined) return arr
  arr.push(a9)

  return arr
}

// '@peartubeIndex/token-prefix'
const index25 = {
  name: '@peartubeIndex/token-prefix',
  version: 1,
  id: 25,
  encodeKey (record) {
    return index25_key.encode(index25_indexify(record))
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return index25_key.encodeRange({
      gt: gt ? index25_indexify(gt) : null,
      lt: lt ? index25_indexify(lt) : null,
      gte: gte ? index25_indexify(gte) : null,
      lte: lte ? index25_indexify(lte) : null
    })
  },
  encodeValue: (record) => index25.collection.encodeKey(record),
  encodeIndexKeys (record, context) {
    return [index25_key.encode([record.relationType, record.fromId, record.publisherId, record.sourceRecordRef, record.toId, record.publisherId, record.sourceRecordRef, record.relationType, record.fromId, record.toId])]
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection6.indexes.length,
  collection: collection6
}
collection6.indexes.push(index25)

// '@peartubeIndex/usageCounters' collection key
const collection26_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING
], { prefix: 26 })

function collection26_indexify (record) {
  const arr = []

  const a0 = record.publisherId
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.scope
  if (a1 === undefined) return arr
  arr.push(a1)

  const a2 = record.bucketId
  if (a2 === undefined) return arr
  arr.push(a2)

  return arr
}

// '@peartubeIndex/usageCounters' value encoding
const collection26_enc = getEncoding('@peartubeIndex/usageCounter/hyperdb#26')

// '@peartubeIndex/usageCounters' reconstruction function
function collection26_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection26_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection26.decodedVersion = c.uint.decode(state)
  const record = collection26_enc.decode(state)
  record.publisherId = key[0]
  record.scope = key[1]
  record.bucketId = key[2]
  return record
}
// '@peartubeIndex/usageCounters' key reconstruction function
function collection26_reconstruct_key (keyBuf) {
  const key = collection26_key.decode(keyBuf)
  return {
    publisherId: key[0],
    scope: key[1],
    bucketId: key[2]
  }
}

// '@peartubeIndex/usageCounters'
const collection26 = {
  name: '@peartubeIndex/usageCounters',
  id: 26,
  version: 2,
  encodeKey (record) {
    const key = [record.publisherId, record.scope, record.bucketId]
    return collection26_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection26_key.encodeRange({
      gt: gt ? collection26_indexify(gt) : null,
      lt: lt ? collection26_indexify(lt) : null,
      gte: gte ? collection26_indexify(gte) : null,
      lte: lte ? collection26_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection26_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection26_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection26_reconstruct,
  reconstructKey: collection26_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@peartubeIndex/admissionTombstones' collection key
const collection27_key = new IndexEncoder([
  IndexEncoder.STRING
], { prefix: 27 })

function collection27_indexify (record) {
  const a = record.publisherId
  return a === undefined ? [] : [a]
}

// '@peartubeIndex/admissionTombstones' value encoding
const collection27_enc = getEncoding('@peartubeIndex/admissionTombstone/hyperdb#27')

// '@peartubeIndex/admissionTombstones' reconstruction function
function collection27_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection27_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection27.decodedVersion = c.uint.decode(state)
  const record = collection27_enc.decode(state)
  record.publisherId = key[0]
  return record
}
// '@peartubeIndex/admissionTombstones' key reconstruction function
function collection27_reconstruct_key (keyBuf) {
  const key = collection27_key.decode(keyBuf)
  return {
    publisherId: key[0]
  }
}

// '@peartubeIndex/admissionTombstones'
const collection27 = {
  name: '@peartubeIndex/admissionTombstones',
  id: 27,
  version: 2,
  encodeKey (record) {
    const key = [record.publisherId]
    return collection27_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection27_key.encodeRange({
      gt: gt ? collection27_indexify(gt) : null,
      lt: lt ? collection27_indexify(lt) : null,
      gte: gte ? collection27_indexify(gte) : null,
      lte: lte ? collection27_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection27_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection27_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection27_reconstruct,
  reconstructKey: collection27_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@peartubeIndex/usage-by-scope' collection key
const index28_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING
], { prefix: 28 })

function index28_indexify (record) {
  const arr = []

  const a0 = record.scope
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.bucketId
  if (a1 === undefined) return arr
  arr.push(a1)

  const a2 = record.publisherId
  if (a2 === undefined) return arr
  arr.push(a2)

  const a3 = record.publisherId
  if (a3 === undefined) return arr
  arr.push(a3)

  const a4 = record.scope
  if (a4 === undefined) return arr
  arr.push(a4)

  const a5 = record.bucketId
  if (a5 === undefined) return arr
  arr.push(a5)

  return arr
}

// '@peartubeIndex/usage-by-scope'
const index28 = {
  name: '@peartubeIndex/usage-by-scope',
  version: 2,
  id: 28,
  encodeKey (record) {
    return index28_key.encode(index28_indexify(record))
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return index28_key.encodeRange({
      gt: gt ? index28_indexify(gt) : null,
      lt: lt ? index28_indexify(lt) : null,
      gte: gte ? index28_indexify(gte) : null,
      lte: lte ? index28_indexify(lte) : null
    })
  },
  encodeValue: (record) => index28.collection.encodeKey(record),
  encodeIndexKeys (record, context) {
    return [index28_key.encode([record.scope, record.bucketId, record.publisherId, record.publisherId, record.scope, record.bucketId])]
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection26.indexes.length,
  collection: collection26
}
collection26.indexes.push(index28)

const collections = [
  collection0,
  collection1,
  collection2,
  collection3,
  collection4,
  collection5,
  collection6,
  collection26,
  collection27
]

const indexes = [
  index7,
  index8,
  index9,
  index10,
  index11,
  index12,
  index13,
  index14,
  index15,
  index16,
  index17,
  index18,
  index19,
  index20,
  index21,
  index22,
  index23,
  index24,
  index25,
  index28
]

export default { versions, collections, indexes, resolveCollection, resolveIndex }

function resolveCollection (name) {
  switch (name) {
    case '@peartubeIndex/sourceRecords': return collection0
    case '@peartubeIndex/sourceCursors': return collection1
    case '@peartubeIndex/externalReferenceProjections': return collection2
    case '@peartubeIndex/publicationProjections': return collection3
    case '@peartubeIndex/renditionProjections': return collection4
    case '@peartubeIndex/availabilityProjections': return collection5
    case '@peartubeIndex/relationshipEdges': return collection6
    case '@peartubeIndex/usageCounters': return collection26
    case '@peartubeIndex/admissionTombstones': return collection27
    default: return null
  }
}

function resolveIndex (name) {
  switch (name) {
    case '@peartubeIndex/source-records-by-publisher': return index7
    case '@peartubeIndex/source-cursors-by-publisher': return index8
    case '@peartubeIndex/external-references-by-publisher': return index9
    case '@peartubeIndex/publications-by-publisher': return index10
    case '@peartubeIndex/renditions-by-publisher': return index11
    case '@peartubeIndex/availability-by-publisher': return index12
    case '@peartubeIndex/relationships-by-publisher': return index13
    case '@peartubeIndex/external-reference-exact': return index14
    case '@peartubeIndex/entity-exact': return index15
    case '@peartubeIndex/publication-exact': return index16
    case '@peartubeIndex/publication-by-work': return index17
    case '@peartubeIndex/normalized-title': return index18
    case '@peartubeIndex/asset-exact': return index19
    case '@peartubeIndex/rendition-exact': return index20
    case '@peartubeIndex/availability-by-asset': return index21
    case '@peartubeIndex/relationship-by-type': return index22
    case '@peartubeIndex/relationship-by-from': return index23
    case '@peartubeIndex/relationship-by-to': return index24
    case '@peartubeIndex/token-prefix': return index25
    case '@peartubeIndex/usage-by-scope': return index28
    default: return null
  }
}
