/**
 * Video Player Desktop Styles
 *
 * CSS-in-JS styles for the video player overlay on Pear desktop.
 */

import React from 'react'
import { colors } from '@/lib/colors'

export const desktopStyles: Record<string, React.CSSProperties> = {
  overlay: {
    position: 'fixed',
    top: 108, // PEAR_BAR_HEIGHT (52) + HEADER_HEIGHT (56)
    left: 240, // SIDEBAR_WIDTH
    right: 0,
    bottom: 0,
    backgroundColor: colors.bg,
    zIndex: 1000, // Higher than header (100) and sidebar (50) to ensure full coverage
    overflow: 'auto',
  },
  container: {
    display: 'flex',
    flexDirection: 'row',
    padding: 24,
    gap: 24,
    maxWidth: 1600,
  },
  mainColumn: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },
  videoWrapper: {
    position: 'relative',
    backgroundColor: '#000',
    borderRadius: 12,
    overflow: 'hidden',
  },
  castPlaceholder: {
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.bgSecondary,
    gap: 10,
    flexDirection: 'column',
  },
  castTextBlock: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 4,
    maxWidth: 520,
  },
  castTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
  },
  castSubtitle: {
    fontSize: 13,
    color: colors.textMuted,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  placeholder: {
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.bgSecondary,
  },
  placeholderText: {
    fontSize: 48,
    color: colors.primary,
    fontWeight: '600',
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.7)',
  },
  videoInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  playerControls: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '10px 12px',
    backgroundColor: colors.bgSecondary,
    borderRadius: 10,
  },
  controlButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    border: `1px solid ${colors.border}`,
    backgroundColor: colors.bg,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
  },
  seekRow: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    gap: 10,
  },
  seekInput: {
    flex: 1,
    accentColor: colors.primary,
    outline: 'none',
    cursor: 'pointer',
  },
  timeLabel: {
    fontSize: 12,
    color: colors.textMuted,
    minWidth: 90,
    textAlign: 'right',
    fontVariantNumeric: 'tabular-nums',
  },
  title: {
    fontSize: 20,
    fontWeight: '600',
    color: colors.text,
    margin: 0,
    lineHeight: 1.3,
  },
  castBanner: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '8px 12px',
    backgroundColor: colors.bgSecondary,
    border: `1px solid ${colors.border}`,
    borderRadius: 999,
    width: 'fit-content',
  },
  castBannerText: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  castDisconnectButton: {
    marginLeft: 8,
    backgroundColor: 'transparent',
    border: 'none',
    color: colors.primary,
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: '600',
  },
  meta: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    fontSize: 14,
    color: colors.textMuted,
  },
  dot: {
    color: colors.textMuted,
  },
  channelRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    paddingTop: 12,
    borderTop: `1px solid ${colors.border}`,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.primary,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  channelInfo: {
    display: 'flex',
    flexDirection: 'column',
  },
  channelName: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.text,
  },
  channelKey: {
    fontSize: 12,
    color: colors.textMuted,
  },
  actions: {
    display: 'flex',
    gap: 12,
    paddingTop: 12,
  },
  actionButton: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '8px 16px',
    backgroundColor: colors.bgSecondary,
    border: 'none',
    borderRadius: 20,
    color: colors.text,
    fontSize: 14,
    fontWeight: '500',
  },
  actionLabel: {
    color: colors.text,
  },
  reactionButton: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '8px 16px',
    border: 'none',
    borderRadius: 20,
    fontSize: 14,
    fontWeight: '500',
    cursor: 'pointer',
  },
  description: {
    paddingTop: 16,
    borderTop: `1px solid ${colors.border}`,
  },
  descriptionText: {
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 1.6,
    margin: 0,
  },
  closeButton: {
    position: 'absolute',
    top: 24,
    right: 24,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.bgSecondary,
    border: 'none',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'background-color 0.15s ease',
  },
  minimizeButton: {
    position: 'absolute',
    top: 24,
    right: 72,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.bgSecondary,
    border: 'none',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'background-color 0.15s ease',
  },
  // P2P Stats styles (old simplified version)
  statsSection: {
    display: 'flex',
    gap: 24,
    padding: '12px 0',
    borderTop: `1px solid ${colors.border}`,
  },
  statItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  statText: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  // P2P Stats Bar - matching mobile design
  p2pStatsBar: {
    backgroundColor: colors.bgSecondary,
    borderRadius: 12,
    padding: 16,
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  p2pStatsRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 16,
    flexWrap: 'wrap',
  },
  p2pStatItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  statusLabel: {
    fontSize: 14,
    fontWeight: '600',
  },
  p2pStatText: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  p2pStatSpeed: {
    fontSize: 14,
    color: '#4ade80',
  },
  p2pStatSpeedUp: {
    fontSize: 14,
    color: '#fbbf24',
  },
  p2pStatsRowSecondary: {
    display: 'flex',
    alignItems: 'center',
    gap: 16,
    flexWrap: 'wrap',
  },
  p2pStatDetail: {
    fontSize: 13,
    color: colors.textMuted,
  },
  p2pStatProgress: {
    fontSize: 14,
    fontWeight: '600',
  },
  // Comments styles
  commentsSection: {
    paddingTop: 16,
    borderTop: `1px solid ${colors.border}`,
  },
  commentsHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  commentsTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
    margin: 0,
  },
  refreshButton: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '6px 12px',
    backgroundColor: 'transparent',
    border: 'none',
    color: colors.primary,
    fontSize: 13,
    cursor: 'pointer',
  },
  commentComposer: {
    display: 'flex',
    gap: 12,
    marginBottom: 16,
  },
  commentInput: {
    flex: 1,
    padding: '10px 14px',
    backgroundColor: colors.bgSecondary,
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    color: colors.text,
    fontSize: 14,
    outline: 'none',
  },
  postButton: {
    padding: '10px 20px',
    backgroundColor: colors.primary,
    border: 'none',
    borderRadius: 8,
    color: '#fff',
    fontSize: 14,
    fontWeight: '500',
    cursor: 'pointer',
  },
  commentsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },
  noComments: {
    color: colors.textMuted,
    fontSize: 14,
    textAlign: 'center',
    padding: 20,
    margin: 0,
  },
  commentItem: {
    padding: 12,
    backgroundColor: colors.bgSecondary,
    borderRadius: 8,
  },
  commentHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  commentAuthor: {
    fontSize: 13,
    fontWeight: '500',
    color: colors.text,
  },
  commentTime: {
    fontSize: 12,
    color: colors.textMuted,
  },
  adminBadge: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.primary,
    backgroundColor: `${colors.primary}22`,
    padding: '2px 6px',
    borderRadius: 4,
  },
  commentText: {
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 1.5,
    margin: 0,
  },
  replies: {
    marginTop: 12,
    marginLeft: 16,
    paddingLeft: 12,
    borderLeft: `2px solid ${colors.border}`,
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  replyItem: {
    padding: 8,
  },
}
