/**
 * Video Player Mobile Styles
 *
 * React Native StyleSheet for the video player overlay on iOS/Android.
 */

import { StyleSheet } from 'react-native'
import { colors } from '@/lib/colors'
import { MINI_PIP_WIDTH, MINI_PIP_HEIGHT } from './constants'

export const styles = StyleSheet.create({
  container: {
    // Use black background to ensure PiP shows black (not grey) for any offset areas
    // This makes the video look properly letterboxed rather than broken
    backgroundColor: '#000',
    overflow: 'hidden',
  },
  // Landscape fullscreen styles
  landscapeContainer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#000',
    zIndex: 9999,
  },
  landscapeAnimatedContainer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#000',
  },
  landscapeExitButton: {
    position: 'absolute',
    top: 16,
    right: 16,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 20,
  },
  landscapeTimeDisplay: {
    position: 'absolute',
    bottom: 40,
    left: 16,
    backgroundColor: 'rgba(0,0,0,0.6)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 4,
    zIndex: 20,
  },
  landscapeProgressContainer: {
    position: 'absolute',
    bottom: 16,
    left: 16,
    right: 16,
    height: 24,
    justifyContent: 'center',
    zIndex: 20,
  },
  landscapeVideoWrapper: {
    ...StyleSheet.absoluteFillObject,
    flex: 1,
    backgroundColor: '#000',
  },
  videoWrapper: {
    backgroundColor: '#000',
    overflow: 'hidden',
  },
  videoBackground: {
    flex: 1,
    backgroundColor: '#000',
  },
  landscapeVideoBackground: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#000',
  },
  videoPlaceholder: {
    flex: 1,
    backgroundColor: colors.bgHover,
    justifyContent: 'center',
    alignItems: 'center',
  },
  placeholderText: {
    color: colors.primary,
    fontSize: 32,
    fontWeight: '600',
  },
  castPlaceholder: {
    flex: 1,
    backgroundColor: colors.bgHover,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 24,
  },
  castPlaceholderTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '600',
  },
  castPlaceholderSubtitle: {
    color: colors.textMuted,
    fontSize: 12,
  },
  castBanner: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: colors.bgCard,
    alignSelf: 'flex-start',
  },
  castBannerText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '600',
  },
  castBannerAction: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: colors.bgSecondary,
  },
  castBannerActionText: {
    color: colors.text,
    fontSize: 11,
    fontWeight: '600',
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    color: '#fff',
    marginTop: 12,
    fontSize: 14,
  },
  // Custom controls overlay - positioning handled by controlsOverlayStyle animated style
  controlsOverlayBase: {
    backgroundColor: 'rgba(0,0,0,0.4)',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 48,
  },
  controlButton: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
  },
  controlButtonLarge: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(0,0,0,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  controlButtonText: {
    color: '#fff',
    fontSize: 12,
    marginTop: 4,
  },
  seekFeedback: {
    position: 'absolute',
    top: '50%',
    marginTop: -40,
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  seekFeedbackLeft: {
    left: '15%',
  },
  seekFeedbackRight: {
    right: '15%',
  },
  seekFeedbackText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
    marginTop: 4,
  },
  minimizeButton: {
    position: 'absolute',
    left: 12,
    zIndex: 10,
  },
  minimizeButtonInner: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  speedButton: {
    position: 'absolute',
    right: 12,
    zIndex: 10,
  },
  speedButtonInner: {
    minWidth: 50,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  speedButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  castButton: {
    position: 'absolute',
    right: 60,
    zIndex: 10,
    elevation: 10,
  },
  castButtonInner: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fullscreenButton: {
    position: 'absolute',
    right: 12,
    zIndex: 10,
    elevation: 10,
  },
  fullscreenButtonLandscape: {
    bottom: 16,
    right: 16,
  },
  fullscreenButtonInner: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  // ── Scrubber: Track layers (spec §1, §9) ──────────────────────────────
  scrubberTrackWrapper: {
    position: 'relative',
    height: 8,
  },
  scrubberTrackBg: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
  },
  scrubberBufferFill: {
    position: 'absolute',
    left: 0,
    top: 0,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(145, 71, 255, 0.35)',
  },
  scrubberPlayedFill: {
    position: 'absolute',
    left: 0,
    top: 0,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#9147ff',
  },
  // ── Scrubber: Handle (spec §3) ───────────────────────────────────────
  scrubberHandleNew: {
    position: 'absolute',
    left: 0,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.40,
    shadowRadius: 3,
    elevation: 4,
  },
  // ── Scrubber: Tooltip (spec §4) ──────────────────────────────────────
  scrubberTooltip: {
    position: 'absolute',
    left: 0,
    alignItems: 'center',
  },
  scrubberTooltipBubble: {
    backgroundColor: '#1f1f23',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: 'rgba(48, 48, 53, 0.8)',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.50,
    shadowRadius: 6,
    elevation: 8,
  } as any,
  scrubberTooltipText: {
    color: '#efeff1',
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 0.3,
    fontVariant: ['tabular-nums'] as any,
    textAlign: 'center',
    minWidth: 40,
  } as any,
  scrubberTooltipArrow: {
    width: 0,
    height: 0,
    borderLeftWidth: 6,
    borderLeftColor: 'transparent',
    borderRightWidth: 6,
    borderRightColor: 'transparent',
    borderTopWidth: 6,
    borderTopColor: '#1f1f23',
    marginTop: -1,
    alignSelf: 'center',
  } as any,
  // ── ControlsPanel: Unified bottom controls ─────────────────────────────
  controlsPanel: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 16,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    overflow: 'hidden',
    zIndex: 15,
  },
  controlsPanelTimeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  controlsPanelButtonGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  controlsPanelButton: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  // Legacy thin progress bar styles kept for web fallback
  thinProgressBg: {
    height: 3,
    backgroundColor: 'rgba(255,255,255,0.3)',
  },
  thinProgressFill: {
    height: '100%',
    backgroundColor: colors.primary,
  },
  timeDisplayRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  timeTextCurrent: {
    color: '#efeff1',
    fontSize: 12,
    fontWeight: '500',
    fontVariant: ['tabular-nums'] as any,
  } as any,
  timeTextMuted: {
    color: '#7a7a85',
    fontSize: 12,
    fontWeight: '500',
    fontVariant: ['tabular-nums'] as any,
  } as any,
  timeDisplayAction: {
    minWidth: 36,
    minHeight: 36,
    padding: 8,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0.8,
  },
  // Fullscreen progress bar (shown with controls)
  fullscreenProgressContainer: {
    position: 'absolute',
    bottom: 12,
    left: 12,
    right: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    zIndex: 10,
  },
  fullscreenProgressBar: {
    flex: 1,
    height: 24,
    justifyContent: 'center',
  },
  fullscreenProgressBg: {
    height: 4,
    backgroundColor: 'transparent',
    borderRadius: 2,
    overflow: 'hidden',
  },
  fullscreenProgressFill: {
    height: '100%',
    backgroundColor: colors.primary,
    borderRadius: 2,
  },
  seekHandle: {
    position: 'absolute',
    top: -5,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: colors.primary,
    marginLeft: -7,
  },
  timeText: {
    minWidth: 40,
  },
  // Mini player styles
  miniInfo: {
    position: 'absolute',
    left: MINI_PIP_WIDTH,
    right: 100,
    top: 0,
    height: MINI_PIP_HEIGHT,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  miniInfoText: {
    flex: 1,
    justifyContent: 'center',
  },
  miniTitle: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '500',
  },
  miniChannel: {
    color: colors.textMuted,
    fontSize: 12,
    marginTop: 2,
  },
  miniControls: {
    position: 'absolute',
    right: 8,
    top: 0,
    height: MINI_PIP_HEIGHT,
    flexDirection: 'row',
    alignItems: 'center',
  },
  miniControlButton: {
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
  },
  miniProgressBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  miniProgressFill: {
    height: '100%',
    backgroundColor: colors.primary,
  },
  miniPipOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  miniPipTopRow: {
    position: 'absolute',
    top: 8,
    left: 8,
    right: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  miniPipSmallButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  miniPipPlayPauseButton: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    width: 40,
    height: 40,
    marginTop: -20,
    marginLeft: -20,
    borderRadius: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  } as any,
  miniPipControlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
  },
  miniPipSkipButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  miniPipPlayButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  miniPipProgressBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 3,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },
  miniPipProgressFill: {
    height: '100%',
    backgroundColor: colors.primary,
  },
  // Fullscreen content styles
  // Black background ensures PiP shows video + black (not video + colored content)
  // when native hideNonVideoContent hides the ScrollView
  fullscreenContent: {
    // Position is set by animated style (absolute with top: videoHeight)
    // No flex needed since we use explicit positioning
    backgroundColor: '#000',
  },
  scrollContent: {
    flex: 1,
    backgroundColor: '#000',
  },
  videoInfo: {
    padding: 16,
    backgroundColor: '#000',
  },
  videoTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '600',
    lineHeight: 24,
  },
  videoMeta: {
    color: colors.textMuted,
    fontSize: 13,
    marginTop: 6,
  },
  actions: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 12,
    backgroundColor: '#000',
    paddingHorizontal: 8,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  actionButton: {
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  actionLabel: {
    color: colors.text,
    fontSize: 11,
    marginTop: 4,
  },
  actionLabelActive: {
    color: colors.primary,
  },
  toast: {
    position: 'absolute',
    left: 16,
    right: 16,
    padding: 12,
    borderRadius: 12,
    backgroundColor: 'rgba(0,0,0,0.85)',
    borderWidth: 1,
    borderColor: colors.border,
  },
  toastTitle: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 2,
  },
  toastText: {
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 16,
  },
  channelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
  },
  channelAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  channelAvatarText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },
  channelInfo: {
    flex: 1,
    marginLeft: 12,
  },
  channelName: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '500',
  },
  channelSubs: {
    color: colors.textMuted,
    fontSize: 12,
    marginTop: 2,
  },
  subscribeButton: {
    backgroundColor: colors.primary,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  subscribeText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '600',
  },
  divider: {
    height: 8,
    backgroundColor: colors.bgSecondary,
    marginVertical: 8,
  },
  description: {
    padding: 16,
  },
  descriptionText: {
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  // Comments styles
  commentsSection: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 16,
  },
  commentsTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 10,
  },
  commentsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  refreshButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.bgSecondary,
  },
  refreshButtonText: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '600',
  },
  replyIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.primary + '20',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    marginBottom: 8,
  },
  replyIndicatorText: {
    color: colors.primary,
    fontSize: 13,
  },
  cancelReplyButton: {
    padding: 4,
  },
  commentComposer: {
    backgroundColor: colors.bgSecondary,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    padding: 10,
    marginBottom: 12,
  },
  commentInput: {
    color: colors.text,
    minHeight: 44,
    fontSize: 14,
    padding: 0,
  },
  commentButton: {
    alignSelf: 'flex-end',
    marginTop: 10,
    backgroundColor: colors.primary,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
  },
  commentButtonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 13,
  },
  commentsEmpty: {
    color: colors.textMuted,
    fontSize: 13,
    paddingVertical: 8,
  },
  commentItem: {
    backgroundColor: colors.bgSecondary,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    padding: 10,
  },
  commentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  commentAuthor: {
    color: colors.textMuted,
    fontSize: 12,
    flex: 1,
  },
  adminBadge: {
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: 999,
    paddingHorizontal: 6,
    paddingVertical: 2,
    fontSize: 11,
    color: colors.primary,
    fontWeight: '600',
  },
  pendingBadge: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    paddingHorizontal: 6,
    paddingVertical: 2,
    fontSize: 11,
    color: colors.textMuted,
  },
  commentActions: {
    flexDirection: 'row',
    gap: 8,
    marginLeft: 'auto',
  },
  commentActionButton: {
    padding: 4,
  },
  commentText: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 20,
  },
  commentTextPending: {
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 20,
  },
  repliesContainer: {
    marginLeft: 20,
    marginTop: 8,
    gap: 8,
    borderLeftWidth: 2,
    borderLeftColor: colors.border,
    paddingLeft: 12,
  },
  replyItem: {
    backgroundColor: colors.bgSecondary,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    padding: 8,
  },
  loadMoreButton: {
    alignItems: 'center',
    paddingVertical: 12,
    backgroundColor: colors.bgSecondary,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  loadMoreText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: '500',
  },
  // P2P Stats Bar styles - Clean with all stats
  statsBar: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderRadius: 10,
    marginHorizontal: 12,
    marginTop: 8,
  },
  statsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  statsRowSecondary: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    justifyContent: 'space-between',
  },
  statItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  statsDivider: {
    width: 1,
    height: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    marginHorizontal: 10,
  },
  statLabel: {
    fontSize: 13,
    fontWeight: '600',
  },
  statText: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 13,
  },
  statSpeed: {
    color: '#60a5fa',
    fontSize: 13,
    fontWeight: '500',
  },
  statSpeedUp: {
    color: '#4ade80',
    fontSize: 13,
    fontWeight: '500',
  },
  statDetail: {
    color: 'rgba(255, 255, 255, 0.5)',
    fontSize: 11,
  },
  statProgress: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 12,
    fontWeight: '600',
  },
  statProgressComplete: {
    color: '#4ade80',
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  progressBarBg: {
    marginTop: 10,
    height: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 2,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#fbbf24',
    borderRadius: 2,
  },
})
