// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @peartubeIndex/sourceRecord
const encoding0 = {
  preencode(state, m) {
    c.string.preencode(state, m.publisherId)
    c.uint64.preencode(state, m.catalogEpoch)
    c.string.preencode(state, m.recordId)
    c.string.preencode(state, m.recordType)
    c.uint64.preencode(state, m.sourceSequence)
    c.buffer.preencode(state, m.canonicalEnvelope)
    c.string.preencode(state, m.projectionState)
    c.uint64.preencode(state, m.ingestedAt)
  },
  encode(state, m) {
    c.string.encode(state, m.publisherId)
    c.uint64.encode(state, m.catalogEpoch)
    c.string.encode(state, m.recordId)
    c.string.encode(state, m.recordType)
    c.uint64.encode(state, m.sourceSequence)
    c.buffer.encode(state, m.canonicalEnvelope)
    c.string.encode(state, m.projectionState)
    c.uint64.encode(state, m.ingestedAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.uint64.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.uint64.decode(state)
    const r5 = c.buffer.decode(state)
    const r6 = c.string.decode(state)
    const r7 = c.uint64.decode(state)

    return {
      publisherId: r0,
      catalogEpoch: r1,
      recordId: r2,
      recordType: r3,
      sourceSequence: r4,
      canonicalEnvelope: r5,
      projectionState: r6,
      ingestedAt: r7
    }
  }
}

// @peartubeIndex/sourceCursor
const encoding1 = {
  preencode(state, m) {
    c.string.preencode(state, m.publisherId)
    c.uint64.preencode(state, m.catalogEpoch)
    c.string.preencode(state, m.catalogBootstrapKey)
    c.uint64.preencode(state, m.viewFork)
    c.uint64.preencode(state, m.viewVersion)
    c.uint64.preencode(state, m.sourceHead)
    c.string.preencode(state, m.lastVerifiedDescriptor)
  },
  encode(state, m) {
    c.string.encode(state, m.publisherId)
    c.uint64.encode(state, m.catalogEpoch)
    c.string.encode(state, m.catalogBootstrapKey)
    c.uint64.encode(state, m.viewFork)
    c.uint64.encode(state, m.viewVersion)
    c.uint64.encode(state, m.sourceHead)
    c.string.encode(state, m.lastVerifiedDescriptor)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.uint64.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.uint64.decode(state)
    const r4 = c.uint64.decode(state)
    const r5 = c.uint64.decode(state)
    const r6 = c.string.decode(state)

    return {
      publisherId: r0,
      catalogEpoch: r1,
      catalogBootstrapKey: r2,
      viewFork: r3,
      viewVersion: r4,
      sourceHead: r5,
      lastVerifiedDescriptor: r6
    }
  }
}

// @peartubeIndex/externalReferenceProjection
const encoding2 = {
  preencode(state, m) {
    c.string.preencode(state, m.publisherId)
    c.string.preencode(state, m.sourceRecordRef)
    c.string.preencode(state, m.namespace)
    c.string.preencode(state, m.normalizedIdentifier)
    c.string.preencode(state, m.entityKind)
    c.string.preencode(state, m.entityId)
    state.end++ // flags are fixed size

    if (m.evidenceWeight) c.uint64.preencode(state, m.evidenceWeight)
  },
  encode(state, m) {
    const flags = m.evidenceWeight ? 1 : 0

    c.string.encode(state, m.publisherId)
    c.string.encode(state, m.sourceRecordRef)
    c.string.encode(state, m.namespace)
    c.string.encode(state, m.normalizedIdentifier)
    c.string.encode(state, m.entityKind)
    c.string.encode(state, m.entityId)
    c.uint8.encode(state, flags)

    if (m.evidenceWeight) c.uint64.encode(state, m.evidenceWeight)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.string.decode(state)
    const r5 = c.string.decode(state)
    const flags = c.uint8.decode(state)

    return {
      publisherId: r0,
      sourceRecordRef: r1,
      namespace: r2,
      normalizedIdentifier: r3,
      entityKind: r4,
      entityId: r5,
      evidenceWeight: (flags & 1) !== 0 ? c.uint64.decode(state) : 0
    }
  }
}

// @peartubeIndex/publicationProjection
const encoding3 = {
  preencode(state, m) {
    c.string.preencode(state, m.publisherId)
    c.string.preencode(state, m.sourceRecordRef)
    c.string.preencode(state, m.publicationId)
    c.string.preencode(state, m.workEntityId)
    c.string.preencode(state, m.normalizedTitle)
    state.end++ // flags are fixed size

    if (m.releaseYear) c.uint64.preencode(state, m.releaseYear)
    c.string.preencode(state, m.manifestId)
    if (m.provenanceSummary) c.string.preencode(state, m.provenanceSummary)
  },
  encode(state, m) {
    const flags = (m.releaseYear ? 1 : 0) | (m.provenanceSummary ? 2 : 0)

    c.string.encode(state, m.publisherId)
    c.string.encode(state, m.sourceRecordRef)
    c.string.encode(state, m.publicationId)
    c.string.encode(state, m.workEntityId)
    c.string.encode(state, m.normalizedTitle)
    c.uint8.encode(state, flags)

    if (m.releaseYear) c.uint64.encode(state, m.releaseYear)
    c.string.encode(state, m.manifestId)
    if (m.provenanceSummary) c.string.encode(state, m.provenanceSummary)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.string.decode(state)
    const flags = c.uint8.decode(state)

    return {
      publisherId: r0,
      sourceRecordRef: r1,
      publicationId: r2,
      workEntityId: r3,
      normalizedTitle: r4,
      releaseYear: (flags & 1) !== 0 ? c.uint64.decode(state) : 0,
      manifestId: c.string.decode(state),
      provenanceSummary: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @peartubeIndex/renditionProjection
const encoding4 = {
  preencode(state, m) {
    c.string.preencode(state, m.publisherId)
    c.string.preencode(state, m.sourceRecordRef)
    c.string.preencode(state, m.renditionId)
    c.string.preencode(state, m.assetId)
    state.end++ // flags are fixed size

    if (m.format) c.string.preencode(state, m.format)
    if (m.codec) c.string.preencode(state, m.codec)
    if (m.dimensions) c.string.preencode(state, m.dimensions)
    if (m.mediaFeatures) c.string.preencode(state, m.mediaFeatures)
    if (m.byteLength) c.uint64.preencode(state, m.byteLength)
  },
  encode(state, m) {
    const flags =
      (m.format ? 1 : 0) |
      (m.codec ? 2 : 0) |
      (m.dimensions ? 4 : 0) |
      (m.mediaFeatures ? 8 : 0) |
      (m.byteLength ? 16 : 0)

    c.string.encode(state, m.publisherId)
    c.string.encode(state, m.sourceRecordRef)
    c.string.encode(state, m.renditionId)
    c.string.encode(state, m.assetId)
    c.uint8.encode(state, flags)

    if (m.format) c.string.encode(state, m.format)
    if (m.codec) c.string.encode(state, m.codec)
    if (m.dimensions) c.string.encode(state, m.dimensions)
    if (m.mediaFeatures) c.string.encode(state, m.mediaFeatures)
    if (m.byteLength) c.uint64.encode(state, m.byteLength)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const flags = c.uint8.decode(state)

    return {
      publisherId: r0,
      sourceRecordRef: r1,
      renditionId: r2,
      assetId: r3,
      format: (flags & 1) !== 0 ? c.string.decode(state) : null,
      codec: (flags & 2) !== 0 ? c.string.decode(state) : null,
      dimensions: (flags & 4) !== 0 ? c.string.decode(state) : null,
      mediaFeatures: (flags & 8) !== 0 ? c.string.decode(state) : null,
      byteLength: (flags & 16) !== 0 ? c.uint64.decode(state) : 0
    }
  }
}

// @peartubeIndex/availabilityProjection
const encoding5 = {
  preencode(state, m) {
    c.string.preencode(state, m.publisherId)
    c.string.preencode(state, m.sourceRecordRef)
    c.string.preencode(state, m.assetId)
    c.string.preencode(state, m.observerId)
    c.uint64.preencode(state, m.observedSeeders)
    c.uint64.preencode(state, m.observedCompleteSeeders)
    c.uint64.preencode(state, m.observedAt)
    c.uint64.preencode(state, m.expiresAt)
    c.string.preencode(state, m.availabilityState)
  },
  encode(state, m) {
    c.string.encode(state, m.publisherId)
    c.string.encode(state, m.sourceRecordRef)
    c.string.encode(state, m.assetId)
    c.string.encode(state, m.observerId)
    c.uint64.encode(state, m.observedSeeders)
    c.uint64.encode(state, m.observedCompleteSeeders)
    c.uint64.encode(state, m.observedAt)
    c.uint64.encode(state, m.expiresAt)
    c.string.encode(state, m.availabilityState)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.uint64.decode(state)
    const r5 = c.uint64.decode(state)
    const r6 = c.uint64.decode(state)
    const r7 = c.uint64.decode(state)
    const r8 = c.string.decode(state)

    return {
      publisherId: r0,
      sourceRecordRef: r1,
      assetId: r2,
      observerId: r3,
      observedSeeders: r4,
      observedCompleteSeeders: r5,
      observedAt: r6,
      expiresAt: r7,
      availabilityState: r8
    }
  }
}

// @peartubeIndex/relationshipEdge
const encoding6 = {
  preencode(state, m) {
    c.string.preencode(state, m.publisherId)
    c.string.preencode(state, m.sourceRecordRef)
    c.string.preencode(state, m.relationType)
    c.string.preencode(state, m.fromId)
    c.string.preencode(state, m.toId)
  },
  encode(state, m) {
    c.string.encode(state, m.publisherId)
    c.string.encode(state, m.sourceRecordRef)
    c.string.encode(state, m.relationType)
    c.string.encode(state, m.fromId)
    c.string.encode(state, m.toId)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.string.decode(state)

    return {
      publisherId: r0,
      sourceRecordRef: r1,
      relationType: r2,
      fromId: r3,
      toId: r4
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@peartubeIndex/sourceRecord':
      return encoding0
    case '@peartubeIndex/sourceCursor':
      return encoding1
    case '@peartubeIndex/externalReferenceProjection':
      return encoding2
    case '@peartubeIndex/publicationProjection':
      return encoding3
    case '@peartubeIndex/renditionProjection':
      return encoding4
    case '@peartubeIndex/availabilityProjection':
      return encoding5
    case '@peartubeIndex/relationshipEdge':
      return encoding6
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
